#!/usr/bin/env -S npx tsx
/**
 * gen-mobile-nav-seed — BOOTSTRAP-NAV-MOBILE-CATALOG
 *
 * Promotes the mobile app's screens + mode-pills from the compile-time
 * NAVIGATION_CATALOG into the admin-manageable `nav_catalog` / `nav_catalog_i18n`
 * tables, so every screen and route is editable from the Vitana Navigator admin
 * (and not merely gap-filled at runtime).
 *
 * Design:
 *   - ADDITIVE ONLY. Emits rows for screen_ids that are NOT already in the DB
 *     (the existing 42 shared rows are passed in via EXISTING_SCREEN_IDS) so we
 *     never touch / clobber rows an admin may have edited.
 *   - Idempotent without needing the original deterministic UUIDs: each row is a
 *     CTE that upserts nav_catalog keyed on the `screen_id` partial-unique index
 *     (tenant_id IS NULL), RETURNING id, then upserts its i18n rows.
 *   - EXCLUDES `developer` screens (admin/dev tooling, not in the mobile app) and
 *     overlay entries (entry_kind='overlay' / `overlay` field) — overlays cannot
 *     be expressed as nav_catalog rows (no entry_kind/overlay columns) and must
 *     stay gap-filled from TS so the drawer marker keeps working.
 *   - mobile_route is intentionally NOT seeded: nav-catalog-db.ts already
 *     inherits it from TS by screen_id at cache-build time (VTID-NAV-MOBILEROUTE).
 *
 * Usage:
 *   npx tsx scripts/gen-mobile-nav-seed.ts > ../../supabase/migrations/<ts>_nav_catalog_mobile.sql
 */
import { NAVIGATION_CATALOG } from '../src/lib/navigation-catalog';

// The 42 shared screen_ids already present in nav_catalog (queried live).
// Anything here is left untouched.
const EXISTING_SCREEN_IDS = new Set<string>([
  'AI.COMPANION','AI.RECOMMENDATIONS','AUTH.ALKALMA_PORTAL','AUTH.EARTHLINKS_PORTAL','AUTH.GENERIC',
  'AUTH.MAXINA_PORTAL','AUTOPILOT.MY_JOURNEY','BUSINESS.ANALYTICS','BUSINESS.CLIENTS','BUSINESS.OVERVIEW',
  'BUSINESS.SELL_EARN','BUSINESS.SERVICES','COMM.EVENTS','COMM.LIVE_ROOMS','COMM.MEDIA_HUB','COMM.OVERVIEW',
  'DISCOVER.DEALS','DISCOVER.DOCTORS_COACHES','DISCOVER.OVERVIEW','DISCOVER.SUPPLEMENTS','DISCOVER.WELLNESS_SERVICES',
  'HEALTH.EDUCATION','HEALTH.MY_BIOLOGY','HEALTH.OVERVIEW','HEALTH.PLANS','HEALTH.SERVICES_HUB','HOME.AI_FEED',
  'HOME.MATCHES','HOME.OVERVIEW','INBOX.OVERVIEW','INBOX.REMINDERS','MEMORY.DIARY','MEMORY.OVERVIEW',
  'PUBLIC.LANDING','PUBLIC.PRIVACY','SETTINGS.NOTIFICATIONS','SETTINGS.OVERVIEW','SETTINGS.PRIVACY',
  'WALLET.BALANCE','WALLET.OVERVIEW','WALLET.REWARDS','WALLET.SUBSCRIPTIONS',
]);

// Categories that are NOT part of the mobile app surface.
const EXCLUDE_CATEGORIES = new Set<string>(['developer']);

function q(s: string): string {
  // SQL single-quote escaping.
  return (s ?? '').replace(/'/g, "''");
}

type Entry = (typeof NAVIGATION_CATALOG)[number] & {
  entry_kind?: string;
  overlay?: unknown;
};

const entries = (NAVIGATION_CATALOG as ReadonlyArray<Entry>).filter((e) => {
  if (EXISTING_SCREEN_IDS.has(e.screen_id)) return false;
  if (EXCLUDE_CATEGORIES.has(e.category as string)) return false;
  if (e.entry_kind === 'overlay' || e.overlay) return false; // overlays stay TS-gap-filled
  return true;
});

const out: string[] = [];
out.push('-- BOOTSTRAP-NAV-MOBILE-CATALOG: promote mobile screens + mode-pills into');
out.push('-- the admin-manageable nav_catalog (generated by services/gateway/scripts/gen-mobile-nav-seed.ts).');
out.push('-- Additive + idempotent: upserts keyed on the screen_id shared-unique index;');
out.push('-- only screen_ids absent from the DB at generation time are included, so existing');
out.push('-- rows / admin edits are never touched. Overlays + developer screens excluded.');
out.push(`-- ${entries.length} screens.`);
out.push('BEGIN;');
out.push('');

for (const e of entries) {
  const route = q(e.route);
  const category = q(e.category as string);
  const access = q(e.access as string);
  const anon = e.anonymous_safe ? 'TRUE' : 'FALSE';
  const priority = Number((e as { priority?: number }).priority ?? 0) || 0;
  // related_kb_topics is jsonb in the DB; context_rules/override_triggers are not
  // present in the TS catalog, so we omit them and let the column defaults apply.
  const kb = q(JSON.stringify((e as { related_kb_topics?: string[] }).related_kb_topics ?? []));

  // i18n VALUES rows (en mandatory; include every lang present in TS).
  const langs = Object.keys(e.i18n);
  const i18nValues = langs
    .map((lang) => {
      const c = (e.i18n as Record<string, { title: string; description: string; when_to_visit: string }>)[lang];
      return `    ('${q(lang)}', '${q(c.title)}', '${q(c.description)}', '${q(c.when_to_visit)}')`;
    })
    .join(',\n');

  out.push(`-- ${e.screen_id}`);
  out.push(`WITH up AS (`);
  out.push(`  INSERT INTO nav_catalog (screen_id, tenant_id, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)`);
  out.push(`  VALUES ('${q(e.screen_id)}', NULL, '${route}', '${category}', '${access}', ${anon}, ${priority}, '${kb}'::jsonb, TRUE)`);
  out.push(`  ON CONFLICT (screen_id) WHERE tenant_id IS NULL`);
  out.push(`  DO UPDATE SET updated_at = now()`);
  out.push(`  RETURNING id`);
  out.push(`)`);
  out.push(`INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)`);
  out.push(`SELECT up.id, v.lang, v.title, v.description, v.wtv`);
  out.push(`FROM up CROSS JOIN (VALUES`);
  out.push(i18nValues);
  out.push(`) AS v(lang, title, description, wtv)`);
  out.push(`ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;`);
  out.push('');
}

out.push('COMMIT;');
process.stdout.write(out.join('\n') + '\n');
