#!/usr/bin/env -S node --loader ts-node/esm
/**
 * VTID-02783: sync-nav-catalog-from-manifest
 *
 * Reads `vitana-v1/src/navigation/screens.manifest.ts` and regenerates the
 * auto-managed block in `services/gateway/src/lib/navigation-catalog.ts`
 * between the `<auto:nav-catalog-start VTID-02783>` and `<auto:nav-catalog-end>`
 * markers.
 *
 * Usage:
 *   npm run nav:sync           — write changes to navigation-catalog.ts
 *   npm run nav:check          — exit 1 if catalog block is stale (CI gate)
 *
 * vitana-v1 path resolution (in order):
 *   1. $VITANA_V1_REPO_PATH env var
 *   2. ../../vitana-v1 (sibling fallback)
 *   3. /home/dstev/vitana-v1 (host-pinned fallback)
 *
 * If vitana-v1 isn't reachable, the script no-ops in --check mode (skips
 * silently — local dev convenience) but FAILS in --write mode to prevent a
 * silent partial regeneration.
 *
 * Failure modes (always non-zero exit):
 *   - Manifest entry has duplicate screen_id with the hand-curated block
 *   - Manifest entry's screen_id collides with an existing one
 *   - Type-mirror file out of sync between repos
 *   - --check mode and the regenerated block differs from on-disk
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { execSync } from 'node:child_process';

const SCRIPT_DIR = dirname(new URL(import.meta.url).pathname);
const GATEWAY_ROOT = resolve(SCRIPT_DIR, '..');
const CATALOG_PATH = join(GATEWAY_ROOT, 'src/lib/navigation-catalog.ts');
const TYPES_PATH = join(GATEWAY_ROOT, 'src/lib/screen-manifest-types.ts');

const START_MARKER = '// <auto:nav-catalog-start VTID-02783>';
const END_MARKER = '// <auto:nav-catalog-end>';

const HEADER_NOTICE = [
  '  // ⚠️  DO NOT EDIT — regenerated by services/gateway/scripts/sync-nav-catalog-from-manifest.ts',
  '  //     from vitana-v1/src/navigation/screens.manifest.ts.',
  '  //     Run `npm run nav:sync` after changing the manifest.',
].join('\n');

interface CliOpts {
  mode: 'write' | 'check';
}

function parseArgs(): CliOpts {
  const args = process.argv.slice(2);
  return { mode: args.includes('--check') ? 'check' : 'write' };
}

function resolveVitanaV1Root(): string | null {
  const candidates = [
    process.env.VITANA_V1_REPO_PATH,
    resolve(GATEWAY_ROOT, '../../../vitana-v1'),
    '/home/dstev/vitana-v1',
  ].filter(Boolean) as string[];

  for (const c of candidates) {
    if (existsSync(join(c, 'src/navigation/screens.manifest.ts'))) return c;
  }
  return null;
}

function loadManifest(v1Root: string): unknown[] {
  // Use `tsc --module commonjs` to compile the manifest TS file in isolation,
  // then require the resulting JS. ts-node ESM loader has issues resolving
  // intra-repo `import type` references, so transpiling is more reliable.
  const manifestSrc = join(v1Root, 'src/navigation/screens.manifest.ts');
  const typesSrc = join(v1Root, 'src/navigation/screen-manifest-types.ts');

  // Smallest possible eval: pull the SCREEN_MANIFEST array literal out via
  // dynamic require after stripping `import type` lines. This avoids needing
  // ts-node, vitana-v1's full tsconfig, etc.
  const raw = readFileSync(manifestSrc, 'utf8');
  // Replace the type import with a no-op so eval won't choke on it.
  const sanitized = raw
    .replace(/^import\s+type\s+[^;]+;\s*$/gm, '')
    .replace(/^export\s+type\s+\{[^}]+\}\s+from[^;]+;\s*$/gm, '');

  // Remove the `: ScreenManifestEntry[]` annotation (transpile equivalent).
  const stripped = sanitized.replace(/:\s*ScreenManifestEntry\[\]/g, '');

  // Wrap in a CommonJS-style module so we can eval it.
  const mod: { SCREEN_MANIFEST?: unknown[] } = {};
  const fn = new Function('module', 'exports', `${stripped.replace(/^export\s+const\s+/m, 'exports.')}\n`);
  // The `exports.SCREEN_MANIFEST = [...]` form — assign via property.
  const wrapped = stripped.replace(/^export\s+const\s+SCREEN_MANIFEST\s*=/m, '__exports__.SCREEN_MANIFEST =');
  // eslint-disable-next-line @typescript-eslint/no-implied-eval, no-new-func
  const evaluator = new Function('__exports__', `${wrapped}\nreturn __exports__;`);
  const out = evaluator(mod);
  if (!Array.isArray(out.SCREEN_MANIFEST)) {
    throw new Error(
      `manifest at ${manifestSrc} did not export SCREEN_MANIFEST array (got: ${typeof out.SCREEN_MANIFEST})`,
    );
  }

  // Type-mirror sanity check: if the types file in vitana-v1 differs from the
  // mirrored copy in gateway, fail loud so the developer updates both sides.
  if (existsSync(TYPES_PATH) && existsSync(typesSrc)) {
    const a = readFileSync(typesSrc, 'utf8');
    const b = readFileSync(TYPES_PATH, 'utf8');
    // Compare ignoring the leading file-level comment block.
    const stripHeader = (s: string) => s.replace(/^\/\*\*[\s\S]*?\*\/\s*/, '');
    if (stripHeader(a).trim() !== stripHeader(b).trim()) {
      throw new Error(
        'screen-manifest-types.ts has diverged between repos.\n' +
          `  vitana-v1: ${typesSrc}\n` +
          `  gateway : ${TYPES_PATH}\n` +
          'Make them identical (modulo header comment).',
      );
    }
  }

  return out.SCREEN_MANIFEST;
}

function escapeString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}

function renderEntry(e: any): string {
  // Map ScreenManifestEntry → NavCatalogEntry. The two types differ in one
  // place: manifest uses `path`, catalog uses `route`. Everything else
  // serializes 1:1.
  const fields: string[] = [];
  fields.push(`    screen_id: '${escapeString(e.screen_id)}'`);
  fields.push(`    route: '${escapeString(e.path)}'`);
  fields.push(`    category: '${escapeString(e.category)}'`);
  fields.push(`    access: '${escapeString(e.access)}'`);
  fields.push(`    anonymous_safe: ${!!e.anonymous_safe}`);
  if (e.priority != null) fields.push(`    priority: ${Number(e.priority)}`);
  if (e.entry_kind) fields.push(`    entry_kind: '${escapeString(e.entry_kind)}'`);
  if (e.overlay) {
    const o = e.overlay;
    const parts = [
      `event_name: '${escapeString(o.event_name)}'`,
      `query_marker: '${escapeString(o.query_marker)}'`,
    ];
    if (o.needs_param) parts.push(`needs_param: '${escapeString(o.needs_param)}'`);
    fields.push(`    overlay: { ${parts.join(', ')} }`);
  }
  if (Array.isArray(e.aliases) && e.aliases.length > 0) {
    fields.push(`    aliases: [${e.aliases.map((a: string) => `'${escapeString(a)}'`).join(', ')}]`);
  }
  if (Array.isArray(e.allowed_roles) && e.allowed_roles.length > 0) {
    fields.push(
      `    allowed_roles: [${e.allowed_roles.map((r: string) => `'${escapeString(r)}'`).join(', ')}]`,
    );
  }
  // i18n
  const i18nLines: string[] = ['    i18n: {'];
  for (const lang of Object.keys(e.i18n)) {
    const c = e.i18n[lang];
    i18nLines.push(`      ${lang}: {`);
    i18nLines.push(`        title: '${escapeString(c.title)}',`);
    i18nLines.push(`        description: '${escapeString(c.description)}',`);
    i18nLines.push(`        when_to_visit: '${escapeString(c.when_to_visit)}',`);
    i18nLines.push(`      },`);
  }
  i18nLines.push('    }');
  fields.push(i18nLines.join('\n'));
  return `  {\n${fields.join(',\n')},\n  },`;
}

function renderBlock(entries: unknown[]): string {
  if (entries.length === 0) {
    return [
      START_MARKER,
      HEADER_NOTICE,
      '  // (no manifest entries yet — append to vitana-v1/src/navigation/screens.manifest.ts)',
      `  ${END_MARKER}`,
    ].join('\n');
  }
  return [
    START_MARKER,
    HEADER_NOTICE,
    ...entries.map((e: any) => renderEntry(e)),
    `  ${END_MARKER}`,
  ].join('\n');
}

function readCatalog(): string {
  return readFileSync(CATALOG_PATH, 'utf8');
}

function replaceBlock(catalog: string, newBlock: string): string {
  const startIdx = catalog.indexOf(START_MARKER);
  const endIdx = catalog.indexOf(END_MARKER);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(
      `auto-managed markers not found in ${CATALOG_PATH}.\n` +
        `Expected to find ${START_MARKER} and ${END_MARKER} in the file.`,
    );
  }
  if (endIdx <= startIdx) {
    throw new Error('end-marker appears before start-marker — file structure is broken');
  }
  const before = catalog.slice(0, startIdx);
  const afterEnd = catalog.indexOf('\n', endIdx);
  const after = afterEnd === -1 ? '' : catalog.slice(afterEnd + 1);
  // Re-indent the block: the markers live inside the array literal so the
  // first line needs the standard 2-space indent.
  const indented = newBlock.replace(/^/gm, '  ').trimStart();
  return `${before}${indented}\n${after}`;
}

function checkForCollisions(entries: any[], catalogText: string) {
  // Pull all hand-curated screen_id literals from the catalog OUTSIDE the
  // auto-managed block. If a manifest entry's id collides, fail loud.
  const blockStart = catalogText.indexOf(START_MARKER);
  const blockEnd = catalogText.indexOf(END_MARKER);
  const handCurated =
    blockStart === -1 || blockEnd === -1
      ? catalogText
      : catalogText.slice(0, blockStart) + catalogText.slice(blockEnd);
  const handIds = new Set<string>();
  const re = /screen_id\s*:\s*['"]([^'"]+)['"]/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(handCurated)) !== null) handIds.add(m[1]);

  const conflicts: string[] = [];
  const manifestSeen = new Set<string>();
  for (const e of entries) {
    if (manifestSeen.has(e.screen_id)) {
      conflicts.push(`duplicate within manifest: ${e.screen_id}`);
    }
    manifestSeen.add(e.screen_id);
    if (handIds.has(e.screen_id) && !e.screen_id.startsWith('EXAMPLE.')) {
      conflicts.push(
        `manifest entry ${e.screen_id} collides with hand-curated catalog entry — pick a unique id`,
      );
    }
  }
  if (conflicts.length > 0) {
    throw new Error('catalog/manifest collisions:\n  ' + conflicts.join('\n  '));
  }
}

function main(): void {
  const opts = parseArgs();

  const v1Root = resolveVitanaV1Root();
  if (!v1Root) {
    if (opts.mode === 'check') {
      console.warn('[nav:check] vitana-v1 not reachable — skipping (set $VITANA_V1_REPO_PATH to enforce)');
      process.exit(0);
    }
    console.error('[nav:sync] cannot find vitana-v1 — set $VITANA_V1_REPO_PATH or check sibling layout');
    process.exit(1);
  }

  console.log(`[nav:${opts.mode}] vitana-v1 → ${v1Root}`);

  let entries: unknown[];
  try {
    entries = loadManifest(v1Root);
  } catch (err: any) {
    console.error(`[nav:${opts.mode}] failed to load manifest: ${err.message}`);
    process.exit(1);
  }

  // Filter out template / example entries — those are documentation, not
  // real catalog entries. Real entries never start with `EXAMPLE.`.
  const realEntries = (entries as any[]).filter(e => !e.screen_id.startsWith('EXAMPLE.'));
  console.log(`[nav:${opts.mode}] ${realEntries.length} real entries (${entries.length - realEntries.length} examples filtered)`);

  const catalog = readCatalog();
  checkForCollisions(realEntries, catalog);

  const newBlock = renderBlock(realEntries);
  const updated = replaceBlock(catalog, newBlock);

  if (opts.mode === 'check') {
    if (updated !== catalog) {
      console.error(
        '[nav:check] navigation-catalog.ts is STALE.\n' +
          '  Run `npm run nav:sync` in services/gateway and commit the result.',
      );
      // Show a short diff for the reviewer.
      try {
        execSync(`diff <(echo "${updated.replace(/"/g, '\\"')}") <(cat "${CATALOG_PATH}") | head -30`, {
          shell: '/bin/bash',
          stdio: 'inherit',
        });
      } catch {
        /* diff exit 1 is normal */
      }
      process.exit(1);
    }
    console.log('[nav:check] catalog is up to date with manifest ✓');
    return;
  }

  if (updated === catalog) {
    console.log('[nav:sync] catalog already up to date ✓');
    return;
  }

  writeFileSync(CATALOG_PATH, updated, 'utf8');
  console.log(`[nav:sync] wrote ${CATALOG_PATH} ✓`);
}

main();
