/**
 * VTID-04384 — placeholder Sage answers on answer_ready support questions are
 * replaced with a real draft for supervisor review; nothing is ever sent.
 */
import * as fs from 'fs';
import * as path from 'path';
import {
  draftPlaceholderAnswersTick,
  isPlaceholderAnswer,
  resetAnswerDraftThrottle,
  MAX_ANSWER_DRAFT_ATTEMPTS,
} from '../src/services/feedback-answer-drafter';

const S = { url: 'https://sb.test', key: 'svc' };
const SQL_PLACEHOLDER = '**Sage auto-draft (placeholder)**\n\n_Generated by auto_triage routine._\n\nUser asked: how?';
const LLM_FALLBACK = '**Sage draft (LLM unavailable, placeholder)**\n\n_Router returned no text_';

describe('isPlaceholderAnswer', () => {
  it('flags the auto-triage and LLM-fallback placeholders', () => {
    expect(isPlaceholderAnswer(SQL_PLACEHOLDER)).toBe(true);
    expect(isPlaceholderAnswer(LLM_FALLBACK)).toBe(true);
    expect(isPlaceholderAnswer(null)).toBe(true);
  });
  it('accepts a real answer', () => {
    expect(isPlaceholderAnswer('Open Settings → Data and tap Export.')).toBe(false);
  });
});

describe('draftPlaceholderAnswersTick', () => {
  let calls: Array<{ url: string; method: string; body: any }>;
  let rows: any[];
  beforeEach(() => {
    resetAnswerDraftThrottle();
    calls = [];
    rows = [{ id: 'a1', ticket_number: 'FB-9', kind: 'support_question', status: 'answer_ready',
      draft_answer_md: SQL_PLACEHOLDER, raw_transcript: 'How do I export my data?', intake_messages: null,
      structured_fields: null, classifier_meta: {}, screen_path: '/settings', app_version: '1',
      vitana_id: 'V1', priority: 'p2', supervisor_notes: null }];
    (global as any).fetch = jest.fn(async (url: string, init?: any) => {
      const method = init?.method ?? 'GET';
      calls.push({ url, method, body: init?.body ? JSON.parse(init.body) : undefined });
      const payload = method === 'GET' ? rows : [{ id: 'a1' }];
      return { ok: true, status: 200, json: async () => payload } as any;
    });
  });

  it('replaces a placeholder answer with a real Sage draft, guarded on answer_ready', async () => {
    const draft = jest.fn().mockResolvedValue({ markdown: 'Open Settings → Data and tap Export.\n', provider: 'llm' });
    const r = await draftPlaceholderAnswersTick(S, { draft, force: true });
    expect(r).toEqual({ drafted: 1, failed: 0, skipped: 0 });
    expect(calls[0].url).toContain('kind=eq.support_question');
    expect(calls[0].url).toContain('status=eq.answer_ready');
    const write = calls.filter((c) => c.method === 'PATCH').pop()!;
    expect(write.url).toContain('status=eq.answer_ready');
    expect(write.body.draft_answer_md).toBe('Open Settings → Data and tap Export.\n');
    expect(write.body.classifier_meta).toMatchObject({
      answer_drafted_by: 'sage-llm', answer_draft_attempts: 1, answer_draft_claimed_at: null,
    });
  });

  it('never changes the status or sends anything', async () => {
    const draft = jest.fn().mockResolvedValue({ markdown: 'Real answer.\n', provider: 'llm' });
    await draftPlaceholderAnswersTick(S, { draft, force: true });
    for (const c of calls.filter((x) => x.method === 'PATCH')) {
      expect(Object.keys(c.body).sort()).toEqual(expect.not.arrayContaining(['status', 'resolution_md']));
    }
    expect(calls.every((c) => c.url.includes('/rest/v1/feedback_tickets'))).toBe(true);
  });

  it('keeps the placeholder when the model falls back, and counts the attempt', async () => {
    const draft = jest.fn().mockResolvedValue({ markdown: LLM_FALLBACK, provider: 'fallback' });
    const r = await draftPlaceholderAnswersTick(S, { draft, force: true });
    expect(r.failed).toBe(1);
    expect(calls.some((c) => c.body && 'draft_answer_md' in c.body)).toBe(false);
  });

  it('stops after MAX_ANSWER_DRAFT_ATTEMPTS and skips a freshly claimed ticket', async () => {
    const draft = jest.fn();
    rows[0].classifier_meta = { answer_draft_attempts: MAX_ANSWER_DRAFT_ATTEMPTS };
    expect((await draftPlaceholderAnswersTick(S, { draft, force: true })).skipped).toBe(1);
    rows[0].classifier_meta = { answer_draft_claimed_at: new Date().toISOString() };
    expect((await draftPlaceholderAnswersTick(S, { draft, force: true })).skipped).toBe(1);
    expect(draft).not.toHaveBeenCalled();
  });

  it('is throttled and can be disabled', async () => {
    const draft = jest.fn().mockResolvedValue({ markdown: 'Real.', provider: 'llm' });
    await draftPlaceholderAnswersTick(S, { draft, now: () => 1_000_000 });
    await draftPlaceholderAnswersTick(S, { draft, now: () => 1_000_000 + 60_000 });
    expect(draft).toHaveBeenCalledTimes(1);
    resetAnswerDraftThrottle();
    await draftPlaceholderAnswersTick(S, { draft, force: true, env: { FEEDBACK_ANSWER_DRAFT_ENABLED: 'false' } as any });
    expect(draft).toHaveBeenCalledTimes(1);
  });

  it('is wired into the executor tick', () => {
    const src = fs.readFileSync(path.join(__dirname, '../src/services/dev-autopilot-execute.ts'), 'utf8');
    expect(src).toContain("await import('./feedback-answer-drafter')");
    expect(src).toContain('draftPlaceholderAnswersTick(s)');
  });
});
