apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 356ad1aa-fb9c-4fdc-bd16-9bc7fda43c14
    run.googleapis.com/build-image-uri: us-central1-docker.pkg.dev/lovable-vitana-vers1/cloud-run-source-deploy/gateway
    run.googleapis.com/build-name: projects/86804897789/locations/us-central1/builds/356ad1aa-fb9c-4fdc-bd16-9bc7fda43c14
    run.googleapis.com/build-source-location: gs://run-sources-lovable-vitana-vers1-us-central1/services/gateway/1763644921.962526-bfe24283a14f47bfa269481f969b06ce.zip#1763644923780722
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 548.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/operation-id: 42ac3df8-367c-4adb-a70c-5be121018485
    run.googleapis.com/urls: '["https://gateway-86804897789.us-central1.run.app","https://gateway-q74ibpv6ia-uc.a.run.app"]'
    serving.knative.dev/creator: d.stevanovic@exafy.io
    serving.knative.dev/lastModifier: d.stevanovic@exafy.io
  creationTimestamp: '2025-11-05T18:35:03.648804Z'
  generation: 140
  labels:
    cloud.googleapis.com/location: us-central1
  name: gateway
  namespace: '86804897789'
  resourceVersion: AAZEBtf7h/s
  selfLink: /apis/serving.knative.dev/v1/namespaces/86804897789/services/gateway
  uid: 26e62ee6-54f2-486e-b4d4-ddb5e2a2433f
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 548.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: qgfvtwezzs
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: SUPABASE_URL
          value: "https://inmkhvwdcuyhnxkgfvsb.supabase.co"
        - name: SUPABASE_SERVICE_ROLE_KEY
          value: "sb_secret_NnZa8jSuhmYhYuhgrsI8wQ_ZdVElmIY"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              key: latest
              name: gemini-api-key
        image: us-central1-docker.pkg.dev/lovable-vitana-vers1/cloud-run-source-deploy/gateway@sha256:8cd580dfdf14ef4f81aff5415f0f73e15ad7bb1f02c737459c7dfe4b4301d83d
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 86804897789-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
status:
  address:
    url: https://gateway-q74ibpv6ia-uc.a.run.app
  conditions:
  - lastTransitionTime: '2025-11-20T13:40:44.285648Z'
    message: |-
      The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.

      Logs URL: https://console.cloud.google.com/logs/viewer?project=lovable-vitana-vers1&resource=cloud_run_revision/service_name/gateway/revision_name/gateway-00136-whl&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22gateway%22%0Aresource.labels.revision_name%3D%22gateway-00136-whl%22 
      For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
    reason: HealthCheckContainerError
    status: 'False'
    type: Ready
  - lastTransitionTime: '2025-11-20T13:40:44.187412Z'
    message: |-
      The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.

      Logs URL: https://console.cloud.google.com/logs/viewer?project=lovable-vitana-vers1&resource=cloud_run_revision/service_name/gateway/revision_name/gateway-00136-whl&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22gateway%22%0Aresource.labels.revision_name%3D%22gateway-00136-whl%22 
      For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
    reason: HealthCheckContainerError
    status: 'False'
    type: ConfigurationsReady
  - lastTransitionTime: '2025-11-20T13:40:44.285648Z'
    message: |-
      The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable within the allocated timeout. This can happen when the container port is misconfigured or if the timeout is too short. The health check timeout can be extended. Logs for this revision might contain more information.

      Logs URL: https://console.cloud.google.com/logs/viewer?project=lovable-vitana-vers1&resource=cloud_run_revision/service_name/gateway/revision_name/gateway-00136-whl&advancedFilter=resource.type%3D%22cloud_run_revision%22%0Aresource.labels.service_name%3D%22gateway%22%0Aresource.labels.revision_name%3D%22gateway-00136-whl%22 
      For more troubleshooting guidance, see https://cloud.google.com/run/docs/troubleshooting#container-failed-to-start
    reason: HealthCheckContainerError
    status: 'False'
    type: RoutesReady
  latestCreatedRevisionName: gateway-00136-whl
  latestReadyRevisionName: gateway-00134-j5d
  observedGeneration: 140
  traffic:
  - latestRevision: true
    percent: 100
    revisionName: gateway-00134-j5d
  url: https://gateway-q74ibpv6ia-uc.a.run.app
