/**
 * Vitana Developer Catalog – Canonical Navigation Config
 * VTID: DEV-CICDL-0205
 *
 * AUTO-GENERATED by services/gateway/scripts/regen-screens-catalog.mjs
 * from the runtime NAVIGATION_CONFIG in app.js. Do not hand-edit — your
 * changes will be overwritten on the next regen run.
 */

export const NAVIGATION_CONFIG = [
  {
    module: "overview",
    label: "Overview",
    tabs: [
      { key: "system-overview", label: "System Overview" },
      { key: "live-metrics", label: "Live Metrics" },
      { key: "recent-events", label: "Recent Events" },
      { key: "errors-violations", label: "Errors & Violations" },
      { key: "release-feed", label: "Release Feed" }
    ]
  },
  {
    module: "admin",
    label: "Admin",
    tabs: [
      { key: "users", label: "Users" },
      { key: "permissions", label: "Permissions" },
      { key: "tenants", label: "Tenants" },
      { key: "content-moderation", label: "Content Moderation" },
      { key: "identity-access", label: "Identity Access" },
      { key: "marketplace-shops", label: "Marketplace Shops" },
      { key: "marketplace-review", label: "Marketplace Review" },
      { key: "analytics", label: "Analytics" }
    ]
  },
  {
    module: "assistant",
    label: "Assistant",
    tabs: [
      { key: "overview", label: "Overview" },
      { key: "orb-live", label: "ORB Live" },
      { key: "sessions", label: "Sessions" },
      { key: "personality", label: "Personality" },
      { key: "experiments", label: "Experiments" },
      { key: "metrics", label: "Metrics" },
      { key: "awareness-registry", label: "Awareness Registry" },
      { key: "awareness-test", label: "Awareness Test" },
      { key: "voice-tools", label: "Voice Tools" }
    ]
  },
  {
    module: "autonomy",
    label: "Autonomy",
    tabs: [
      { key: "autopilot-community", label: "Autopilot (Community)" },
      { key: "autopilot-developer", label: "Autopilot (Developer)" },
      { key: "autopilot-admin", label: "Autopilot (Admin)" },
      { key: "self-healing", label: "Self-Healing" },
      { key: "autonomy-pulse", label: "Autonomy Pulse" },
      { key: "autonomy-trace", label: "Autonomy Trace" }
    ]
  },
  {
    module: "operator",
    label: "Operator",
    tabs: [
      { key: "dashboard", label: "Dashboard" },
      { key: "task-queue", label: "Task Queue" },
      { key: "event-stream", label: "Event Stream" },
      { key: "deployments", label: "Deployments" },
      { key: "runbook", label: "Runbook" }
    ]
  },
  {
    module: "command-hub",
    label: "Operations",
    tabs: [
      { key: "tasks", label: "Tasks" },
      { key: "live-console", label: "Live Console" },
      { key: "events", label: "Events" },
      { key: "vtids", label: "VTIDs" },
      { key: "approvals", label: "Approvals" }
    ]
  },
  {
    module: "governance",
    label: "Governance",
    tabs: [
      { key: "rules", label: "Rules" },
      { key: "categories", label: "Categories" },
      { key: "evaluations", label: "Evaluations" },
      { key: "violations", label: "Violations" },
      { key: "history", label: "History" },
      { key: "proposals", label: "Proposals" },
      { key: "controls", label: "Controls" }
    ]
  },
  {
    module: "agents",
    label: "Agents",
    tabs: [
      { key: "registered-agents", label: "Registered Agents" },
      { key: "skills", label: "Skills" },
      { key: "pipelines", label: "Pipelines" },
      { key: "memory", label: "Memory" },
      { key: "telemetry", label: "Telemetry" }
    ]
  },
  {
    module: "autopilot",
    label: "Autopilot",
    tabs: [
      { key: "registry", label: "Registry" },
      { key: "scanners", label: "Scanners" },
      { key: "impact-rules", label: "Impact Rules" },
      { key: "auto-approve", label: "Auto Approve" },
      { key: "runs", label: "Runs" },
      { key: "live", label: "Live" },
      { key: "engine", label: "Engine" },
      { key: "growth", label: "Growth" }
    ]
  },
  {
    module: "oasis",
    label: "OASIS",
    tabs: [
      { key: "events", label: "Events" },
      { key: "vtid-ledger", label: "VTID Ledger" },
      { key: "entities", label: "Entities" },
      { key: "streams", label: "Streams" },
      { key: "command-log", label: "Command Log" }
    ]
  },
  {
    module: "databases",
    label: "Databases",
    tabs: [
      { key: "supabase", label: "Supabase" },
      { key: "vectors", label: "Vectors" },
      { key: "cache", label: "Cache" },
      { key: "analytics", label: "Analytics" },
      { key: "clusters", label: "Clusters" }
    ]
  },
  {
    module: "infrastructure",
    label: "Infrastructure",
    tabs: [
      { key: "services", label: "Services" },
      { key: "health", label: "Health" },
      { key: "deployments", label: "Deployments" },
      { key: "logs", label: "Logs" },
      { key: "config", label: "Config" }
    ]
  },
  {
    module: "security-dev",
    label: "Security (Dev)",
    tabs: [
      { key: "policies", label: "Policies" },
      { key: "roles", label: "Roles" },
      { key: "keys-secrets", label: "Keys & Secrets" },
      { key: "audit-log", label: "Audit Log" },
      { key: "rls-access", label: "RLS & Access" }
    ]
  },
  {
    module: "integrations-tools",
    label: "Integrations & Tools",
    tabs: [
      { key: "mcp-connectors", label: "MCP & CLI" },
      { key: "llm-providers", label: "LLM Providers" },
      { key: "apis", label: "API's" },
      { key: "tools", label: "Tools" },
      { key: "plugins", label: "Plugins & Extensions" },
      { key: "service-mesh", label: "Service Mesh" }
    ]
  },
  {
    module: "diagnostics",
    label: "Diagnostics",
    tabs: [
      { key: "health-checks", label: "Health Checks" },
      { key: "latency", label: "Latency" },
      { key: "errors", label: "Errors" },
      { key: "sse", label: "SSE" },
      { key: "debug-panel", label: "Debug Panel" },
      { key: "voice-lab", label: "Voice LAB" }
    ]
  },
  {
    module: "models-evaluations",
    label: "Models & Evaluations",
    tabs: [
      { key: "models", label: "Models" },
      { key: "evaluations", label: "Evaluations" },
      { key: "benchmarks", label: "Benchmarks" },
      { key: "routing", label: "Routing" },
      { key: "playground", label: "Playground" }
    ]
  },
  {
    module: "testing-qa",
    label: "Testing & QA",
    tabs: [
      { key: "unit-tests", label: "Unit Tests" },
      { key: "integration-tests", label: "Integration Tests" },
      { key: "validator-tests", label: "Validator Tests" },
      { key: "e2e", label: "E2E" },
      { key: "ci-reports", label: "CI Reports" }
    ]
  },
  {
    module: "intelligence-memory-dev",
    label: "Intelligence & Memory (Dev)",
    tabs: [
      { key: "memory-vault", label: "Memory Vault" },
      { key: "knowledge-graph", label: "Knowledge Graph" },
      { key: "embeddings", label: "Embeddings" },
      { key: "recall", label: "Recall" },
      { key: "inspector", label: "Inspector" }
    ]
  },
  {
    module: "docs",
    label: "Docs",
    tabs: [
      { key: "screens", label: "Screens" },
      { key: "api-inventory", label: "Api Inventory" },
      { key: "database-schemas", label: "Database Schemas" },
      { key: "architecture", label: "Architecture" },
      { key: "workforce", label: "Workforce" },
      { key: "system-knowledge", label: "System Knowledge" },
      { key: "specialists", label: "Specialists" }
    ]
  },
  {
    module: "feedback",
    label: "Feedback",
    tabs: [
      { key: "inbox", label: "Inbox" },
      { key: "handoffs", label: "Live Handoffs" },
      { key: "kpis", label: "KPIs" },
      { key: "audit", label: "Audit Log" }
    ]
  }
];
