-- Aurora schema sync, part 1: columns and tables (VTID-04755).
-- Generated 2026-10-09 from the Supabase catalog (public schema) after a full
-- column diff against vitana-aurora-prod. Run BEFORE the vector pre-load:
-- the pre-load and the FK script both reference objects created here.
-- Idempotent: safe to re-run after a partial failure.
-- One statement per line (aurora-run-sql.sh). Enum and vector columns are
-- created as text, matching how the rest of Aurora stores them; the vector
-- columns are converted back by aurora-cutover-vector-postload.sql.
-- Views are in aurora-cutover-schema-sync-views.sql (run last).
-- Sequences used by the new tables' id defaults
CREATE SEQUENCE IF NOT EXISTS public.onboarding_coach_decisions_id_seq;
CREATE SEQUENCE IF NOT EXISTS public.onboarding_touch_ledger_id_seq;
-- 79 missing columns on existing tables
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS skills text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS domains text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS roles_allowed text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS surfaces_allowed text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS llm_stage text;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS max_tier text;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS budget_per_run_usd numeric(10,4);
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS budget_per_day_usd numeric(10,4);
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS owner text;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS eval_suite text;
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS eval_pass_rate numeric(5,4);
ALTER TABLE public.agents_registry ADD COLUMN IF NOT EXISTS enabled boolean DEFAULT true NOT NULL;
ALTER TABLE public.autopilot_recommendations ADD COLUMN IF NOT EXISTS action jsonb;
ALTER TABLE public.autopilot_recommendations ADD COLUMN IF NOT EXISTS priority_score numeric;
ALTER TABLE public.autopilot_recommendations ADD COLUMN IF NOT EXISTS quality jsonb;
ALTER TABLE public.calendar_events ADD COLUMN IF NOT EXISTS rrule text;
ALTER TABLE public.calendar_events ADD COLUMN IF NOT EXISTS timezone text;
ALTER TABLE public.calendar_events ADD COLUMN IF NOT EXISTS reminder_offsets integer[];
ALTER TABLE public.calendar_events ADD COLUMN IF NOT EXISTS emoji text;
ALTER TABLE public.calendar_events ADD COLUMN IF NOT EXISTS pillar text;
ALTER TABLE public.calendar_events ADD COLUMN IF NOT EXISTS contribution_vector jsonb;
ALTER TABLE public.catalog_verticals ADD COLUMN IF NOT EXISTS discover_category text;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.contacts ADD COLUMN IF NOT EXISTS external_id text;
ALTER TABLE public.dev_agent_memory ADD COLUMN IF NOT EXISTS file_paths text[] DEFAULT '{}'::text[] NOT NULL;
ALTER TABLE public.dev_agent_memory ADD COLUMN IF NOT EXISTS stage text;
ALTER TABLE public.dev_agent_memory ADD COLUMN IF NOT EXISTS author_user_id uuid;
ALTER TABLE public.lab_reports ADD COLUMN IF NOT EXISTS partner_result_id uuid;
ALTER TABLE public.media_upload_comments ADD COLUMN IF NOT EXISTS mentions jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE public.memory_facts ADD COLUMN IF NOT EXISTS sensitivity text DEFAULT 'standard'::text NOT NULL;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS confidence_score integer DEFAULT 50 NOT NULL;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS source_classification text DEFAULT 'system'::text;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS verification_level text DEFAULT 'none'::text NOT NULL;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS sensitivity_flag text;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS third_party_source text;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS third_party_valid boolean;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS last_confidence_update timestamp with time zone DEFAULT now();
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS times_confirmed integer DEFAULT 0 NOT NULL;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS times_corrected integer DEFAULT 0 NOT NULL;
ALTER TABLE public.memory_items ADD COLUMN IF NOT EXISTS sensitivity text DEFAULT 'standard'::text NOT NULL;
ALTER TABLE public.merchants ADD COLUMN IF NOT EXISTS owner_user_id uuid;
ALTER TABLE public.merchants ADD COLUMN IF NOT EXISTS partner_tenant_id uuid;
ALTER TABLE public.merchants ADD COLUMN IF NOT EXISTS vertical_key text;
ALTER TABLE public.merchants ADD COLUMN IF NOT EXISTS onboarding_status text DEFAULT 'draft'::text NOT NULL;
ALTER TABLE public.merchants ADD COLUMN IF NOT EXISTS affiliate_advertiser_id text;
ALTER TABLE public.merchants ADD COLUMN IF NOT EXISTS partner_organization_id uuid;
ALTER TABLE public.notification_categories ADD COLUMN IF NOT EXISTS member_can_disable boolean DEFAULT true NOT NULL;
ALTER TABLE public.operator_threads ADD COLUMN IF NOT EXISTS engine text DEFAULT 'llm'::text NOT NULL;
ALTER TABLE public.partner_organizations ADD COLUMN IF NOT EXISTS partner_type text;
ALTER TABLE public.partner_organizations ADD COLUMN IF NOT EXISTS lifecycle_state text;
ALTER TABLE public.partner_organizations ADD COLUMN IF NOT EXISTS legal_name text;
ALTER TABLE public.partner_organizations ADD COLUMN IF NOT EXISTS country text;
ALTER TABLE public.partner_organizations ADD COLUMN IF NOT EXISTS vat_id text;
ALTER TABLE public.partner_organizations ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE public.partner_organizations ADD COLUMN IF NOT EXISTS trust_level smallint DEFAULT 0 NOT NULL;
ALTER TABLE public.partner_tenant ADD COLUMN IF NOT EXISTS partner_organization_id uuid;
ALTER TABLE public.partner_terms_acceptances ADD COLUMN IF NOT EXISTS terms_version_id uuid;
ALTER TABLE public.partner_terms_acceptances ADD COLUMN IF NOT EXISTS content_sha256 text;
ALTER TABLE public.partner_terms_acceptances ADD COLUMN IF NOT EXISTS shown_locale text;
ALTER TABLE public.product_clicks ADD COLUMN IF NOT EXISTS referrer_user_id uuid;
ALTER TABLE public.product_clicks ADD COLUMN IF NOT EXISTS attribution_rejected_reason text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS attributes jsonb DEFAULT '{}'::jsonb NOT NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS first_listed_at timestamp with time zone;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS listing_hold text;
ALTER TABLE public.profile_post_comments ADD COLUMN IF NOT EXISTS mentions jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE public.profile_posts ADD COLUMN IF NOT EXISTS attached_ref_type text;
ALTER TABLE public.profile_posts ADD COLUMN IF NOT EXISTS attached_ref_id uuid;
ALTER TABLE public.recommendation_commissions ADD COLUMN IF NOT EXISTS confirm_after timestamp with time zone;
ALTER TABLE public.recommendation_commissions ADD COLUMN IF NOT EXISTS confirmed_at timestamp with time zone;
ALTER TABLE public.recommendation_commissions ADD COLUMN IF NOT EXISTS reversed_at timestamp with time zone;
ALTER TABLE public.recommendation_commissions ADD COLUMN IF NOT EXISTS reversal_reason text;
ALTER TABLE public.reminders ADD COLUMN IF NOT EXISTS calendar_occurrence_start timestamp with time zone;
ALTER TABLE public.reminders ADD COLUMN IF NOT EXISTS reminder_offset_minutes integer;
ALTER TABLE public.user_intents ADD COLUMN IF NOT EXISTS embedding_v2 text;
ALTER TABLE public.user_notifications ADD COLUMN IF NOT EXISTS push_outcome text;
ALTER TABLE public.user_wallets ADD COLUMN IF NOT EXISTS earned_balance numeric(15,2) DEFAULT 0 NOT NULL;
ALTER TABLE public.vtid_ledger ADD COLUMN IF NOT EXISTS embedding_v2 text;
ALTER TABLE public.wallet_transactions ADD COLUMN IF NOT EXISTS idempotency_key text;
ALTER TABLE public.wallet_transactions ADD COLUMN IF NOT EXISTS credit_source text;
-- 8 missing tables, with constraints, indexes, RLS, policies and grants
CREATE TABLE IF NOT EXISTS public.onboarding_coach_decisions (id bigint DEFAULT nextval('onboarding_coach_decisions_id_seq'::regclass) NOT NULL, user_id uuid NOT NULL, tenant_id uuid NOT NULL, local_day date NOT NULL, mode text NOT NULL, stage text NOT NULL, action_key text, decision text NOT NULL, reason text NOT NULL, tick_id uuid NOT NULL, decided_at timestamp with time zone DEFAULT now() NOT NULL);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_decisions_pkey' AND conrelid = 'public.onboarding_coach_decisions'::regclass) THEN ALTER TABLE public.onboarding_coach_decisions ADD CONSTRAINT onboarding_coach_decisions_pkey PRIMARY KEY (id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_decisions_user_id_local_day_mode_key' AND conrelid = 'public.onboarding_coach_decisions'::regclass) THEN ALTER TABLE public.onboarding_coach_decisions ADD CONSTRAINT onboarding_coach_decisions_user_id_local_day_mode_key UNIQUE (user_id, local_day, mode); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_decisions_decision_check' AND conrelid = 'public.onboarding_coach_decisions'::regclass) THEN ALTER TABLE public.onboarding_coach_decisions ADD CONSTRAINT onboarding_coach_decisions_decision_check CHECK ((decision = ANY (ARRAY['would_touch'::text, 'skip'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_decisions_mode_check' AND conrelid = 'public.onboarding_coach_decisions'::regclass) THEN ALTER TABLE public.onboarding_coach_decisions ADD CONSTRAINT onboarding_coach_decisions_mode_check CHECK ((mode = ANY (ARRAY['shadow'::text, 'live'::text]))); END IF; END $do$;
ALTER TABLE public.onboarding_coach_decisions ENABLE ROW LEVEL SECURITY;
GRANT DELETE ON public.onboarding_coach_decisions TO service_role;
GRANT INSERT ON public.onboarding_coach_decisions TO service_role;
GRANT REFERENCES ON public.onboarding_coach_decisions TO service_role;
GRANT SELECT ON public.onboarding_coach_decisions TO service_role;
GRANT TRIGGER ON public.onboarding_coach_decisions TO service_role;
GRANT TRUNCATE ON public.onboarding_coach_decisions TO service_role;
GRANT UPDATE ON public.onboarding_coach_decisions TO service_role;
CREATE TABLE IF NOT EXISTS public.onboarding_coach_state (user_id uuid NOT NULL, tenant_id uuid NOT NULL, joined_at timestamp with time zone NOT NULL, stage text DEFAULT 'd0'::text NOT NULL, pilot_stage_override text, next_action_key text, last_touch_at timestamp with time zone, snoozed_until timestamp with time zone, ignored_streak integer DEFAULT 0 NOT NULL, opted_out_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_state_pkey' AND conrelid = 'public.onboarding_coach_state'::regclass) THEN ALTER TABLE public.onboarding_coach_state ADD CONSTRAINT onboarding_coach_state_pkey PRIMARY KEY (user_id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_state_ignored_streak_check' AND conrelid = 'public.onboarding_coach_state'::regclass) THEN ALTER TABLE public.onboarding_coach_state ADD CONSTRAINT onboarding_coach_state_ignored_streak_check CHECK ((ignored_streak >= 0)); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_state_pilot_stage_override_check' AND conrelid = 'public.onboarding_coach_state'::regclass) THEN ALTER TABLE public.onboarding_coach_state ADD CONSTRAINT onboarding_coach_state_pilot_stage_override_check CHECK (((pilot_stage_override IS NULL) OR (pilot_stage_override = ANY (ARRAY['d0'::text, 'd1'::text, 'd2_3'::text, 'd4_7'::text, 'd8_30'::text, 'd31_60'::text, 'd61_90'::text])))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_coach_state_stage_check' AND conrelid = 'public.onboarding_coach_state'::regclass) THEN ALTER TABLE public.onboarding_coach_state ADD CONSTRAINT onboarding_coach_state_stage_check CHECK ((stage = ANY (ARRAY['d0'::text, 'd1'::text, 'd2_3'::text, 'd4_7'::text, 'd8_30'::text, 'd31_60'::text, 'd61_90'::text, 'done'::text]))); END IF; END $do$;
CREATE INDEX IF NOT EXISTS idx_onboarding_coach_state_tenant ON public.onboarding_coach_state USING btree (tenant_id, stage);
ALTER TABLE public.onboarding_coach_state ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS onboarding_coach_state_read_own ON public.onboarding_coach_state;
CREATE POLICY onboarding_coach_state_read_own ON public.onboarding_coach_state AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = auth.uid()));
GRANT REFERENCES ON public.onboarding_coach_state TO anon;
GRANT SELECT ON public.onboarding_coach_state TO anon;
GRANT TRIGGER ON public.onboarding_coach_state TO anon;
GRANT TRUNCATE ON public.onboarding_coach_state TO anon;
GRANT REFERENCES ON public.onboarding_coach_state TO authenticated;
GRANT SELECT ON public.onboarding_coach_state TO authenticated;
GRANT TRIGGER ON public.onboarding_coach_state TO authenticated;
GRANT TRUNCATE ON public.onboarding_coach_state TO authenticated;
GRANT DELETE ON public.onboarding_coach_state TO service_role;
GRANT INSERT ON public.onboarding_coach_state TO service_role;
GRANT REFERENCES ON public.onboarding_coach_state TO service_role;
GRANT SELECT ON public.onboarding_coach_state TO service_role;
GRANT TRIGGER ON public.onboarding_coach_state TO service_role;
GRANT TRUNCATE ON public.onboarding_coach_state TO service_role;
GRANT UPDATE ON public.onboarding_coach_state TO service_role;
CREATE TABLE IF NOT EXISTS public.onboarding_touch_ledger (id bigint DEFAULT nextval('onboarding_touch_ledger_id_seq'::regclass) NOT NULL, user_id uuid NOT NULL, tenant_id uuid NOT NULL, local_day date NOT NULL, action_key text NOT NULL, channel text NOT NULL, status text DEFAULT 'pending'::text NOT NULL, attempts integer DEFAULT 1 NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_touch_ledger_pkey' AND conrelid = 'public.onboarding_touch_ledger'::regclass) THEN ALTER TABLE public.onboarding_touch_ledger ADD CONSTRAINT onboarding_touch_ledger_pkey PRIMARY KEY (id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_touch_ledger_user_id_local_day_key' AND conrelid = 'public.onboarding_touch_ledger'::regclass) THEN ALTER TABLE public.onboarding_touch_ledger ADD CONSTRAINT onboarding_touch_ledger_user_id_local_day_key UNIQUE (user_id, local_day); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_touch_ledger_attempts_check' AND conrelid = 'public.onboarding_touch_ledger'::regclass) THEN ALTER TABLE public.onboarding_touch_ledger ADD CONSTRAINT onboarding_touch_ledger_attempts_check CHECK (((attempts >= 1) AND (attempts <= 2))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_touch_ledger_channel_check' AND conrelid = 'public.onboarding_touch_ledger'::regclass) THEN ALTER TABLE public.onboarding_touch_ledger ADD CONSTRAINT onboarding_touch_ledger_channel_check CHECK ((channel = ANY (ARRAY['push'::text, 'inapp'::text, 'dm'::text, 'post_offer'::text, 'auto_post'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'onboarding_touch_ledger_status_check' AND conrelid = 'public.onboarding_touch_ledger'::regclass) THEN ALTER TABLE public.onboarding_touch_ledger ADD CONSTRAINT onboarding_touch_ledger_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text]))); END IF; END $do$;
ALTER TABLE public.onboarding_touch_ledger ENABLE ROW LEVEL SECURITY;
GRANT DELETE ON public.onboarding_touch_ledger TO service_role;
GRANT INSERT ON public.onboarding_touch_ledger TO service_role;
GRANT REFERENCES ON public.onboarding_touch_ledger TO service_role;
GRANT SELECT ON public.onboarding_touch_ledger TO service_role;
GRANT TRIGGER ON public.onboarding_touch_ledger TO service_role;
GRANT TRUNCATE ON public.onboarding_touch_ledger TO service_role;
GRANT UPDATE ON public.onboarding_touch_ledger TO service_role;
CREATE TABLE IF NOT EXISTS public.ops_attention_acks (id uuid DEFAULT gen_random_uuid() NOT NULL, env text NOT NULL, fingerprint text NOT NULL, action text NOT NULL, reason text NOT NULL, severity text, actor_user_id uuid, actor_email text, vtid text, created_at timestamp with time zone DEFAULT now() NOT NULL, expires_at timestamp with time zone NOT NULL);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_pkey' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_pkey PRIMARY KEY (id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_action_check' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_action_check CHECK ((action = ANY (ARRAY['ack'::text, 'snooze'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_env_check' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_env_check CHECK ((env = ANY (ARRAY['production'::text, 'staging'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_expiry_window' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_expiry_window CHECK (((expires_at > created_at) AND (expires_at <= (created_at + '24:00:00'::interval)))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_fingerprint_check' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_fingerprint_check CHECK (((length(fingerprint) >= 3) AND (length(fingerprint) <= 300))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_p1_never_snoozed' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_p1_never_snoozed CHECK ((NOT ((action = 'snooze'::text) AND (severity = 'P1'::text)))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_reason_check' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_reason_check CHECK (((length(btrim(reason)) >= 3) AND (length(btrim(reason)) <= 500))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_severity_check' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_severity_check CHECK ((severity = ANY (ARRAY['P1'::text, 'P2'::text, 'P3'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ops_attention_acks_vtid_check' AND conrelid = 'public.ops_attention_acks'::regclass) THEN ALTER TABLE public.ops_attention_acks ADD CONSTRAINT ops_attention_acks_vtid_check CHECK (((vtid IS NULL) OR (vtid ~ '^VTID-[0-9]{4,5}$'::text))); END IF; END $do$;
CREATE INDEX IF NOT EXISTS ops_attention_acks_active_idx ON public.ops_attention_acks USING btree (env, expires_at DESC);
CREATE INDEX IF NOT EXISTS ops_attention_acks_fingerprint_idx ON public.ops_attention_acks USING btree (env, fingerprint, created_at DESC);
ALTER TABLE public.ops_attention_acks ENABLE ROW LEVEL SECURITY;
GRANT DELETE ON public.ops_attention_acks TO service_role;
GRANT INSERT ON public.ops_attention_acks TO service_role;
GRANT REFERENCES ON public.ops_attention_acks TO service_role;
GRANT SELECT ON public.ops_attention_acks TO service_role;
GRANT TRIGGER ON public.ops_attention_acks TO service_role;
GRANT TRUNCATE ON public.ops_attention_acks TO service_role;
GRANT UPDATE ON public.ops_attention_acks TO service_role;
CREATE TABLE IF NOT EXISTS public.partner_terms_versions (id uuid DEFAULT gen_random_uuid() NOT NULL, version text NOT NULL, status text DEFAULT 'draft'::text NOT NULL, requires_reacceptance boolean DEFAULT true NOT NULL, binding_locale text DEFAULT 'de'::text NOT NULL, content jsonb NOT NULL, content_sha256 text, baseline_version_id uuid, created_by uuid, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL, published_by uuid, published_at timestamp with time zone);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'partner_terms_versions_pkey' AND conrelid = 'public.partner_terms_versions'::regclass) THEN ALTER TABLE public.partner_terms_versions ADD CONSTRAINT partner_terms_versions_pkey PRIMARY KEY (id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'partner_terms_versions_version_key' AND conrelid = 'public.partner_terms_versions'::regclass) THEN ALTER TABLE public.partner_terms_versions ADD CONSTRAINT partner_terms_versions_version_key UNIQUE (version); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'partner_terms_versions_binding_locale_check' AND conrelid = 'public.partner_terms_versions'::regclass) THEN ALTER TABLE public.partner_terms_versions ADD CONSTRAINT partner_terms_versions_binding_locale_check CHECK ((binding_locale = 'de'::text)); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'partner_terms_versions_binding_text' AND conrelid = 'public.partner_terms_versions'::regclass) THEN ALTER TABLE public.partner_terms_versions ADD CONSTRAINT partner_terms_versions_binding_text CHECK (((jsonb_typeof((content -> 'de'::text)) = 'object'::text) AND (length(btrim(COALESCE(((content -> 'de'::text) ->> 'title'::text), ''::text))) > 0) AND (length(btrim(COALESCE(((content -> 'de'::text) ->> 'body_md'::text), ''::text))) > 0))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'partner_terms_versions_published_fields' AND conrelid = 'public.partner_terms_versions'::regclass) THEN ALTER TABLE public.partner_terms_versions ADD CONSTRAINT partner_terms_versions_published_fields CHECK (((status = 'draft'::text) OR ((content_sha256 IS NOT NULL) AND (published_at IS NOT NULL) AND (baseline_version_id IS NOT NULL)))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'partner_terms_versions_status_check' AND conrelid = 'public.partner_terms_versions'::regclass) THEN ALTER TABLE public.partner_terms_versions ADD CONSTRAINT partner_terms_versions_status_check CHECK ((status = ANY (ARRAY['draft'::text, 'published'::text, 'superseded'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'partner_terms_versions_version_check' AND conrelid = 'public.partner_terms_versions'::regclass) THEN ALTER TABLE public.partner_terms_versions ADD CONSTRAINT partner_terms_versions_version_check CHECK (((length(btrim(version)) >= 1) AND (length(btrim(version)) <= 40))); END IF; END $do$;
CREATE UNIQUE INDEX IF NOT EXISTS partner_terms_versions_one_published ON public.partner_terms_versions USING btree ((true)) WHERE (status = 'published'::text);
ALTER TABLE public.partner_terms_versions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS partner_terms_versions_select ON public.partner_terms_versions;
CREATE POLICY partner_terms_versions_select ON public.partner_terms_versions AS PERMISSIVE FOR SELECT TO authenticated USING ((status = ANY (ARRAY['published'::text, 'superseded'::text])));
GRANT REFERENCES ON public.partner_terms_versions TO anon;
GRANT SELECT ON public.partner_terms_versions TO anon;
GRANT TRIGGER ON public.partner_terms_versions TO anon;
GRANT REFERENCES ON public.partner_terms_versions TO authenticated;
GRANT SELECT ON public.partner_terms_versions TO authenticated;
GRANT TRIGGER ON public.partner_terms_versions TO authenticated;
GRANT DELETE ON public.partner_terms_versions TO service_role;
GRANT INSERT ON public.partner_terms_versions TO service_role;
GRANT REFERENCES ON public.partner_terms_versions TO service_role;
GRANT SELECT ON public.partner_terms_versions TO service_role;
GRANT TRIGGER ON public.partner_terms_versions TO service_role;
GRANT TRUNCATE ON public.partner_terms_versions TO service_role;
GRANT UPDATE ON public.partner_terms_versions TO service_role;
CREATE TABLE IF NOT EXISTS public.reward_orders (id uuid DEFAULT gen_random_uuid() NOT NULL, tenant_id uuid NOT NULL, user_id uuid NOT NULL, item_id uuid NOT NULL, vtna_amount integer NOT NULL, fulfilment text NOT NULL, status text NOT NULL, country character(2), shipping_address jsonb, shipping_fee_cents integer, shipping_currency text, stripe_session_id text, stripe_payment_intent text, age_confirmed_at timestamp with time zone, reservation_held boolean DEFAULT false NOT NULL, reservation_expires_at timestamp with time zone, paid_at timestamp with time zone, status_reason text, idempotency_key text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_pkey' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_pkey PRIMARY KEY (id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_stripe_session_id_key' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_stripe_session_id_key UNIQUE (stripe_session_id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_user_id_idempotency_key_key' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_user_id_idempotency_key_key UNIQUE (user_id, idempotency_key); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_fulfilment_check' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_fulfilment_check CHECK ((fulfilment = ANY (ARRAY['ship'::text, 'event'::text, 'digital'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_idempotency_key_check' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_idempotency_key_check CHECK (((length(idempotency_key) >= 8) AND (length(idempotency_key) <= 200))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_shipping_currency_check' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_shipping_currency_check CHECK (((shipping_currency IS NULL) OR (shipping_currency = ANY (ARRAY['EUR'::text, 'USD'::text])))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_shipping_fee_cents_check' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_shipping_fee_cents_check CHECK (((shipping_fee_cents IS NULL) OR (shipping_fee_cents >= 0))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_status_check' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_status_check CHECK ((status = ANY (ARRAY['awaiting_shipping_payment'::text, 'paid'::text, 'fulfilling'::text, 'shipped'::text, 'delivered'::text, 'cancelled'::text, 'refunded'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_orders_vtna_amount_check' AND conrelid = 'public.reward_orders'::regclass) THEN ALTER TABLE public.reward_orders ADD CONSTRAINT reward_orders_vtna_amount_check CHECK ((vtna_amount > 0)); END IF; END $do$;
CREATE INDEX IF NOT EXISTS reward_orders_user_idx ON public.reward_orders USING btree (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS reward_orders_awaiting_idx ON public.reward_orders USING btree (reservation_expires_at) WHERE (status = 'awaiting_shipping_payment'::text);
CREATE INDEX IF NOT EXISTS reward_orders_status_idx ON public.reward_orders USING btree (status, created_at DESC);
ALTER TABLE public.reward_orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS reward_orders_read_own ON public.reward_orders;
CREATE POLICY reward_orders_read_own ON public.reward_orders AS PERMISSIVE FOR SELECT TO authenticated USING ((user_id = auth.uid()));
GRANT SELECT ON public.reward_orders TO authenticated;
GRANT DELETE ON public.reward_orders TO service_role;
GRANT INSERT ON public.reward_orders TO service_role;
GRANT REFERENCES ON public.reward_orders TO service_role;
GRANT SELECT ON public.reward_orders TO service_role;
GRANT TRIGGER ON public.reward_orders TO service_role;
GRANT TRUNCATE ON public.reward_orders TO service_role;
GRANT UPDATE ON public.reward_orders TO service_role;
CREATE TABLE IF NOT EXISTS public.reward_shipping_fees (country character(2) NOT NULL, currency text NOT NULL, fee_cents integer NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shipping_fees_pkey' AND conrelid = 'public.reward_shipping_fees'::regclass) THEN ALTER TABLE public.reward_shipping_fees ADD CONSTRAINT reward_shipping_fees_pkey PRIMARY KEY (country, currency); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shipping_fees_country_check' AND conrelid = 'public.reward_shipping_fees'::regclass) THEN ALTER TABLE public.reward_shipping_fees ADD CONSTRAINT reward_shipping_fees_country_check CHECK ((country ~ '^[A-Z]{2}$'::text)); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shipping_fees_currency_check' AND conrelid = 'public.reward_shipping_fees'::regclass) THEN ALTER TABLE public.reward_shipping_fees ADD CONSTRAINT reward_shipping_fees_currency_check CHECK ((currency = ANY (ARRAY['EUR'::text, 'USD'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shipping_fees_fee_cents_check' AND conrelid = 'public.reward_shipping_fees'::regclass) THEN ALTER TABLE public.reward_shipping_fees ADD CONSTRAINT reward_shipping_fees_fee_cents_check CHECK ((fee_cents >= 0)); END IF; END $do$;
ALTER TABLE public.reward_shipping_fees ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS reward_shipping_fees_read ON public.reward_shipping_fees;
CREATE POLICY reward_shipping_fees_read ON public.reward_shipping_fees AS PERMISSIVE FOR SELECT TO authenticated USING (true);
GRANT SELECT ON public.reward_shipping_fees TO authenticated;
GRANT DELETE ON public.reward_shipping_fees TO service_role;
GRANT INSERT ON public.reward_shipping_fees TO service_role;
GRANT REFERENCES ON public.reward_shipping_fees TO service_role;
GRANT SELECT ON public.reward_shipping_fees TO service_role;
GRANT TRIGGER ON public.reward_shipping_fees TO service_role;
GRANT TRUNCATE ON public.reward_shipping_fees TO service_role;
GRANT UPDATE ON public.reward_shipping_fees TO service_role;
CREATE TABLE IF NOT EXISTS public.reward_shop_items (id uuid DEFAULT gen_random_uuid() NOT NULL, slug text NOT NULL, titles jsonb NOT NULL, descriptions jsonb DEFAULT '{}'::jsonb NOT NULL, images text[] DEFAULT '{}'::text[] NOT NULL, vtna_price integer NOT NULL, fulfilment text NOT NULL, age_restricted boolean DEFAULT false NOT NULL, min_age smallint, ships_to_countries character(2)[] DEFAULT '{}'::bpchar[] NOT NULL, stock integer, reserved integer DEFAULT 0 NOT NULL, is_active boolean DEFAULT false NOT NULL, sort_order integer DEFAULT 100 NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now() NOT NULL);
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_pkey' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_pkey PRIMARY KEY (id); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_slug_key' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_slug_key UNIQUE (slug); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_check CHECK (((NOT age_restricted) OR (min_age IS NOT NULL))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_check1' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_check1 CHECK (((fulfilment <> 'ship'::text) OR (cardinality(ships_to_countries) > 0) OR (NOT is_active))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_check2' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_check2 CHECK (((stock IS NULL) OR (reserved <= stock))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_descriptions_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_descriptions_check CHECK ((jsonb_typeof(descriptions) = 'object'::text)); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_fulfilment_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_fulfilment_check CHECK ((fulfilment = ANY (ARRAY['ship'::text, 'event'::text, 'digital'::text]))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_min_age_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_min_age_check CHECK (((min_age IS NULL) OR ((min_age >= 1) AND (min_age <= 99)))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_reserved_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_reserved_check CHECK ((reserved >= 0)); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_slug_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_slug_check CHECK ((slug ~ '^[a-z0-9][a-z0-9-]{1,79}$'::text)); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_stock_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_stock_check CHECK (((stock IS NULL) OR (stock >= 0))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_titles_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_titles_check CHECK (((jsonb_typeof(titles) = 'object'::text) AND (titles ? 'de'::text))); END IF; END $do$;
DO $do$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_shop_items_vtna_price_check' AND conrelid = 'public.reward_shop_items'::regclass) THEN ALTER TABLE public.reward_shop_items ADD CONSTRAINT reward_shop_items_vtna_price_check CHECK ((vtna_price > 0)); END IF; END $do$;
ALTER TABLE public.reward_shop_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS reward_shop_items_read_active ON public.reward_shop_items;
CREATE POLICY reward_shop_items_read_active ON public.reward_shop_items AS PERMISSIVE FOR SELECT TO authenticated USING (is_active);
GRANT SELECT ON public.reward_shop_items TO authenticated;
GRANT DELETE ON public.reward_shop_items TO service_role;
GRANT INSERT ON public.reward_shop_items TO service_role;
GRANT REFERENCES ON public.reward_shop_items TO service_role;
GRANT SELECT ON public.reward_shop_items TO service_role;
GRANT TRIGGER ON public.reward_shop_items TO service_role;
GRANT TRUNCATE ON public.reward_shop_items TO service_role;
GRANT UPDATE ON public.reward_shop_items TO service_role;
ALTER SEQUENCE public.onboarding_coach_decisions_id_seq OWNED BY public.onboarding_coach_decisions.id;
ALTER SEQUENCE public.onboarding_touch_ledger_id_seq OWNED BY public.onboarding_touch_ledger.id;
GRANT USAGE, SELECT ON SEQUENCE public.onboarding_coach_decisions_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.onboarding_touch_ledger_id_seq TO service_role;
