-- Aurora cutover: recreate Supabase's public->public foreign keys on Aurora (VTID-04755)
--
-- Generated read-only from Supabase (inmkhvwdcuyhnxkgfvsb) pg_constraint on 2026-10-05.
-- Aurora has ZERO foreign keys in public (DMS full loads don't copy them), so
-- PostgREST on Aurora reports "0 Relationships" and every embedded select
-- (e.g. select=*,profiles(*)) would fail after the cutover.
--
-- RUN ONLY AFTER the final full load (runbook Step 5): TRUNCATE_BEFORE_LOAD
-- fails on tables referenced by a foreign key, so these must not exist while
-- DMS loads. NOT VALID = enforced for new writes and visible to PostgREST,
-- without scanning existing rows. public->auth FKs (127) are deliberately
-- NOT included: auth.users is not in Aurora.
--
-- Regenerate right before the window if Supabase's schema changed since.
BEGIN;
ALTER TABLE access_audit_log ADD CONSTRAINT access_audit_log_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE account_health_snapshot ADD CONSTRAINT account_health_snapshot_provider_account_id_fkey FOREIGN KEY (provider_account_id) REFERENCES provider_account(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE action_ledger ADD CONSTRAINT action_ledger_action_id_fkey FOREIGN KEY (action_id) REFERENCES pending_connector_actions(id) NOT VALID;
ALTER TABLE agent_audit_log ADD CONSTRAINT agent_audit_log_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE agent_kb_bindings ADD CONSTRAINT agent_kb_bindings_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_kb_bindings_tenant ADD CONSTRAINT agent_kb_bindings_tenant_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_persona_versions ADD CONSTRAINT agent_persona_versions_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_personas_tenant_overrides ADD CONSTRAINT agent_personas_tenant_overrides_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_routing_keywords_tenant ADD CONSTRAINT agent_routing_keywords_tenant_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_run_signals ADD CONSTRAINT agent_run_signals_run_id_fkey FOREIGN KEY (run_id) REFERENCES agent_runs(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_run_steps ADD CONSTRAINT agent_run_steps_run_id_fkey FOREIGN KEY (run_id) REFERENCES agent_runs(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_runs ADD CONSTRAINT agent_runs_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES agent_runs(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE agent_third_party_connections ADD CONSTRAINT agent_third_party_connections_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_tool_bindings ADD CONSTRAINT agent_tool_bindings_persona_id_fkey FOREIGN KEY (persona_id) REFERENCES agent_personas(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_tool_bindings ADD CONSTRAINT agent_tool_bindings_tool_key_fkey FOREIGN KEY (tool_key) REFERENCES agent_tools(key) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_voice_config_changes ADD CONSTRAINT agent_voice_config_changes_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents_registry(agent_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_voice_configs ADD CONSTRAINT agent_voice_configs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES agents_registry(agent_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE agent_voice_configs ADD CONSTRAINT agent_voice_configs_llm_provider_fkey FOREIGN KEY (llm_provider) REFERENCES voice_providers(id) NOT VALID;
ALTER TABLE agent_voice_configs ADD CONSTRAINT agent_voice_configs_stt_provider_fkey FOREIGN KEY (stt_provider) REFERENCES voice_providers(id) NOT VALID;
ALTER TABLE agent_voice_configs ADD CONSTRAINT agent_voice_configs_tts_provider_fkey FOREIGN KEY (tts_provider) REFERENCES voice_providers(id) NOT VALID;
ALTER TABLE ai_assistant_credentials ADD CONSTRAINT ai_assistant_credentials_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES user_connections(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE ai_conversations ADD CONSTRAINT ai_conversations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE ai_memory ADD CONSTRAINT ai_memory_source_conversation_id_fkey FOREIGN KEY (source_conversation_id) REFERENCES ai_conversations(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE ai_messages ADD CONSTRAINT ai_messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES ai_conversations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE ai_recommendations ADD CONSTRAINT ai_recommendations_deployed_rule_id_fkey FOREIGN KEY (deployed_rule_id) REFERENCES automation_rules(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE ai_recommendations ADD CONSTRAINT ai_recommendations_situation_id_fkey FOREIGN KEY (situation_id) REFERENCES ai_situation_analyses(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE ai_recommendations ADD CONSTRAINT ai_recommendations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE ai_situation_analyses ADD CONSTRAINT ai_situation_analyses_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE api_performance_metrics ADD CONSTRAINT api_performance_metrics_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES api_integrations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE api_test_logs ADD CONSTRAINT api_test_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES api_integrations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE api_test_notifications ADD CONSTRAINT api_test_notifications_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES api_integrations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE app_users ADD CONSTRAINT app_users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE app_users ADD CONSTRAINT fk_app_users_live_room FOREIGN KEY (live_room_id) REFERENCES live_rooms(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE assistant_promises ADD CONSTRAINT assistant_promises_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES user_open_threads(thread_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE audit_events ADD CONSTRAINT audit_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) NOT VALID;
ALTER TABLE automation_executions ADD CONSTRAINT automation_executions_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES automation_rules(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE automation_executions ADD CONSTRAINT automation_executions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE autopilot_actions ADD CONSTRAINT autopilot_actions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE autopilot_feedback ADD CONSTRAINT autopilot_feedback_action_id_fkey FOREIGN KEY (action_id) REFERENCES autopilot_actions(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE autopilot_prompt_prefs ADD CONSTRAINT autopilot_prompt_prefs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE autopilot_prompt_prefs ADD CONSTRAINT autopilot_prompt_prefs_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE autopilot_prompts ADD CONSTRAINT autopilot_prompts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE autopilot_prompts ADD CONSTRAINT autopilot_prompts_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE biomarker_results ADD CONSTRAINT biomarker_results_lab_report_id_fkey FOREIGN KEY (lab_report_id) REFERENCES lab_reports(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE business_packages ADD CONSTRAINT business_packages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) NOT VALID;
ALTER TABLE calendar_google_links ADD CONSTRAINT calendar_google_links_calendar_event_id_fkey FOREIGN KEY (calendar_event_id) REFERENCES calendar_events(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE calendar_push_links ADD CONSTRAINT calendar_push_links_calendar_event_id_fkey FOREIGN KEY (calendar_event_id) REFERENCES calendar_events(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE campaign_posts ADD CONSTRAINT campaign_posts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE campaign_posts ADD CONSTRAINT campaign_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES distribution_posts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE capability_awareness_events ADD CONSTRAINT capability_awareness_events_capability_key_fkey FOREIGN KEY (capability_key) REFERENCES system_capabilities(capability_key) NOT VALID;
ALTER TABLE catalog_vertical_fields ADD CONSTRAINT catalog_vertical_fields_vertical_key_fkey FOREIGN KEY (vertical_key) REFERENCES catalog_verticals(key) ON DELETE CASCADE NOT VALID;
ALTER TABLE catalog_verticals ADD CONSTRAINT catalog_verticals_discover_category_fkey FOREIGN KEY (discover_category) REFERENCES discover_categories(key) ON UPDATE CASCADE NOT VALID;
ALTER TABLE chat_group_members ADD CONSTRAINT chat_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES chat_groups(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE chat_message_replies ADD CONSTRAINT chat_message_replies_message_id_fkey FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE chat_message_replies ADD CONSTRAINT chat_message_replies_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES chat_messages(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_group_id_fkey FOREIGN KEY (group_id) REFERENCES chat_groups(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE cj_orders ADD CONSTRAINT cj_orders_checkout_session_id_fkey FOREIGN KEY (checkout_session_id) REFERENCES checkout_sessions(id) NOT VALID;
ALTER TABLE commission_event ADD CONSTRAINT commission_event_affiliate_program_id_fkey FOREIGN KEY (affiliate_program_id) REFERENCES affiliate_program(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listing_categories ADD CONSTRAINT community_listing_categories_parent_key_fkey FOREIGN KEY (parent_key) REFERENCES community_listing_categories(key) ON DELETE SET NULL NOT VALID;
ALTER TABLE community_listing_reports ADD CONSTRAINT community_listing_reports_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES community_listings(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listing_reports ADD CONSTRAINT community_listing_reports_reporter_user_id_fkey FOREIGN KEY (reporter_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listing_reports ADD CONSTRAINT community_listing_reports_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listing_seller_blocks ADD CONSTRAINT community_listing_seller_blocks_blocked_seller_id_fkey FOREIGN KEY (blocked_seller_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listing_seller_blocks ADD CONSTRAINT community_listing_seller_blocks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listing_seller_blocks ADD CONSTRAINT community_listing_seller_blocks_viewer_user_id_fkey FOREIGN KEY (viewer_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listings ADD CONSTRAINT community_listings_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE community_listings ADD CONSTRAINT community_listings_seller_user_id_fkey FOREIGN KEY (seller_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_listings ADD CONSTRAINT community_listings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_marketplace_seller_suspensions ADD CONSTRAINT community_marketplace_seller_suspensions_seller_user_id_fkey FOREIGN KEY (seller_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_marketplace_seller_suspensions ADD CONSTRAINT community_marketplace_seller_suspensions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_meetups ADD CONSTRAINT community_meetups_group_id_fkey FOREIGN KEY (group_id) REFERENCES community_groups(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE community_memberships ADD CONSTRAINT community_memberships_group_id_fkey FOREIGN KEY (group_id) REFERENCES community_groups(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE connector_certification ADD CONSTRAINT connector_certification_version_id_fkey FOREIGN KEY (version_id) REFERENCES integration_version(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE consent_receipt ADD CONSTRAINT consent_receipt_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES consent_grant(id) ON UPDATE CASCADE ON DELETE RESTRICT NOT VALID;
ALTER TABLE consents ADD CONSTRAINT consents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE contradiction_flags ADD CONSTRAINT contradiction_flags_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE curated_memories ADD CONSTRAINT curated_memories_consent_id_fkey FOREIGN KEY (consent_id) REFERENCES consents(consent_id) NOT VALID;
ALTER TABLE curated_memories ADD CONSTRAINT curated_memories_source_event_id_fkey FOREIGN KEY (source_event_id) REFERENCES memory_events(event_id) NOT VALID;
ALTER TABLE curated_memories ADD CONSTRAINT curated_memories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE dev_agent_memory ADD CONSTRAINT dev_agent_memory_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES dev_agent_memory(id) NOT VALID;
ALTER TABLE dev_autopilot_executions ADD CONSTRAINT dev_autopilot_executions_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE dev_autopilot_executions ADD CONSTRAINT dev_autopilot_executions_parent_execution_id_fkey FOREIGN KEY (parent_execution_id) REFERENCES dev_autopilot_executions(id) NOT VALID;
ALTER TABLE dev_autopilot_outcomes ADD CONSTRAINT dev_autopilot_outcomes_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE dev_autopilot_plan_versions ADD CONSTRAINT dev_autopilot_plan_versions_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE dev_autopilot_signals ADD CONSTRAINT dev_autopilot_signals_run_id_fkey FOREIGN KEY (run_id) REFERENCES dev_autopilot_runs(run_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE disclosure ADD CONSTRAINT disclosure_cart_order_id_fkey FOREIGN KEY (cart_order_id) REFERENCES cart_order(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;
ALTER TABLE discover_subcategories ADD CONSTRAINT discover_subcategories_category_key_fkey FOREIGN KEY (category_key) REFERENCES discover_categories(key) ON UPDATE CASCADE NOT VALID;
ALTER TABLE distribution_posts ADD CONSTRAINT distribution_posts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE entity_relationships ADD CONSTRAINT entity_relationships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE erp_approvals ADD CONSTRAINT erp_approvals_command_id_fkey FOREIGN KEY (command_id) REFERENCES erp_commands(id) NOT VALID;
ALTER TABLE event_co_creators ADD CONSTRAINT event_co_creators_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE event_game_participants ADD CONSTRAINT event_game_participants_event_game_id_fkey FOREIGN KEY (event_game_id) REFERENCES event_games(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE event_game_points ADD CONSTRAINT event_game_points_event_game_id_fkey FOREIGN KEY (event_game_id) REFERENCES event_games(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE event_game_points ADD CONSTRAINT event_game_points_reversal_of_id_fkey FOREIGN KEY (reversal_of_id) REFERENCES event_game_points(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE event_game_points ADD CONSTRAINT event_game_points_source_post_id_fkey FOREIGN KEY (source_post_id) REFERENCES profile_posts(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE event_recommendations ADD CONSTRAINT event_recommendations_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE event_ticket_purchases ADD CONSTRAINT event_ticket_purchases_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE event_ticket_purchases ADD CONSTRAINT event_ticket_purchases_ticket_type_id_fkey FOREIGN KEY (ticket_type_id) REFERENCES event_ticket_types(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE event_ticket_scans ADD CONSTRAINT event_ticket_scans_ticket_purchase_id_fkey FOREIGN KEY (ticket_purchase_id) REFERENCES event_ticket_purchases(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE event_ticket_types ADD CONSTRAINT event_ticket_types_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE feature_entitlements ADD CONSTRAINT feature_entitlements_plan_key_fkey FOREIGN KEY (plan_key) REFERENCES subscription_plans(plan_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE feedback_handoff_events ADD CONSTRAINT feedback_handoff_events_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES feedback_tickets(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE feedback_tickets ADD CONSTRAINT feedback_tickets_duplicate_of_fkey FOREIGN KEY (duplicate_of) REFERENCES feedback_tickets(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE feedback_tickets ADD CONSTRAINT feedback_tickets_linked_finding_id_fkey FOREIGN KEY (linked_finding_id) REFERENCES autopilot_recommendations(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE global_community_group_members ADD CONSTRAINT global_community_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE global_community_groups ADD CONSTRAINT global_community_groups_chat_thread_id_fkey FOREIGN KEY (chat_thread_id) REFERENCES global_message_threads(id) NOT VALID;
ALTER TABLE global_event_participants ADD CONSTRAINT fk_global_event_participants_event FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE global_group_members ADD CONSTRAINT fk_global_group_members_group FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE global_messages ADD CONSTRAINT fk_global_messages_thread FOREIGN KEY (thread_id) REFERENCES global_message_threads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE global_thread_participants ADD CONSTRAINT fk_global_thread_participants_thread FOREIGN KEY (thread_id) REFERENCES global_message_threads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE global_typing_indicators ADD CONSTRAINT global_typing_indicators_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES global_message_threads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE goal_plan_i18n ADD CONSTRAINT goal_plan_i18n_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES goal_plans(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE goal_plan_step_i18n ADD CONSTRAINT goal_plan_step_i18n_step_id_fkey FOREIGN KEY (step_id) REFERENCES goal_plan_steps(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE goal_plan_steps ADD CONSTRAINT goal_plan_steps_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES goal_plans(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE governance_enforcements ADD CONSTRAINT governance_enforcements_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES governance_rules(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE governance_evaluations ADD CONSTRAINT governance_evaluations_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES governance_rules(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE governance_rules ADD CONSTRAINT governance_rules_category_id_fkey FOREIGN KEY (category_id) REFERENCES governance_categories(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE governance_violations ADD CONSTRAINT governance_violations_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES governance_rules(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE group_post_comments ADD CONSTRAINT group_post_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES group_posts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE group_post_likes ADD CONSTRAINT group_post_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES group_posts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE group_posts ADD CONSTRAINT group_posts_group_id_fkey FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE group_recommendations ADD CONSTRAINT group_recommendations_group_id_fkey FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE health_data_attestation ADD CONSTRAINT health_data_attestation_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES consent_grant(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE index_delta_observations ADD CONSTRAINT index_delta_observations_recommendation_id_fkey FOREIGN KEY (recommendation_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE insurance_quote ADD CONSTRAINT insurance_quote_grant_id_fkey FOREIGN KEY (grant_id) REFERENCES consent_grant(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE integration_manifest ADD CONSTRAINT integration_manifest_partner_tenant_id_fkey FOREIGN KEY (partner_tenant_id) REFERENCES partner_tenant(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE integration_version ADD CONSTRAINT integration_version_manifest_id_fkey FOREIGN KEY (manifest_id) REFERENCES integration_manifest(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_categories ADD CONSTRAINT intent_categories_kind_key_fkey FOREIGN KEY (kind_key) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_compass_boost ADD CONSTRAINT intent_compass_boost_intent_kind_fkey FOREIGN KEY (intent_kind) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_compatibility ADD CONSTRAINT intent_compatibility_kind_a_fkey FOREIGN KEY (kind_a) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_compatibility ADD CONSTRAINT intent_compatibility_kind_b_fkey FOREIGN KEY (kind_b) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_disputes ADD CONSTRAINT intent_disputes_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_events ADD CONSTRAINT intent_events_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_events ADD CONSTRAINT intent_events_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_match_recommendations ADD CONSTRAINT intent_match_recommendations_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_matches ADD CONSTRAINT intent_matches_intent_a_id_fkey FOREIGN KEY (intent_a_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_matches ADD CONSTRAINT intent_matches_intent_b_id_fkey FOREIGN KEY (intent_b_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE intent_supply_seeded ADD CONSTRAINT intent_supply_seeded_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE job_artifact ADD CONSTRAINT job_artifact_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES job_attempt(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE job_attempt ADD CONSTRAINT job_attempt_step_id_fkey FOREIGN KEY (step_id) REFERENCES job_step(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE job_step ADD CONSTRAINT job_step_job_id_fkey FOREIGN KEY (job_id) REFERENCES provisioning_job(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE journey_checklist_translations ADD CONSTRAINT journey_checklist_translations_locale_fkey FOREIGN KEY (locale) REFERENCES supported_locales(code) ON UPDATE CASCADE NOT VALID;
ALTER TABLE lab_reports ADD CONSTRAINT lab_reports_partner_result_id_fkey FOREIGN KEY (partner_result_id) REFERENCES partner_health_results(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE lab_test_orders ADD CONSTRAINT lab_test_orders_lab_test_id_fkey FOREIGN KEY (lab_test_id) REFERENCES lab_tests(id) NOT VALID;
ALTER TABLE lab_test_results ADD CONSTRAINT lab_test_results_order_id_fkey FOREIGN KEY (order_id) REFERENCES lab_test_orders(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE life_compass_subgoals ADD CONSTRAINT life_compass_subgoals_compass_id_fkey FOREIGN KEY (compass_id) REFERENCES life_compass(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE lifecycle_notification_state ADD CONSTRAINT lifecycle_notification_state_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES user_subscriptions(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE listing_status_history ADD CONSTRAINT listing_status_history_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES community_listings(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE live_highlights ADD CONSTRAINT live_highlights_live_room_id_fkey FOREIGN KEY (live_room_id) REFERENCES live_rooms(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE live_room_access_grants ADD CONSTRAINT fk_grants_session FOREIGN KEY (session_id) REFERENCES live_room_sessions(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE live_room_access_grants ADD CONSTRAINT live_room_access_grants_room_id_fkey FOREIGN KEY (room_id) REFERENCES live_rooms(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE live_room_access_grants ADD CONSTRAINT live_room_access_grants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE live_room_access_grants ADD CONSTRAINT live_room_access_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE live_room_attendance ADD CONSTRAINT fk_attendance_session FOREIGN KEY (session_id) REFERENCES live_room_sessions(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE live_room_attendance ADD CONSTRAINT live_room_attendance_live_room_id_fkey FOREIGN KEY (live_room_id) REFERENCES live_rooms(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE live_room_sessions ADD CONSTRAINT live_room_sessions_room_id_fkey FOREIGN KEY (room_id) REFERENCES live_rooms(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE live_rooms ADD CONSTRAINT fk_live_rooms_current_session FOREIGN KEY (current_session_id) REFERENCES live_room_sessions(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE live_stream_subscribers ADD CONSTRAINT live_stream_subscribers_stream_id_fkey FOREIGN KEY (stream_id) REFERENCES community_live_streams(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE livekit_test_results ADD CONSTRAINT livekit_test_results_case_id_fkey FOREIGN KEY (case_id) REFERENCES livekit_test_cases(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE livekit_test_results ADD CONSTRAINT livekit_test_results_run_id_fkey FOREIGN KEY (run_id) REFERENCES livekit_test_runs(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE llm_allowed_models ADD CONSTRAINT llm_allowed_models_provider_key_fkey FOREIGN KEY (provider_key) REFERENCES llm_allowed_providers(provider_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE llm_routing_policy_audit ADD CONSTRAINT llm_routing_policy_audit_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES llm_routing_policy(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE location_visits ADD CONSTRAINT location_visits_location_id_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE mapping_decision ADD CONSTRAINT mapping_decision_mapping_id_fkey FOREIGN KEY (mapping_id) REFERENCES schema_mapping(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE match_notifications ADD CONSTRAINT match_notifications_match_id_fkey FOREIGN KEY (match_id) REFERENCES user_matches(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE mcp_tool_executions ADD CONSTRAINT mcp_tool_executions_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES api_integrations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_analytics ADD CONSTRAINT media_analytics_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_upload_comment_likes ADD CONSTRAINT media_upload_comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES media_upload_comments(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_upload_comments ADD CONSTRAINT media_upload_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES media_upload_comments(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_upload_comments ADD CONSTRAINT media_upload_comments_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES media_uploads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_upload_likes ADD CONSTRAINT media_upload_likes_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES media_uploads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_video_comment_likes ADD CONSTRAINT media_video_comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES media_video_comments(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_video_comments ADD CONSTRAINT media_video_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES media_video_comments(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE media_video_comments ADD CONSTRAINT media_video_comments_video_id_fkey FOREIGN KEY (video_id) REFERENCES media_videos(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE mem_episodes ADD CONSTRAINT mem_episodes_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES mem_episodes(id) NOT VALID;
ALTER TABLE mem_facts ADD CONSTRAINT mem_facts_source_episode_id_fkey FOREIGN KEY (source_episode_id) REFERENCES mem_episodes(id) NOT VALID;
ALTER TABLE mem_facts ADD CONSTRAINT mem_facts_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES mem_facts(id) NOT VALID;
ALTER TABLE mem_graph_edges ADD CONSTRAINT mem_graph_edges_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES mem_graph_edges(id) NOT VALID;
ALTER TABLE memberships ADD CONSTRAINT memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE memory_category_mapping ADD CONSTRAINT memory_category_mapping_garden_category_fkey FOREIGN KEY (garden_category) REFERENCES memory_garden_config(category_key) NOT VALID;
ALTER TABLE memory_confidence_history ADD CONSTRAINT memory_confidence_history_memory_item_id_fkey FOREIGN KEY (memory_item_id) REFERENCES memory_items(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE memory_confidence_history ADD CONSTRAINT memory_confidence_history_reason_code_fkey FOREIGN KEY (reason_code) REFERENCES memory_confidence_reasons(reason_code) NOT VALID;
ALTER TABLE memory_embeddings ADD CONSTRAINT memory_embeddings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE memory_events ADD CONSTRAINT memory_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE memory_facts ADD CONSTRAINT memory_facts_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES memory_facts(id) NOT VALID;
ALTER TABLE memory_items ADD CONSTRAINT memory_items_category_key_fkey FOREIGN KEY (category_key) REFERENCES memory_categories(key) NOT VALID;
ALTER TABLE memory_items ADD CONSTRAINT memory_items_source_classification_fkey FOREIGN KEY (source_classification) REFERENCES memory_source_trust(source_type) NOT VALID;
ALTER TABLE memory_node_sources ADD CONSTRAINT memory_node_sources_diary_entry_id_fkey FOREIGN KEY (diary_entry_id) REFERENCES memory_diary_entries(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE memory_node_sources ADD CONSTRAINT memory_node_sources_node_id_fkey FOREIGN KEY (node_id) REFERENCES memory_garden_nodes(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE merchant_route ADD CONSTRAINT merchant_route_cart_order_id_fkey FOREIGN KEY (cart_order_id) REFERENCES cart_order(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE merchants ADD CONSTRAINT merchants_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES partner_organizations(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE merchants ADD CONSTRAINT merchants_vertical_key_fkey FOREIGN KEY (vertical_key) REFERENCES catalog_verticals(key) NOT VALID;
ALTER TABLE message_actions ADD CONSTRAINT message_actions_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE message_queue ADD CONSTRAINT message_queue_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE message_queue ADD CONSTRAINT message_queue_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES campaign_recipients(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE messages ADD CONSTRAINT messages_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES messages(id) NOT VALID;
ALTER TABLE messages ADD CONSTRAINT messages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE messages ADD CONSTRAINT messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads(id) NOT VALID;
ALTER TABLE monetization_cooldowns ADD CONSTRAINT monetization_cooldowns_triggered_by_attempt_id_fkey FOREIGN KEY (triggered_by_attempt_id) REFERENCES monetization_attempts(id) NOT VALID;
ALTER TABLE music_metadata ADD CONSTRAINT music_metadata_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE oasis_spec_approvals ADD CONSTRAINT oasis_spec_approvals_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES oasis_specs(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE oasis_spec_validations ADD CONSTRAINT oasis_spec_validations_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES oasis_specs(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE onboarding_invitations ADD CONSTRAINT onboarding_invitations_signup_attempt_id_fkey FOREIGN KEY (signup_attempt_id) REFERENCES signup_attempts(id) NOT VALID;
ALTER TABLE onboarding_invitations ADD CONSTRAINT onboarding_invitations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) NOT VALID;
ALTER TABLE operator_messages ADD CONSTRAINT operator_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES operator_threads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE orb_session_state ADD CONSTRAINT orb_session_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_package_item_id_fkey FOREIGN KEY (package_item_id) REFERENCES package_items(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES package_purchases(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) NOT VALID;
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_ticket_purchase_id_fkey FOREIGN KEY (ticket_purchase_id) REFERENCES event_ticket_purchases(id) NOT VALID;
ALTER TABLE package_items ADD CONSTRAINT package_items_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE package_items ADD CONSTRAINT package_items_package_id_fkey FOREIGN KEY (package_id) REFERENCES business_packages(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE package_items ADD CONSTRAINT package_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) NOT VALID;
ALTER TABLE package_purchases ADD CONSTRAINT package_purchases_package_id_fkey FOREIGN KEY (package_id) REFERENCES business_packages(id) NOT VALID;
ALTER TABLE package_purchases ADD CONSTRAINT package_purchases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) NOT VALID;
ALTER TABLE partner_capability ADD CONSTRAINT partner_capability_manifest_id_fkey FOREIGN KEY (manifest_id) REFERENCES integration_manifest(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_customer_links ADD CONSTRAINT partner_customer_links_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES partner_registry(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_health_result_inbox ADD CONSTRAINT partner_health_result_inbox_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES partner_registry(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_health_result_inbox ADD CONSTRAINT partner_health_result_inbox_resolved_order_id_fkey FOREIGN KEY (resolved_order_id) REFERENCES partner_health_test_orders(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE partner_health_results ADD CONSTRAINT partner_health_results_order_id_fkey FOREIGN KEY (order_id) REFERENCES partner_health_test_orders(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_health_results ADD CONSTRAINT partner_health_results_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES partner_registry(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_health_test_orders ADD CONSTRAINT partner_health_test_orders_partner_customer_link_id_fkey FOREIGN KEY (partner_customer_link_id) REFERENCES partner_customer_links(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE partner_health_test_orders ADD CONSTRAINT partner_health_test_orders_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES partner_registry(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_health_test_orders ADD CONSTRAINT partner_health_test_orders_product_order_id_fkey FOREIGN KEY (product_order_id) REFERENCES product_orders(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE partner_health_test_status_history ADD CONSTRAINT partner_health_test_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES partner_health_test_orders(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_oauth_credential ADD CONSTRAINT partner_oauth_credential_manifest_fkey FOREIGN KEY (manifest_id) REFERENCES integration_manifest(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_onboarding_steps ADD CONSTRAINT partner_onboarding_steps_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES partner_organizations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_organization_invites ADD CONSTRAINT partner_organization_invites_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES partner_organizations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_organization_members ADD CONSTRAINT partner_organization_members_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES partner_organizations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE partner_registry ADD CONSTRAINT partner_registry_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES partner_organizations(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE partner_tenant ADD CONSTRAINT partner_tenant_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES partner_organizations(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE partner_terms_acceptances ADD CONSTRAINT partner_terms_acceptances_partner_organization_id_fkey FOREIGN KEY (partner_organization_id) REFERENCES partner_organizations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE patient_provider_assignments ADD CONSTRAINT patient_provider_assignments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE pattern_discoveries ADD CONSTRAINT pattern_discoveries_implemented_rule_id_fkey FOREIGN KEY (implemented_rule_id) REFERENCES automation_rules(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE pattern_discoveries ADD CONSTRAINT pattern_discoveries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE plan_adherence_logs ADD CONSTRAINT plan_adherence_logs_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES user_health_plans(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE podcast_favorites ADD CONSTRAINT podcast_favorites_podcast_id_fkey FOREIGN KEY (podcast_id) REFERENCES media_uploads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE podcast_metadata ADD CONSTRAINT podcast_metadata_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE post_analytics ADD CONSTRAINT post_analytics_post_id_fkey FOREIGN KEY (post_id) REFERENCES distribution_posts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE product_clicks ADD CONSTRAINT product_clicks_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_clicks ADD CONSTRAINT product_clicks_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_orders ADD CONSTRAINT product_orders_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_orders ADD CONSTRAINT product_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_orders ADD CONSTRAINT product_orders_source_creator_id_fkey FOREIGN KEY (source_creator_id) REFERENCES app_users(user_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_orders ADD CONSTRAINT product_orders_source_video_id_fkey FOREIGN KEY (source_video_id) REFERENCES shop_videos(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_outcomes ADD CONSTRAINT product_outcomes_order_id_fkey FOREIGN KEY (order_id) REFERENCES product_orders(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_outcomes ADD CONSTRAINT product_outcomes_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE product_recommendations ADD CONSTRAINT product_recommendations_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE product_recommendations ADD CONSTRAINT product_recommendations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE product_recommendations ADD CONSTRAINT product_recommendations_sharing_link_id_fkey FOREIGN KEY (sharing_link_id) REFERENCES sharing_links(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE products ADD CONSTRAINT products_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE profile_post_comment_likes ADD CONSTRAINT profile_post_comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES profile_post_comments(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE profile_post_comments ADD CONSTRAINT profile_post_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES profile_post_comments(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE profile_posts ADD CONSTRAINT profile_posts_event_game_id_fkey FOREIGN KEY (event_game_id) REFERENCES event_games(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE profiles ADD CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE provider_account ADD CONSTRAINT provider_account_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES provider(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE provisioning_job ADD CONSTRAINT provisioning_job_provider_account_id_fkey FOREIGN KEY (provider_account_id) REFERENCES provider_account(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE recommendation_commissions ADD CONSTRAINT recommendation_commissions_product_order_id_fkey FOREIGN KEY (product_order_id) REFERENCES product_orders(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE recommendation_commissions ADD CONSTRAINT recommendation_commissions_product_recommendation_id_fkey FOREIGN KEY (product_recommendation_id) REFERENCES product_recommendations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE recommendation_deployments ADD CONSTRAINT recommendation_deployments_recommendation_id_fkey FOREIGN KEY (recommendation_id) REFERENCES ai_recommendations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE recommendation_deployments ADD CONSTRAINT recommendation_deployments_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES automation_rules(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE redemption_codes ADD CONSTRAINT redemption_codes_grants_plan_fkey FOREIGN KEY (grants_plan) REFERENCES subscription_plans(plan_key) NOT VALID;
ALTER TABLE redemption_redemptions ADD CONSTRAINT redemption_redemptions_code_fkey FOREIGN KEY (code) REFERENCES redemption_codes(code) NOT VALID;
ALTER TABLE relationship_dates ADD CONSTRAINT relationship_dates_relationship_node_id_fkey FOREIGN KEY (relationship_node_id) REFERENCES relationship_nodes(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE relationship_health_context ADD CONSTRAINT relationship_health_context_relationship_node_id_fkey FOREIGN KEY (relationship_node_id) REFERENCES relationship_nodes(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE relationship_health_context ADD CONSTRAINT relationship_health_context_source_episode_id_fkey FOREIGN KEY (source_episode_id) REFERENCES mem_episodes(id) NOT VALID;
ALTER TABLE relationship_health_context ADD CONSTRAINT relationship_health_context_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES relationship_health_context(id) NOT VALID;
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) NOT VALID;
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES reseller_payouts(id) NOT VALID;
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_reseller_id_fkey FOREIGN KEY (reseller_id) REFERENCES reseller_profiles(id) NOT VALID;
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_ticket_purchase_id_fkey FOREIGN KEY (ticket_purchase_id) REFERENCES event_ticket_purchases(id) NOT VALID;
ALTER TABLE reseller_payouts ADD CONSTRAINT reseller_payouts_reseller_profile_id_fkey FOREIGN KEY (reseller_profile_id) REFERENCES reseller_profiles(id) NOT VALID;
ALTER TABLE reseller_payouts ADD CONSTRAINT reseller_payouts_wallet_transaction_id_fkey FOREIGN KEY (wallet_transaction_id) REFERENCES wallet_transactions(id) NOT VALID;
ALTER TABLE reseller_profiles ADD CONSTRAINT reseller_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE retrieval_traces ADD CONSTRAINT retrieval_traces_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE rewards_ledger ADD CONSTRAINT rewards_ledger_commission_event_id_fkey FOREIGN KEY (commission_event_id) REFERENCES commission_event(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID;
ALTER TABLE risk_mitigations ADD CONSTRAINT risk_mitigations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE role_preferences ADD CONSTRAINT role_preferences_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE role_sessions ADD CONSTRAINT role_sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE routine_runs ADD CONSTRAINT routine_runs_routine_name_fkey FOREIGN KEY (routine_name) REFERENCES routines(name) ON DELETE CASCADE NOT VALID;
ALTER TABLE scheduled_posts ADD CONSTRAINT scheduled_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES distribution_posts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE schema_mapping ADD CONSTRAINT schema_mapping_version_id_fkey FOREIGN KEY (version_id) REFERENCES integration_version(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE schema_source ADD CONSTRAINT schema_source_version_id_fkey FOREIGN KEY (version_id) REFERENCES integration_version(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE service_payments ADD CONSTRAINT service_payments_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE shop_saved_products ADD CONSTRAINT shop_saved_products_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) NOT VALID;
ALTER TABLE shop_saved_products ADD CONSTRAINT shop_saved_products_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE shop_saved_products ADD CONSTRAINT shop_saved_products_video_id_fkey FOREIGN KEY (video_id) REFERENCES shop_videos(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE shop_video_anchors ADD CONSTRAINT shop_video_anchors_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) NOT VALID;
ALTER TABLE shop_video_anchors ADD CONSTRAINT shop_video_anchors_video_id_fkey FOREIGN KEY (video_id) REFERENCES shop_videos(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE shop_video_events ADD CONSTRAINT shop_video_events_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE shop_video_events ADD CONSTRAINT shop_video_events_video_id_fkey FOREIGN KEY (video_id) REFERENCES shop_videos(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE shop_videos ADD CONSTRAINT shop_videos_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES app_users(user_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE signup_attempts ADD CONSTRAINT signup_attempts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) NOT VALID;
ALTER TABLE stream_recordings ADD CONSTRAINT stream_recordings_stream_id_fkey FOREIGN KEY (stream_id) REFERENCES community_live_streams(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE subscription_plan_prices ADD CONSTRAINT subscription_plan_prices_plan_key_fkey FOREIGN KEY (plan_key) REFERENCES subscription_plans(plan_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE tenant_autopilot_bindings ADD CONSTRAINT tenant_autopilot_bindings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE tenant_autopilot_bindings ADD CONSTRAINT tenant_autopilot_bindings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES app_users(user_id) NOT VALID;
ALTER TABLE tenant_autopilot_runs ADD CONSTRAINT tenant_autopilot_runs_binding_id_fkey FOREIGN KEY (binding_id) REFERENCES tenant_autopilot_bindings(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE tenant_autopilot_runs ADD CONSTRAINT tenant_autopilot_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE tenant_autopilot_runs ADD CONSTRAINT tenant_autopilot_runs_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES app_users(user_id) NOT VALID;
ALTER TABLE tenant_autopilot_settings ADD CONSTRAINT tenant_autopilot_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE tenant_autopilot_settings ADD CONSTRAINT tenant_autopilot_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES app_users(user_id) NOT VALID;
ALTER TABLE test_contract_runs ADD CONSTRAINT test_contract_runs_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES test_contracts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE test_cycles ADD CONSTRAINT fk_test_cycles_last_run FOREIGN KEY (last_run_id) REFERENCES test_runs(id) NOT VALID;
ALTER TABLE test_results ADD CONSTRAINT test_results_run_id_fkey FOREIGN KEY (run_id) REFERENCES test_runs(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE test_runs ADD CONSTRAINT test_runs_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES test_cycles(id) NOT VALID;
ALTER TABLE thread_participants ADD CONSTRAINT fk_thread_participants_thread_id FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE thread_participants ADD CONSTRAINT thread_participants_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE training_cycle_days ADD CONSTRAINT training_cycle_days_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES training_cycles(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE typing_indicators ADD CONSTRAINT typing_indicators_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE typing_indicators ADD CONSTRAINT typing_indicators_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE universal_cart_events ADD CONSTRAINT universal_cart_events_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES universal_carts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES universal_carts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) NOT VALID;
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) NOT VALID;
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_source_creator_id_fkey FOREIGN KEY (source_creator_id) REFERENCES app_users(user_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_source_video_id_fkey FOREIGN KEY (source_video_id) REFERENCES shop_videos(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE universal_carts ADD CONSTRAINT universal_carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE user_capability_awareness ADD CONSTRAINT user_capability_awareness_capability_key_fkey FOREIGN KEY (capability_key) REFERENCES system_capabilities(capability_key) ON DELETE CASCADE NOT VALID;
ALTER TABLE user_category_preferences ADD CONSTRAINT user_category_preferences_category_id_fkey FOREIGN KEY (category_id) REFERENCES notification_categories(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE user_connections ADD CONSTRAINT user_connections_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES connector_registry(id) NOT VALID;
ALTER TABLE user_device_session_log ADD CONSTRAINT user_device_session_log_device_token_id_fkey FOREIGN KEY (device_token_id) REFERENCES user_device_tokens(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE user_explicit_preferences ADD CONSTRAINT user_explicit_preferences_category_fkey FOREIGN KEY (category) REFERENCES preference_categories(key) NOT VALID;
ALTER TABLE user_feedback_reports ADD CONSTRAINT user_feedback_reports_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE user_intents ADD CONSTRAINT user_intents_intent_kind_fkey FOREIGN KEY (intent_kind) REFERENCES intent_kinds(kind_key) NOT VALID;
ALTER TABLE user_limitations ADD CONSTRAINT user_limitations_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE user_location_history ADD CONSTRAINT user_location_history_named_place_id_fkey FOREIGN KEY (named_place_id) REFERENCES user_location_settings(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE user_permitted_roles ADD CONSTRAINT user_permitted_roles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE user_preference_inferences ADD CONSTRAINT user_preference_inferences_category_fkey FOREIGN KEY (category) REFERENCES preference_categories(key) NOT VALID;
ALTER TABLE user_ratings ADD CONSTRAINT user_ratings_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE SET NULL NOT VALID;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT NOT VALID;
ALTER TABLE user_subscriptions ADD CONSTRAINT user_subscriptions_plan_key_fkey FOREIGN KEY (plan_key) REFERENCES subscription_plans(plan_key) NOT VALID;
ALTER TABLE user_subscriptions ADD CONSTRAINT user_subscriptions_price_key_fkey FOREIGN KEY (price_key) REFERENCES subscription_plan_prices(price_key) NOT VALID;
ALTER TABLE user_tenants ADD CONSTRAINT user_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE user_tenants ADD CONSTRAINT user_tenants_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE vaea_detected_questions ADD CONSTRAINT vaea_detected_questions_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES vaea_listener_channels(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE vaea_reply_drafts ADD CONSTRAINT vaea_reply_drafts_catalog_item_id_fkey FOREIGN KEY (catalog_item_id) REFERENCES vaea_referral_catalog(id) ON DELETE SET NULL NOT VALID;
ALTER TABLE vaea_reply_drafts ADD CONSTRAINT vaea_reply_drafts_detected_question_id_fkey FOREIGN KEY (detected_question_id) REFERENCES vaea_detected_questions(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE video_metadata ADD CONSTRAINT video_metadata_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE voucher_orders ADD CONSTRAINT voucher_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE voucher_orders ADD CONSTRAINT voucher_orders_voucher_id_fkey FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE voucher_redemptions ADD CONSTRAINT voucher_redemptions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE voucher_redemptions ADD CONSTRAINT voucher_redemptions_voucher_id_fkey FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE vouchers ADD CONSTRAINT vouchers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE wallet_credits ADD CONSTRAINT wallet_credits_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE wallet_deposits ADD CONSTRAINT wallet_deposits_account_id_fkey FOREIGN KEY (account_id) REFERENCES wallet_accounts(id) NOT VALID;
ALTER TABLE wallet_ledger_entries ADD CONSTRAINT wallet_ledger_entries_account_id_fkey FOREIGN KEY (account_id) REFERENCES wallet_accounts(id) NOT VALID;
ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES profiles(user_id) NOT VALID NOT VALID;
ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES profiles(user_id) NOT VALID NOT VALID;
ALTER TABLE wearable_daily_metrics ADD CONSTRAINT wearable_daily_metrics_user_connection_id_fkey FOREIGN KEY (user_connection_id) REFERENCES user_connections(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE wearable_waitlist ADD CONSTRAINT wearable_waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE NOT VALID;
ALTER TABLE wearable_workouts ADD CONSTRAINT wearable_workouts_user_connection_id_fkey FOREIGN KEY (user_connection_id) REFERENCES user_connections(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE workflow_step ADD CONSTRAINT workflow_step_run_id_fkey FOREIGN KEY (run_id) REFERENCES workflow_run(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
ALTER TABLE workflow_version ADD CONSTRAINT workflow_version_definition_id_fkey FOREIGN KEY (definition_id) REFERENCES workflow_definition(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;
COMMIT;
NOTIFY pgrst, 'reload schema';
