/**
 * Journey Conversation V2 — structured speech intents (Phase 5).
 *
 * Replaces fixed motivational/onboarding paragraphs with stable INTENTS
 * whose wording is always generated by the LLM. An intent carries the
 * purpose, required/optional elements, anti-repetition memory and
 * frequency constraints — never a sanctioned paragraph.
 *
 * Locale: system instructions stay English by platform rule (CLAUDE.md
 * §13b); the user's language is enforced by the existing language
 * directive injected by the brain/context-pack. Every rendered intent
 * block RESTATES that rule so generated speech cannot drift to English
 * for non-English users.
 *
 * Frequency: the deep inspiration/responsibility messages are capped at
 * once per day via the presence pacer surface
 * 'vitana_responsibility_message' (checked by the caller — the arbiter),
 * and same-day return sessions always get the short greeting intent.
 *
 * Spec: docs/SPEC-journey-conversation-v2.md §8–10.
 */

import type { UserAwareness } from './types';

export type SpeechIntentType =
  | 'daily_inspiration'
  | 'short_return_greeting'
  | 'responsibility_reflection';

export interface SpeechIntent {
  type: SpeechIntentType;
  /** Semantic elements the generated speech MUST weave in. */
  must_include: string[];
  /** Elements the LLM MAY include when natural. */
  may_include: string[];
  /** Recent opening lines that must NOT be structurally repeated. */
  avoid_repeating: string[];
  style: string;
  forbidden_patterns: string[];
  max_per_day: number;
}

export const RESPONSIBILITY_SURFACE = 'vitana_responsibility_message' as const;
export const RESPONSIBILITY_NUDGE_KEY = 'daily_responsibility_reflection' as const;

/**
 * Pick the greeting intent for this session. Multiple sessions in the same
 * day → short contextual return greeting, never a second deep inspiration.
 */
export function buildGreetingSpeechIntent(awareness: UserAwareness): SpeechIntent {
  const isReturnSameDay = (awareness.sessions_today?.count ?? 0) > 0;
  const recentOpenings = awareness.journey_v2?.recent_greeting_openings ?? [];

  if (isReturnSameDay) {
    return {
      type: 'short_return_greeting',
      must_include: ['brief_acknowledgement_of_return'],
      may_include: ['personal_name', 'reference_to_earlier_session_today'],
      avoid_repeating: recentOpenings,
      style: 'short, warm, contextual — one sentence, then content',
      forbidden_patterns: [
        'repeating the full daily inspiration',
        're-introducing Vitana or the platform',
      ],
      max_per_day: Infinity,
    };
  }

  return {
    type: 'daily_inspiration',
    must_include: ['personal_name', 'health_journey', 'support'],
    may_include: ['quality_of_life', 'new_path', 'understand_yourself'],
    avoid_repeating: recentOpenings,
    style: 'warm, intelligent, inspirational, non-repetitive',
    forbidden_patterns: [
      'identical sentence structure to any recent opening',
      'repeated stock phrases ("My role is... My role is...")',
    ],
    max_per_day: 1,
  };
}

/**
 * Occasional "why Vitana exists" reflection — surfaced only when the
 * arbiter selects the inspiration slot AND the pacer permits the
 * once-per-day responsibility surface.
 */
export function buildResponsibilitySpeechIntent(awareness: UserAwareness): SpeechIntent {
  return {
    type: 'responsibility_reflection',
    must_include: ['one_aspect_of_vitanas_responsibility'],
    may_include: [
      'guide',
      'support',
      'remind',
      'motivate',
      'help_self_understanding',
      'improve_health_and_quality_of_life',
      'make_the_app_easier',
    ],
    avoid_repeating: awareness.journey_v2?.recent_greeting_openings ?? [],
    style: 'brief, sincere, varied — pick ONE responsibility aspect, never the full list',
    forbidden_patterns: [
      'reciting every responsibility in one speech',
      'repeating the aspect used in a recent session',
    ],
    max_per_day: 1,
  };
}

/**
 * Render an intent as prompt constraints. The output is an instruction
 * block — it contains NO user-facing sentences to copy, by design.
 */
export function renderSpeechIntentBlock(intent: SpeechIntent): string {
  const lines: string[] = [
    `=== SPEECH INTENT: ${intent.type} ===`,
    'Generate this speech freshly — there is NO sanctioned wording to copy.',
    "LANGUAGE: generate it in the user's language per the language directive in this prompt. NEVER fall back to English for a non-English user.",
    `Style: ${intent.style}`,
    `Must weave in: ${intent.must_include.join(', ')}`,
  ];
  if (intent.may_include.length > 0) {
    lines.push(`May include (only when natural): ${intent.may_include.join(', ')}`);
  }
  if (intent.forbidden_patterns.length > 0) {
    lines.push(`Forbidden: ${intent.forbidden_patterns.map((p) => `(${p})`).join('; ')}`);
  }
  if (intent.avoid_repeating.length > 0) {
    lines.push(
      'Recent openings you must NOT structurally repeat (vary structure, imagery and rhythm):',
      ...intent.avoid_repeating.slice(0, 5).map((o) => `  - "${truncate(o, 140)}"`),
    );
  }
  if (intent.max_per_day === 1) {
    lines.push(
      'This is a once-per-day message. If it has already been delivered today (see session history above), use a short return greeting instead.',
    );
  }
  return lines.join('\n');
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1).trimEnd() + '…';
}
