/**
 * VTID-02783: Mirror of vitana-v1/src/navigation/screen-manifest-types.ts.
 *
 * Both repos consume the same `ScreenManifestEntry` shape. CI verifies the
 * two files are byte-identical (modulo header comment) so they cannot
 * silently drift. If you change one, run `npm run nav:check` in vitana-
 * platform — it will tell you to re-run the sync after the type change.
 *
 * DO NOT edit this file by hand. Source of truth lives in vitana-v1.
 * Update there first, then run:
 *   $ cd services/gateway && npm run nav:sync
 * which copies the file in (and regenerates the catalog block).
 */

export type LangCode = 'en' | 'de' | string;

export interface ScreenManifestI18n {
  title: string;
  description: string;
  /** Free-text guidance the Navigator uses to score "when to visit" matches. */
  when_to_visit: string;
}

export type ScreenCategory =
  | 'public'
  | 'auth'
  | 'home'
  | 'community'
  | 'business'
  | 'wallet'
  | 'health'
  | 'discover'
  | 'memory'
  | 'ai'
  | 'autopilot'
  | 'inbox'
  | 'settings'
  | 'sharing';

/** Overlay metadata. Only used when entry_kind='overlay'. */
export interface ScreenOverlayMeta {
  /** CustomEvent dispatched when the overlay should open. */
  event_name: string;
  /** ?open=<marker> URL signal. */
  query_marker: string;
  /** Optional named param the overlay needs (e.g. 'user_id', 'meetup_id'). */
  needs_param?: string;
}

export interface ScreenManifestEntry {
  /** Canonical id, dotted-uppercase (e.g. 'COMM.OPEN_ASKS'). Must be unique. */
  screen_id: string;
  /** React Router path. May contain `:param` placeholders. */
  path: string;
  category: ScreenCategory;
  access: 'public' | 'authenticated';
  /** Whether unauthenticated users can navigate here. */
  anonymous_safe: boolean;
  /**
   * Alternative slug-style identifiers Gemini, LiveKit, or legacy email/
   * marketing links may emit (e.g. 'find-partner', 'community/events').
   */
  aliases?: string[];
  /** Sort priority for the Navigator (higher = preferred when ambiguous). */
  priority?: number;
  /** Roles that can see this entry. Defaults inferred by surface. */
  allowed_roles?: string[];
  /** 'route' (default) navigates; 'overlay' opens a popup via CustomEvent. */
  entry_kind?: 'route' | 'overlay';
  overlay?: ScreenOverlayMeta;
  /** Localized content. EN required; DE strongly recommended. */
  i18n: Record<LangCode, ScreenManifestI18n>;
}
