-- Repoint Aurora's FK constraints from auth.users(id) to app_users(user_id)
-- (VTID-03702, the identity-anchor step recommended by the 2026-08-05
-- "Aurora except Auth" feasibility assessment, docs/AURORA-EXCEPT-AUTH-ASSESSMENT.md).
--
-- WHY: Aurora will never run Supabase's GoTrue auth service, so auth.users
-- being present (DMS does replicate it as plain table data -- confirmed
-- 190 rows on Aurora vs 205 on Supabase, 2026-08-23) is not a substitute for
-- a real identity anchor Aurora-side code can depend on. app_users is
-- already the canonical mirror CLAUDE.md names, and as of 2026-08-23 it is
-- back in exact 1:1 sync with auth.users on Supabase (205=205; see the
-- companion fix that closed a 7-row drift dating to Feb/Mar 2026 signups).
--
-- Generated directly from Supabase production via pg_get_constraintdef() --
-- not hand-written -- covering all 116 single-column FKs into auth.users(id)
-- across 105 tables (117 total, minus app_users_user_id_fkey itself, which
-- stays pointed at auth.users since app_users IS the anchor). Every
-- ON DELETE action (CASCADE/SET NULL/RESTRICT/none) is preserved exactly.
--
-- SAFE TO RUN NOW, BEST RUN AFTER A FRESH FULL RELOAD: each statement is an
-- idempotent DO block that (a) skips if the constraint already exists
-- (duplicate_object) and (b) catches foreign_key_violation and logs a
-- NOTICE instead of aborting, because Aurora's app_users/other tables are a
-- stale replica (DMS CDC has been down since 2026-08-20 -- see
-- cloudshell-fix-dms-source-dns.sh). A row whose user_id isn't in Aurora's
-- app_users yet just gets skipped and can be retried later by re-running
-- this exact file -- nothing here is destructive or one-shot.
--
-- Run via the same pattern as cloudshell-restore-aurora-schema.sh (RDS Data
-- API, master secret, from CloudShell -- this session's IAM identity is
-- explicitly denied secretsmanager:GetSecretValue on that secret).
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.access_audit_log DROP CONSTRAINT IF EXISTS access_audit_log_actor_user_id_fkey; ALTER TABLE public.access_audit_log ADD CONSTRAINT access_audit_log_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: access_audit_log_actor_user_id_fkey on access_audit_log'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.account_deletion_requests DROP CONSTRAINT IF EXISTS account_deletion_requests_user_id_fkey; ALTER TABLE public.account_deletion_requests ADD CONSTRAINT account_deletion_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: account_deletion_requests_user_id_fkey on account_deletion_requests'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.admin_proactive_settings DROP CONSTRAINT IF EXISTS admin_proactive_settings_updated_by_fkey; ALTER TABLE public.admin_proactive_settings ADD CONSTRAINT admin_proactive_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: admin_proactive_settings_updated_by_fkey on admin_proactive_settings'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.ai_conversations DROP CONSTRAINT IF EXISTS ai_conversations_user_id_fkey; ALTER TABLE public.ai_conversations ADD CONSTRAINT ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: ai_conversations_user_id_fkey on ai_conversations'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.ai_memory DROP CONSTRAINT IF EXISTS ai_memory_user_id_fkey; ALTER TABLE public.ai_memory ADD CONSTRAINT ai_memory_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: ai_memory_user_id_fkey on ai_memory'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.analytics_celebrate_events DROP CONSTRAINT IF EXISTS analytics_celebrate_events_user_id_fkey; ALTER TABLE public.analytics_celebrate_events ADD CONSTRAINT analytics_celebrate_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: analytics_celebrate_events_user_id_fkey on analytics_celebrate_events'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.api_integrations DROP CONSTRAINT IF EXISTS api_integrations_created_by_fkey; ALTER TABLE public.api_integrations ADD CONSTRAINT api_integrations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(user_id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: api_integrations_created_by_fkey on api_integrations'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.api_test_logs DROP CONSTRAINT IF EXISTS api_test_logs_triggered_by_fkey; ALTER TABLE public.api_test_logs ADD CONSTRAINT api_test_logs_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES public.app_users(user_id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: api_test_logs_triggered_by_fkey on api_test_logs'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.automation_rules DROP CONSTRAINT IF EXISTS automation_rules_created_by_fkey; ALTER TABLE public.automation_rules ADD CONSTRAINT automation_rules_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: automation_rules_created_by_fkey on automation_rules'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.automation_rules DROP CONSTRAINT IF EXISTS automation_rules_user_id_fkey; ALTER TABLE public.automation_rules ADD CONSTRAINT automation_rules_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: automation_rules_user_id_fkey on automation_rules'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.autopilot_actions DROP CONSTRAINT IF EXISTS autopilot_actions_user_id_fkey; ALTER TABLE public.autopilot_actions ADD CONSTRAINT autopilot_actions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: autopilot_actions_user_id_fkey on autopilot_actions'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.autopilot_recommendations DROP CONSTRAINT IF EXISTS autopilot_recommendations_user_id_fkey; ALTER TABLE public.autopilot_recommendations ADD CONSTRAINT autopilot_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: autopilot_recommendations_user_id_fkey on autopilot_recommendations'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.bookmarked_items DROP CONSTRAINT IF EXISTS bookmarked_items_user_id_fkey; ALTER TABLE public.bookmarked_items ADD CONSTRAINT bookmarked_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: bookmarked_items_user_id_fkey on bookmarked_items'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.business_packages DROP CONSTRAINT IF EXISTS business_packages_creator_id_fkey; ALTER TABLE public.business_packages ADD CONSTRAINT business_packages_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: business_packages_creator_id_fkey on business_packages'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.campaigns DROP CONSTRAINT IF EXISTS campaigns_user_id_fkey; ALTER TABLE public.campaigns ADD CONSTRAINT campaigns_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: campaigns_user_id_fkey on campaigns'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.cj_orders DROP CONSTRAINT IF EXISTS cj_orders_user_id_fkey; ALTER TABLE public.cj_orders ADD CONSTRAINT cj_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: cj_orders_user_id_fkey on cj_orders'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.community_live_streams DROP CONSTRAINT IF EXISTS community_live_streams_created_by_fkey; ALTER TABLE public.community_live_streams ADD CONSTRAINT community_live_streams_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: community_live_streams_created_by_fkey on community_live_streams'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.community_search_history DROP CONSTRAINT IF EXISTS community_search_history_viewer_user_id_fkey; ALTER TABLE public.community_search_history ADD CONSTRAINT community_search_history_viewer_user_id_fkey FOREIGN KEY (viewer_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: community_search_history_viewer_user_id_fkey on community_search_history'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.connection_requests DROP CONSTRAINT IF EXISTS connection_requests_from_user_id_fkey; ALTER TABLE public.connection_requests ADD CONSTRAINT connection_requests_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: connection_requests_from_user_id_fkey on connection_requests'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.connection_requests DROP CONSTRAINT IF EXISTS connection_requests_to_user_id_fkey; ALTER TABLE public.connection_requests ADD CONSTRAINT connection_requests_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: connection_requests_to_user_id_fkey on connection_requests'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.consents DROP CONSTRAINT IF EXISTS consents_user_id_fkey; ALTER TABLE public.consents ADD CONSTRAINT consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: consents_user_id_fkey on consents'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.contacts DROP CONSTRAINT IF EXISTS contacts_contact_user_id_fkey; ALTER TABLE public.contacts ADD CONSTRAINT contacts_contact_user_id_fkey FOREIGN KEY (contact_user_id) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: contacts_contact_user_id_fkey on contacts'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.contacts DROP CONSTRAINT IF EXISTS contacts_user_id_fkey; ALTER TABLE public.contacts ADD CONSTRAINT contacts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: contacts_user_id_fkey on contacts'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.content_reports DROP CONSTRAINT IF EXISTS content_reports_reporter_user_id_fkey; ALTER TABLE public.content_reports ADD CONSTRAINT content_reports_reporter_user_id_fkey FOREIGN KEY (reporter_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: content_reports_reporter_user_id_fkey on content_reports'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.content_reports DROP CONSTRAINT IF EXISTS content_reports_reviewed_by_fkey; ALTER TABLE public.content_reports ADD CONSTRAINT content_reports_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: content_reports_reviewed_by_fkey on content_reports'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.contradiction_flags DROP CONSTRAINT IF EXISTS contradiction_flags_user_id_fkey; ALTER TABLE public.contradiction_flags ADD CONSTRAINT contradiction_flags_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: contradiction_flags_user_id_fkey on contradiction_flags'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.curated_memories DROP CONSTRAINT IF EXISTS curated_memories_user_id_fkey; ALTER TABLE public.curated_memories ADD CONSTRAINT curated_memories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: curated_memories_user_id_fkey on curated_memories'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.daily_matches DROP CONSTRAINT IF EXISTS daily_matches_matched_user_id_fkey; ALTER TABLE public.daily_matches ADD CONSTRAINT daily_matches_matched_user_id_fkey FOREIGN KEY (matched_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: daily_matches_matched_user_id_fkey on daily_matches'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.daily_matches DROP CONSTRAINT IF EXISTS daily_matches_user_id_fkey; ALTER TABLE public.daily_matches ADD CONSTRAINT daily_matches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: daily_matches_user_id_fkey on daily_matches'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.daily_recompute_runs DROP CONSTRAINT IF EXISTS daily_recompute_runs_user_id_fkey; ALTER TABLE public.daily_recompute_runs ADD CONSTRAINT daily_recompute_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: daily_recompute_runs_user_id_fkey on daily_recompute_runs'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.distribution_channels DROP CONSTRAINT IF EXISTS distribution_channels_user_id_fkey; ALTER TABLE public.distribution_channels ADD CONSTRAINT distribution_channels_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: distribution_channels_user_id_fkey on distribution_channels'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.distribution_posts DROP CONSTRAINT IF EXISTS distribution_posts_user_id_fkey; ALTER TABLE public.distribution_posts ADD CONSTRAINT distribution_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: distribution_posts_user_id_fkey on distribution_posts'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.event_attendees DROP CONSTRAINT IF EXISTS event_attendees_invited_by_fkey; ALTER TABLE public.event_attendees ADD CONSTRAINT event_attendees_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: event_attendees_invited_by_fkey on event_attendees'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.event_co_creators DROP CONSTRAINT IF EXISTS event_co_creators_added_by_fkey; ALTER TABLE public.event_co_creators ADD CONSTRAINT event_co_creators_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: event_co_creators_added_by_fkey on event_co_creators'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.event_co_creators DROP CONSTRAINT IF EXISTS event_co_creators_user_id_fkey; ALTER TABLE public.event_co_creators ADD CONSTRAINT event_co_creators_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: event_co_creators_user_id_fkey on event_co_creators'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.event_recommendations DROP CONSTRAINT IF EXISTS event_recommendations_user_id_fkey; ALTER TABLE public.event_recommendations ADD CONSTRAINT event_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: event_recommendations_user_id_fkey on event_recommendations'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.event_ticket_purchases DROP CONSTRAINT IF EXISTS event_ticket_purchases_buyer_id_fkey; ALTER TABLE public.event_ticket_purchases ADD CONSTRAINT event_ticket_purchases_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: event_ticket_purchases_buyer_id_fkey on event_ticket_purchases'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.event_ticket_purchases DROP CONSTRAINT IF EXISTS event_ticket_purchases_checked_in_by_fkey; ALTER TABLE public.event_ticket_purchases ADD CONSTRAINT event_ticket_purchases_checked_in_by_fkey FOREIGN KEY (checked_in_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: event_ticket_purchases_checked_in_by_fkey on event_ticket_purchases'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.event_ticket_scans DROP CONSTRAINT IF EXISTS event_ticket_scans_scanned_by_fkey; ALTER TABLE public.event_ticket_scans ADD CONSTRAINT event_ticket_scans_scanned_by_fkey FOREIGN KEY (scanned_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: event_ticket_scans_scanned_by_fkey on event_ticket_scans'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.feedback_tickets DROP CONSTRAINT IF EXISTS feedback_tickets_rolled_back_by_fkey; ALTER TABLE public.feedback_tickets ADD CONSTRAINT feedback_tickets_rolled_back_by_fkey FOREIGN KEY (rolled_back_by) REFERENCES public.app_users(user_id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: feedback_tickets_rolled_back_by_fkey on feedback_tickets'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.global_community_events DROP CONSTRAINT IF EXISTS global_community_events_moderated_by_fkey; ALTER TABLE public.global_community_events ADD CONSTRAINT global_community_events_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: global_community_events_moderated_by_fkey on global_community_events'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.global_community_group_members DROP CONSTRAINT IF EXISTS global_community_group_members_user_id_fkey; ALTER TABLE public.global_community_group_members ADD CONSTRAINT global_community_group_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: global_community_group_members_user_id_fkey on global_community_group_members'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.global_community_groups DROP CONSTRAINT IF EXISTS global_community_groups_moderated_by_fkey; ALTER TABLE public.global_community_groups ADD CONSTRAINT global_community_groups_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: global_community_groups_moderated_by_fkey on global_community_groups'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.group_recommendations DROP CONSTRAINT IF EXISTS group_recommendations_user_id_fkey; ALTER TABLE public.group_recommendations ADD CONSTRAINT group_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: group_recommendations_user_id_fkey on group_recommendations'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.handle_aliases DROP CONSTRAINT IF EXISTS handle_aliases_user_id_fkey; ALTER TABLE public.handle_aliases ADD CONSTRAINT handle_aliases_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: handle_aliases_user_id_fkey on handle_aliases'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.intent_disputes DROP CONSTRAINT IF EXISTS intent_disputes_raised_by_fkey; ALTER TABLE public.intent_disputes ADD CONSTRAINT intent_disputes_raised_by_fkey FOREIGN KEY (raised_by) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: intent_disputes_raised_by_fkey on intent_disputes'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.intent_supply_seeded DROP CONSTRAINT IF EXISTS intent_supply_seeded_candidate_user_id_fkey; ALTER TABLE public.intent_supply_seeded ADD CONSTRAINT intent_supply_seeded_candidate_user_id_fkey FOREIGN KEY (candidate_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: intent_supply_seeded_candidate_user_id_fkey on intent_supply_seeded'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.journey_session_updates DROP CONSTRAINT IF EXISTS journey_session_updates_user_id_fkey; ALTER TABLE public.journey_session_updates ADD CONSTRAINT journey_session_updates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: journey_session_updates_user_id_fkey on journey_session_updates'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.lab_test_orders DROP CONSTRAINT IF EXISTS lab_test_orders_user_id_fkey; ALTER TABLE public.lab_test_orders ADD CONSTRAINT lab_test_orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: lab_test_orders_user_id_fkey on lab_test_orders'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.lab_test_results DROP CONSTRAINT IF EXISTS lab_test_results_user_id_fkey; ALTER TABLE public.lab_test_results ADD CONSTRAINT lab_test_results_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: lab_test_results_user_id_fkey on lab_test_results'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.life_compass DROP CONSTRAINT IF EXISTS life_compass_user_id_fkey; ALTER TABLE public.life_compass ADD CONSTRAINT life_compass_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: life_compass_user_id_fkey on life_compass'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.live_stream_subscribers DROP CONSTRAINT IF EXISTS live_stream_subscribers_user_id_fkey; ALTER TABLE public.live_stream_subscribers ADD CONSTRAINT live_stream_subscribers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: live_stream_subscribers_user_id_fkey on live_stream_subscribers'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.mcp_tool_executions DROP CONSTRAINT IF EXISTS mcp_tool_executions_executed_by_fkey; ALTER TABLE public.mcp_tool_executions ADD CONSTRAINT mcp_tool_executions_executed_by_fkey FOREIGN KEY (executed_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: mcp_tool_executions_executed_by_fkey on mcp_tool_executions'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.media_content DROP CONSTRAINT IF EXISTS media_content_user_id_fkey; ALTER TABLE public.media_content ADD CONSTRAINT media_content_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: media_content_user_id_fkey on media_content'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.memory_embeddings DROP CONSTRAINT IF EXISTS memory_embeddings_user_id_fkey; ALTER TABLE public.memory_embeddings ADD CONSTRAINT memory_embeddings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: memory_embeddings_user_id_fkey on memory_embeddings'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.memory_events DROP CONSTRAINT IF EXISTS memory_events_user_id_fkey; ALTER TABLE public.memory_events ADD CONSTRAINT memory_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: memory_events_user_id_fkey on memory_events'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.messages DROP CONSTRAINT IF EXISTS messages_recipient_id_fkey; ALTER TABLE public.messages ADD CONSTRAINT messages_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: messages_recipient_id_fkey on messages'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.messages DROP CONSTRAINT IF EXISTS messages_sender_id_fkey; ALTER TABLE public.messages ADD CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: messages_sender_id_fkey on messages'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_user_id_fkey; ALTER TABLE public.notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: notifications_user_id_fkey on notifications'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.package_purchases DROP CONSTRAINT IF EXISTS package_purchases_buyer_id_fkey; ALTER TABLE public.package_purchases ADD CONSTRAINT package_purchases_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: package_purchases_buyer_id_fkey on package_purchases'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.plan_adherence_logs DROP CONSTRAINT IF EXISTS plan_adherence_logs_user_id_fkey; ALTER TABLE public.plan_adherence_logs ADD CONSTRAINT plan_adherence_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: plan_adherence_logs_user_id_fkey on plan_adherence_logs'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.podcast_show_subscriptions DROP CONSTRAINT IF EXISTS podcast_show_subscriptions_user_id_fkey; ALTER TABLE public.podcast_show_subscriptions ADD CONSTRAINT podcast_show_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: podcast_show_subscriptions_user_id_fkey on podcast_show_subscriptions'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.post_analytics DROP CONSTRAINT IF EXISTS post_analytics_user_id_fkey; ALTER TABLE public.post_analytics ADD CONSTRAINT post_analytics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: post_analytics_user_id_fkey on post_analytics'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.proactive_context_cache DROP CONSTRAINT IF EXISTS proactive_context_cache_user_id_fkey; ALTER TABLE public.proactive_context_cache ADD CONSTRAINT proactive_context_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: proactive_context_cache_user_id_fkey on proactive_context_cache'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.proactive_engagement DROP CONSTRAINT IF EXISTS proactive_engagement_user_id_fkey; ALTER TABLE public.proactive_engagement ADD CONSTRAINT proactive_engagement_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: proactive_engagement_user_id_fkey on proactive_engagement'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.profile_posts DROP CONSTRAINT IF EXISTS profile_posts_user_id_fkey; ALTER TABLE public.profile_posts ADD CONSTRAINT profile_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: profile_posts_user_id_fkey on profile_posts'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_user_id_fkey; ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: profiles_user_id_fkey on profiles'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.provider_appointments DROP CONSTRAINT IF EXISTS provider_appointments_user_id_fkey; ALTER TABLE public.provider_appointments ADD CONSTRAINT provider_appointments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: provider_appointments_user_id_fkey on provider_appointments'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.provider_notes DROP CONSTRAINT IF EXISTS provider_notes_user_id_fkey; ALTER TABLE public.provider_notes ADD CONSTRAINT provider_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: provider_notes_user_id_fkey on provider_notes'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.reseller_profiles DROP CONSTRAINT IF EXISTS reseller_profiles_user_id_fkey; ALTER TABLE public.reseller_profiles ADD CONSTRAINT reseller_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: reseller_profiles_user_id_fkey on reseller_profiles'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.retrieval_traces DROP CONSTRAINT IF EXISTS retrieval_traces_actor_user_id_fkey; ALTER TABLE public.retrieval_traces ADD CONSTRAINT retrieval_traces_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: retrieval_traces_actor_user_id_fkey on retrieval_traces'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.role_sessions DROP CONSTRAINT IF EXISTS role_sessions_user_id_fkey; ALTER TABLE public.role_sessions ADD CONSTRAINT role_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: role_sessions_user_id_fkey on role_sessions'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.scheduled_posts DROP CONSTRAINT IF EXISTS scheduled_posts_user_id_fkey; ALTER TABLE public.scheduled_posts ADD CONSTRAINT scheduled_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: scheduled_posts_user_id_fkey on scheduled_posts'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.templates DROP CONSTRAINT IF EXISTS templates_user_id_fkey; ALTER TABLE public.templates ADD CONSTRAINT templates_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: templates_user_id_fkey on templates'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.thread_participants DROP CONSTRAINT IF EXISTS fk_thread_participants_user_id; ALTER TABLE public.thread_participants ADD CONSTRAINT fk_thread_participants_user_id FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: fk_thread_participants_user_id on thread_participants'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_active_days DROP CONSTRAINT IF EXISTS user_active_days_user_id_fkey; ALTER TABLE public.user_active_days ADD CONSTRAINT user_active_days_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_active_days_user_id_fkey on user_active_days'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_active_role DROP CONSTRAINT IF EXISTS user_active_role_user_id_fkey; ALTER TABLE public.user_active_role ADD CONSTRAINT user_active_role_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_active_role_user_id_fkey on user_active_role'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_active_roles DROP CONSTRAINT IF EXISTS user_active_roles_user_id_fkey; ALTER TABLE public.user_active_roles ADD CONSTRAINT user_active_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_active_roles_user_id_fkey on user_active_roles'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_activity_log DROP CONSTRAINT IF EXISTS user_activity_log_user_id_fkey; ALTER TABLE public.user_activity_log ADD CONSTRAINT user_activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_activity_log_user_id_fkey on user_activity_log'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_api_keys DROP CONSTRAINT IF EXISTS user_api_keys_user_id_fkey; ALTER TABLE public.user_api_keys ADD CONSTRAINT user_api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_api_keys_user_id_fkey on user_api_keys'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_context_cache DROP CONSTRAINT IF EXISTS user_context_cache_user_id_fkey; ALTER TABLE public.user_context_cache ADD CONSTRAINT user_context_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_context_cache_user_id_fkey on user_context_cache'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_discount_codes DROP CONSTRAINT IF EXISTS user_discount_codes_user_id_fkey; ALTER TABLE public.user_discount_codes ADD CONSTRAINT user_discount_codes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_discount_codes_user_id_fkey on user_discount_codes'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_feature_introductions DROP CONSTRAINT IF EXISTS user_feature_introductions_user_id_fkey; ALTER TABLE public.user_feature_introductions ADD CONSTRAINT user_feature_introductions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_feature_introductions_user_id_fkey on user_feature_introductions'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_feedback_reports DROP CONSTRAINT IF EXISTS user_feedback_reports_user_id_fkey; ALTER TABLE public.user_feedback_reports ADD CONSTRAINT user_feedback_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_feedback_reports_user_id_fkey on user_feedback_reports'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_follows DROP CONSTRAINT IF EXISTS user_follows_follower_id_fkey; ALTER TABLE public.user_follows ADD CONSTRAINT user_follows_follower_id_fkey FOREIGN KEY (follower_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_follows_follower_id_fkey on user_follows'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_follows DROP CONSTRAINT IF EXISTS user_follows_following_id_fkey; ALTER TABLE public.user_follows ADD CONSTRAINT user_follows_following_id_fkey FOREIGN KEY (following_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_follows_following_id_fkey on user_follows'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_guided_journey_state DROP CONSTRAINT IF EXISTS user_guided_journey_state_user_id_fkey; ALTER TABLE public.user_guided_journey_state ADD CONSTRAINT user_guided_journey_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_guided_journey_state_user_id_fkey on user_guided_journey_state'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_health_plans DROP CONSTRAINT IF EXISTS user_health_plans_user_id_fkey; ALTER TABLE public.user_health_plans ADD CONSTRAINT user_health_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_health_plans_user_id_fkey on user_health_plans'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_integrations DROP CONSTRAINT IF EXISTS user_integrations_user_id_fkey; ALTER TABLE public.user_integrations ADD CONSTRAINT user_integrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_integrations_user_id_fkey on user_integrations'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_intent_cover_library DROP CONSTRAINT IF EXISTS user_intent_cover_library_user_id_fkey; ALTER TABLE public.user_intent_cover_library ADD CONSTRAINT user_intent_cover_library_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_intent_cover_library_user_id_fkey on user_intent_cover_library'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_intents DROP CONSTRAINT IF EXISTS user_intents_requester_user_id_fkey; ALTER TABLE public.user_intents ADD CONSTRAINT user_intents_requester_user_id_fkey FOREIGN KEY (requester_user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_intents_requester_user_id_fkey on user_intents'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_interests DROP CONSTRAINT IF EXISTS user_interests_user_id_fkey; ALTER TABLE public.user_interests ADD CONSTRAINT user_interests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_interests_user_id_fkey on user_interests'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_journey DROP CONSTRAINT IF EXISTS user_journey_user_id_fkey; ALTER TABLE public.user_journey ADD CONSTRAINT user_journey_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_journey_user_id_fkey on user_journey'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_journey_foundation DROP CONSTRAINT IF EXISTS user_journey_foundation_user_id_fkey; ALTER TABLE public.user_journey_foundation ADD CONSTRAINT user_journey_foundation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_journey_foundation_user_id_fkey on user_journey_foundation'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_journey_overrides DROP CONSTRAINT IF EXISTS user_journey_overrides_user_id_fkey; ALTER TABLE public.user_journey_overrides ADD CONSTRAINT user_journey_overrides_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_journey_overrides_user_id_fkey on user_journey_overrides'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_memory_metadata DROP CONSTRAINT IF EXISTS user_memory_metadata_user_id_fkey; ALTER TABLE public.user_memory_metadata ADD CONSTRAINT user_memory_metadata_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_memory_metadata_user_id_fkey on user_memory_metadata'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_nudge_state DROP CONSTRAINT IF EXISTS user_nudge_state_user_id_fkey; ALTER TABLE public.user_nudge_state ADD CONSTRAINT user_nudge_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_nudge_state_user_id_fkey on user_nudge_state'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_permitted_roles DROP CONSTRAINT IF EXISTS user_permitted_roles_granted_by_fkey; ALTER TABLE public.user_permitted_roles ADD CONSTRAINT user_permitted_roles_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_permitted_roles_granted_by_fkey on user_permitted_roles'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_permitted_roles DROP CONSTRAINT IF EXISTS user_permitted_roles_user_id_fkey; ALTER TABLE public.user_permitted_roles ADD CONSTRAINT user_permitted_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_permitted_roles_user_id_fkey on user_permitted_roles'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_preferences DROP CONSTRAINT IF EXISTS user_preferences_user_id_fkey; ALTER TABLE public.user_preferences ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_preferences_user_id_fkey on user_preferences'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_proactive_pause DROP CONSTRAINT IF EXISTS user_proactive_pause_user_id_fkey; ALTER TABLE public.user_proactive_pause ADD CONSTRAINT user_proactive_pause_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_proactive_pause_user_id_fkey on user_proactive_pause'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_proactive_touches DROP CONSTRAINT IF EXISTS user_proactive_touches_user_id_fkey; ALTER TABLE public.user_proactive_touches ADD CONSTRAINT user_proactive_touches_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_proactive_touches_user_id_fkey on user_proactive_touches'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_profiler_version DROP CONSTRAINT IF EXISTS user_profiler_version_user_id_fkey; ALTER TABLE public.user_profiler_version ADD CONSTRAINT user_profiler_version_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_profiler_version_user_id_fkey on user_profiler_version'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_reputation DROP CONSTRAINT IF EXISTS user_reputation_user_id_fkey; ALTER TABLE public.user_reputation ADD CONSTRAINT user_reputation_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_reputation_user_id_fkey on user_reputation'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS user_roles_granted_by_fkey; ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.app_users(user_id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_roles_granted_by_fkey on user_roles'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_roles DROP CONSTRAINT IF EXISTS user_roles_user_id_fkey; ALTER TABLE public.user_roles ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_roles_user_id_fkey on user_roles'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_routines DROP CONSTRAINT IF EXISTS user_routines_user_id_fkey; ALTER TABLE public.user_routines ADD CONSTRAINT user_routines_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_routines_user_id_fkey on user_routines'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_session_summaries DROP CONSTRAINT IF EXISTS user_session_summaries_user_id_fkey; ALTER TABLE public.user_session_summaries ADD CONSTRAINT user_session_summaries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_session_summaries_user_id_fkey on user_session_summaries'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.user_wellness_interests DROP CONSTRAINT IF EXISTS user_wellness_interests_user_id_fkey; ALTER TABLE public.user_wellness_interests ADD CONSTRAINT user_wellness_interests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: user_wellness_interests_user_id_fkey on user_wellness_interests'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.vitana_index_baseline_survey DROP CONSTRAINT IF EXISTS vitana_index_baseline_survey_user_id_fkey; ALTER TABLE public.vitana_index_baseline_survey ADD CONSTRAINT vitana_index_baseline_survey_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: vitana_index_baseline_survey_user_id_fkey on vitana_index_baseline_survey'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.vitana_index_config DROP CONSTRAINT IF EXISTS vitana_index_config_created_by_fkey; ALTER TABLE public.vitana_index_config ADD CONSTRAINT vitana_index_config_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: vitana_index_config_created_by_fkey on vitana_index_config'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.vitana_pillar_agent_outputs DROP CONSTRAINT IF EXISTS vitana_pillar_agent_outputs_user_id_fkey; ALTER TABLE public.vitana_pillar_agent_outputs ADD CONSTRAINT vitana_pillar_agent_outputs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: vitana_pillar_agent_outputs_user_id_fkey on vitana_pillar_agent_outputs'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.vouchers DROP CONSTRAINT IF EXISTS vouchers_redeemed_by_user_id_fkey; ALTER TABLE public.vouchers ADD CONSTRAINT vouchers_redeemed_by_user_id_fkey FOREIGN KEY (redeemed_by_user_id) REFERENCES public.app_users(user_id) ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: vouchers_redeemed_by_user_id_fkey on vouchers'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.wallet_accounts DROP CONSTRAINT IF EXISTS wallet_accounts_user_id_fkey; ALTER TABLE public.wallet_accounts ADD CONSTRAINT wallet_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: wallet_accounts_user_id_fkey on wallet_accounts'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.wallet_credits DROP CONSTRAINT IF EXISTS wallet_credits_user_id_fkey; ALTER TABLE public.wallet_credits ADD CONSTRAINT wallet_credits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id) ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: wallet_credits_user_id_fkey on wallet_credits'; END $IDEMPOTENT$;
DO $IDEMPOTENT$ BEGIN ALTER TABLE public.wallet_deposits DROP CONSTRAINT IF EXISTS wallet_deposits_user_id_fkey; ALTER TABLE public.wallet_deposits ADD CONSTRAINT wallet_deposits_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.app_users(user_id); EXCEPTION WHEN duplicate_object THEN NULL; WHEN foreign_key_violation THEN RAISE NOTICE 'FK violation, skipped: wallet_deposits_user_id_fkey on wallet_deposits'; END $IDEMPOTENT$;
