-- FK constraints dropped from Aurora public schema on 2026-08-12 to unblock DMS full-load
-- table-prep (TRUNCATE/DROP kept failing with "other objects depend on it" across 245 FKs).
-- Restore these ONLY once Aurora has real write traffic that needs referential integrity
-- enforced locally -- until then Supabase (the DMS source) is the integrity-enforcing system.

ALTER TABLE ai_conversations ADD CONSTRAINT ai_conversations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE SET NULL;
ALTER TABLE ai_memory ADD CONSTRAINT ai_memory_source_conversation_id_fkey FOREIGN KEY (source_conversation_id) REFERENCES ai_conversations(id) ON DELETE SET NULL;
ALTER TABLE ai_recommendations ADD CONSTRAINT ai_recommendations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE ai_recommendations ADD CONSTRAINT ai_recommendations_situation_id_fkey FOREIGN KEY (situation_id) REFERENCES ai_situation_analyses(id) ON DELETE CASCADE;
ALTER TABLE ai_recommendations ADD CONSTRAINT ai_recommendations_deployed_rule_id_fkey FOREIGN KEY (deployed_rule_id) REFERENCES automation_rules(id) ON DELETE SET NULL;
ALTER TABLE ai_situation_analyses ADD CONSTRAINT ai_situation_analyses_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE app_users ADD CONSTRAINT fk_app_users_live_room FOREIGN KEY (live_room_id) REFERENCES live_rooms(id) ON DELETE SET NULL;
ALTER TABLE app_users ADD CONSTRAINT app_users_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE autopilot_actions ADD CONSTRAINT autopilot_actions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE SET NULL;
ALTER TABLE business_packages ADD CONSTRAINT business_packages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE campaign_recipients ADD CONSTRAINT campaign_recipients_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE chat_group_members ADD CONSTRAINT chat_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES chat_groups(id) ON DELETE CASCADE;
ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_group_id_fkey FOREIGN KEY (group_id) REFERENCES chat_groups(id) ON DELETE SET NULL;
ALTER TABLE cj_orders ADD CONSTRAINT cj_orders_checkout_session_id_fkey FOREIGN KEY (checkout_session_id) REFERENCES checkout_sessions(id);
ALTER TABLE commission_event ADD CONSTRAINT commission_event_affiliate_program_id_fkey FOREIGN KEY (affiliate_program_id) REFERENCES affiliate_program(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE community_listing_categories ADD CONSTRAINT community_listing_categories_parent_key_fkey FOREIGN KEY (parent_key) REFERENCES community_listing_categories(key) ON DELETE SET NULL;
ALTER TABLE community_listing_reports ADD CONSTRAINT community_listing_reports_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE community_listing_reports ADD CONSTRAINT community_listing_reports_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES community_listings(id) ON DELETE CASCADE;
ALTER TABLE community_listing_reports ADD CONSTRAINT community_listing_reports_reporter_user_id_fkey FOREIGN KEY (reporter_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE community_listings ADD CONSTRAINT community_listings_seller_user_id_fkey FOREIGN KEY (seller_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE community_listings ADD CONSTRAINT community_listings_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL;
ALTER TABLE community_listings ADD CONSTRAINT community_listings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE community_listing_seller_blocks ADD CONSTRAINT community_listing_seller_blocks_blocked_seller_id_fkey FOREIGN KEY (blocked_seller_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE community_listing_seller_blocks ADD CONSTRAINT community_listing_seller_blocks_viewer_user_id_fkey FOREIGN KEY (viewer_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE community_listing_seller_blocks ADD CONSTRAINT community_listing_seller_blocks_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE community_marketplace_seller_suspensions ADD CONSTRAINT community_marketplace_seller_suspensions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE community_marketplace_seller_suspensions ADD CONSTRAINT community_marketplace_seller_suspensions_seller_user_id_fkey FOREIGN KEY (seller_user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE consents ADD CONSTRAINT consents_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE contradiction_flags ADD CONSTRAINT contradiction_flags_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE curated_memories ADD CONSTRAINT curated_memories_consent_id_fkey FOREIGN KEY (consent_id) REFERENCES consents(consent_id);
ALTER TABLE curated_memories ADD CONSTRAINT curated_memories_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE curated_memories ADD CONSTRAINT curated_memories_source_event_id_fkey FOREIGN KEY (source_event_id) REFERENCES memory_events(event_id);
ALTER TABLE dev_autopilot_executions ADD CONSTRAINT dev_autopilot_executions_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE;
ALTER TABLE dev_autopilot_executions ADD CONSTRAINT dev_autopilot_executions_parent_execution_id_fkey FOREIGN KEY (parent_execution_id) REFERENCES dev_autopilot_executions(id);
ALTER TABLE dev_autopilot_outcomes ADD CONSTRAINT dev_autopilot_outcomes_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE;
ALTER TABLE dev_autopilot_plan_versions ADD CONSTRAINT dev_autopilot_plan_versions_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE;
ALTER TABLE dev_autopilot_signals ADD CONSTRAINT dev_autopilot_signals_run_id_fkey FOREIGN KEY (run_id) REFERENCES dev_autopilot_runs(run_id) ON DELETE CASCADE;
ALTER TABLE disclosure ADD CONSTRAINT disclosure_cart_order_id_fkey FOREIGN KEY (cart_order_id) REFERENCES cart_order(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE distribution_posts ADD CONSTRAINT distribution_posts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL;
ALTER TABLE entity_relationships ADD CONSTRAINT entity_relationships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE event_co_creators ADD CONSTRAINT event_co_creators_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE;
ALTER TABLE event_recommendations ADD CONSTRAINT event_recommendations_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE;
ALTER TABLE event_ticket_purchases ADD CONSTRAINT event_ticket_purchases_ticket_type_id_fkey FOREIGN KEY (ticket_type_id) REFERENCES event_ticket_types(id) ON DELETE CASCADE;
ALTER TABLE event_ticket_purchases ADD CONSTRAINT event_ticket_purchases_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE;
ALTER TABLE event_ticket_scans ADD CONSTRAINT event_ticket_scans_ticket_purchase_id_fkey FOREIGN KEY (ticket_purchase_id) REFERENCES event_ticket_purchases(id) ON DELETE CASCADE;
ALTER TABLE event_ticket_types ADD CONSTRAINT event_ticket_types_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE;
ALTER TABLE feature_entitlements ADD CONSTRAINT feature_entitlements_plan_key_fkey FOREIGN KEY (plan_key) REFERENCES subscription_plans(plan_key) ON DELETE CASCADE;
ALTER TABLE feedback_handoff_events ADD CONSTRAINT feedback_handoff_events_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES feedback_tickets(id) ON DELETE SET NULL;
ALTER TABLE feedback_tickets ADD CONSTRAINT feedback_tickets_linked_finding_id_fkey FOREIGN KEY (linked_finding_id) REFERENCES autopilot_recommendations(id) ON DELETE SET NULL;
ALTER TABLE feedback_tickets ADD CONSTRAINT feedback_tickets_duplicate_of_fkey FOREIGN KEY (duplicate_of) REFERENCES feedback_tickets(id) ON DELETE SET NULL;
ALTER TABLE global_community_group_members ADD CONSTRAINT global_community_group_members_group_id_fkey FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE;
ALTER TABLE global_community_groups ADD CONSTRAINT global_community_groups_chat_thread_id_fkey FOREIGN KEY (chat_thread_id) REFERENCES global_message_threads(id);
ALTER TABLE global_event_participants ADD CONSTRAINT fk_global_event_participants_event FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE CASCADE;
ALTER TABLE global_group_members ADD CONSTRAINT fk_global_group_members_group FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE;
ALTER TABLE global_messages ADD CONSTRAINT fk_global_messages_thread FOREIGN KEY (thread_id) REFERENCES global_message_threads(id) ON DELETE CASCADE;
ALTER TABLE global_thread_participants ADD CONSTRAINT fk_global_thread_participants_thread FOREIGN KEY (thread_id) REFERENCES global_message_threads(id) ON DELETE CASCADE;
ALTER TABLE global_typing_indicators ADD CONSTRAINT global_typing_indicators_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES global_message_threads(id) ON DELETE CASCADE;
ALTER TABLE goal_plan_i18n ADD CONSTRAINT goal_plan_i18n_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES goal_plans(id) ON DELETE CASCADE;
ALTER TABLE goal_plan_step_i18n ADD CONSTRAINT goal_plan_step_i18n_step_id_fkey FOREIGN KEY (step_id) REFERENCES goal_plan_steps(id) ON DELETE CASCADE;
ALTER TABLE goal_plan_steps ADD CONSTRAINT goal_plan_steps_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES goal_plans(id) ON DELETE CASCADE;
ALTER TABLE governance_enforcements ADD CONSTRAINT governance_enforcements_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES governance_rules(id) ON DELETE SET NULL;
ALTER TABLE governance_evaluations ADD CONSTRAINT governance_evaluations_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES governance_rules(id) ON DELETE CASCADE;
ALTER TABLE governance_rules ADD CONSTRAINT governance_rules_category_id_fkey FOREIGN KEY (category_id) REFERENCES governance_categories(id) ON DELETE SET NULL;
ALTER TABLE governance_violations ADD CONSTRAINT governance_violations_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES governance_rules(id) ON DELETE SET NULL;
ALTER TABLE group_post_comments ADD CONSTRAINT group_post_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES group_posts(id) ON DELETE CASCADE;
ALTER TABLE group_post_likes ADD CONSTRAINT group_post_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES group_posts(id) ON DELETE CASCADE;
ALTER TABLE group_posts ADD CONSTRAINT group_posts_group_id_fkey FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE;
ALTER TABLE group_recommendations ADD CONSTRAINT group_recommendations_group_id_fkey FOREIGN KEY (group_id) REFERENCES global_community_groups(id) ON DELETE CASCADE;
ALTER TABLE index_delta_observations ADD CONSTRAINT index_delta_observations_recommendation_id_fkey FOREIGN KEY (recommendation_id) REFERENCES autopilot_recommendations(id) ON DELETE CASCADE;
ALTER TABLE intent_categories ADD CONSTRAINT intent_categories_kind_key_fkey FOREIGN KEY (kind_key) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE;
ALTER TABLE intent_compass_boost ADD CONSTRAINT intent_compass_boost_intent_kind_fkey FOREIGN KEY (intent_kind) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE;
ALTER TABLE intent_compatibility ADD CONSTRAINT intent_compatibility_kind_b_fkey FOREIGN KEY (kind_b) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE;
ALTER TABLE intent_compatibility ADD CONSTRAINT intent_compatibility_kind_a_fkey FOREIGN KEY (kind_a) REFERENCES intent_kinds(kind_key) ON DELETE CASCADE;
ALTER TABLE intent_disputes ADD CONSTRAINT intent_disputes_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE CASCADE;
ALTER TABLE intent_events ADD CONSTRAINT intent_events_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE CASCADE;
ALTER TABLE intent_events ADD CONSTRAINT intent_events_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE;
ALTER TABLE intent_matches ADD CONSTRAINT intent_matches_intent_a_id_fkey FOREIGN KEY (intent_a_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE;
ALTER TABLE intent_matches ADD CONSTRAINT intent_matches_intent_b_id_fkey FOREIGN KEY (intent_b_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE;
ALTER TABLE intent_match_recommendations ADD CONSTRAINT intent_match_recommendations_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE;
ALTER TABLE intent_supply_seeded ADD CONSTRAINT intent_supply_seeded_intent_id_fkey FOREIGN KEY (intent_id) REFERENCES user_intents(intent_id) ON DELETE CASCADE;
ALTER TABLE job_artifact ADD CONSTRAINT job_artifact_attempt_id_fkey FOREIGN KEY (attempt_id) REFERENCES job_attempt(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE job_attempt ADD CONSTRAINT job_attempt_step_id_fkey FOREIGN KEY (step_id) REFERENCES job_step(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE job_step ADD CONSTRAINT job_step_job_id_fkey FOREIGN KEY (job_id) REFERENCES provisioning_job(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE lab_test_orders ADD CONSTRAINT lab_test_orders_lab_test_id_fkey FOREIGN KEY (lab_test_id) REFERENCES lab_tests(id);
ALTER TABLE lab_test_results ADD CONSTRAINT lab_test_results_order_id_fkey FOREIGN KEY (order_id) REFERENCES lab_test_orders(id) ON DELETE CASCADE;
ALTER TABLE life_compass_subgoals ADD CONSTRAINT life_compass_subgoals_compass_id_fkey FOREIGN KEY (compass_id) REFERENCES life_compass(id) ON DELETE CASCADE;
ALTER TABLE lifecycle_notification_state ADD CONSTRAINT lifecycle_notification_state_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES user_subscriptions(id) ON DELETE CASCADE;
ALTER TABLE listing_status_history ADD CONSTRAINT listing_status_history_listing_id_fkey FOREIGN KEY (listing_id) REFERENCES community_listings(id) ON DELETE CASCADE;
ALTER TABLE live_highlights ADD CONSTRAINT live_highlights_live_room_id_fkey FOREIGN KEY (live_room_id) REFERENCES live_rooms(id) ON DELETE CASCADE;
ALTER TABLE livekit_test_results ADD CONSTRAINT livekit_test_results_case_id_fkey FOREIGN KEY (case_id) REFERENCES livekit_test_cases(id) ON DELETE CASCADE;
ALTER TABLE livekit_test_results ADD CONSTRAINT livekit_test_results_run_id_fkey FOREIGN KEY (run_id) REFERENCES livekit_test_runs(id) ON DELETE CASCADE;
ALTER TABLE live_room_access_grants ADD CONSTRAINT fk_grants_session FOREIGN KEY (session_id) REFERENCES live_room_sessions(id) ON DELETE SET NULL;
ALTER TABLE live_room_access_grants ADD CONSTRAINT live_room_access_grants_room_id_fkey FOREIGN KEY (room_id) REFERENCES live_rooms(id) ON DELETE CASCADE;
ALTER TABLE live_room_access_grants ADD CONSTRAINT live_room_access_grants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE live_room_access_grants ADD CONSTRAINT live_room_access_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE live_room_attendance ADD CONSTRAINT live_room_attendance_live_room_id_fkey FOREIGN KEY (live_room_id) REFERENCES live_rooms(id) ON DELETE CASCADE;
ALTER TABLE live_room_attendance ADD CONSTRAINT fk_attendance_session FOREIGN KEY (session_id) REFERENCES live_room_sessions(id) ON DELETE SET NULL;
ALTER TABLE live_rooms ADD CONSTRAINT fk_live_rooms_current_session FOREIGN KEY (current_session_id) REFERENCES live_room_sessions(id) ON DELETE SET NULL;
ALTER TABLE live_room_sessions ADD CONSTRAINT live_room_sessions_room_id_fkey FOREIGN KEY (room_id) REFERENCES live_rooms(id) ON DELETE CASCADE;
ALTER TABLE live_stream_subscribers ADD CONSTRAINT live_stream_subscribers_stream_id_fkey FOREIGN KEY (stream_id) REFERENCES community_live_streams(id) ON DELETE CASCADE;
ALTER TABLE llm_allowed_models ADD CONSTRAINT llm_allowed_models_provider_key_fkey FOREIGN KEY (provider_key) REFERENCES llm_allowed_providers(provider_key) ON DELETE CASCADE;
ALTER TABLE llm_routing_policy_audit ADD CONSTRAINT llm_routing_policy_audit_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES llm_routing_policy(id) ON DELETE SET NULL;
ALTER TABLE location_visits ADD CONSTRAINT location_visits_location_id_fkey FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE;
ALTER TABLE match_notifications ADD CONSTRAINT match_notifications_match_id_fkey FOREIGN KEY (match_id) REFERENCES user_matches(id) ON DELETE CASCADE;
ALTER TABLE mcp_tool_executions ADD CONSTRAINT mcp_tool_executions_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES api_integrations(id) ON DELETE CASCADE;
ALTER TABLE media_analytics ADD CONSTRAINT media_analytics_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE;
ALTER TABLE media_upload_comments ADD CONSTRAINT media_upload_comments_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES media_uploads(id) ON DELETE CASCADE;
ALTER TABLE media_upload_likes ADD CONSTRAINT media_upload_likes_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES media_uploads(id) ON DELETE CASCADE;
ALTER TABLE media_video_comment_likes ADD CONSTRAINT media_video_comment_likes_comment_id_fkey FOREIGN KEY (comment_id) REFERENCES media_video_comments(id) ON DELETE CASCADE;
ALTER TABLE media_video_comments ADD CONSTRAINT media_video_comments_video_id_fkey FOREIGN KEY (video_id) REFERENCES media_videos(id) ON DELETE CASCADE;
ALTER TABLE media_video_comments ADD CONSTRAINT media_video_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES media_video_comments(id) ON DELETE CASCADE;
ALTER TABLE memberships ADD CONSTRAINT memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE mem_episodes ADD CONSTRAINT mem_episodes_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES mem_episodes(id);
ALTER TABLE mem_facts ADD CONSTRAINT mem_facts_source_episode_id_fkey FOREIGN KEY (source_episode_id) REFERENCES mem_episodes(id);
ALTER TABLE mem_facts ADD CONSTRAINT mem_facts_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES mem_facts(id);
ALTER TABLE mem_graph_edges ADD CONSTRAINT mem_graph_edges_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES mem_graph_edges(id);
ALTER TABLE memory_category_mapping ADD CONSTRAINT memory_category_mapping_garden_category_fkey FOREIGN KEY (garden_category) REFERENCES memory_garden_config(category_key);
ALTER TABLE memory_embeddings ADD CONSTRAINT memory_embeddings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE memory_events ADD CONSTRAINT memory_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE memory_facts ADD CONSTRAINT memory_facts_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES memory_facts(id);
ALTER TABLE memory_items ADD CONSTRAINT memory_items_category_key_fkey FOREIGN KEY (category_key) REFERENCES memory_categories(key);
ALTER TABLE memory_node_sources ADD CONSTRAINT memory_node_sources_node_id_fkey FOREIGN KEY (node_id) REFERENCES memory_garden_nodes(id) ON DELETE CASCADE;
ALTER TABLE memory_node_sources ADD CONSTRAINT memory_node_sources_diary_entry_id_fkey FOREIGN KEY (diary_entry_id) REFERENCES memory_diary_entries(id) ON DELETE CASCADE;
ALTER TABLE merchant_route ADD CONSTRAINT merchant_route_cart_order_id_fkey FOREIGN KEY (cart_order_id) REFERENCES cart_order(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE message_actions ADD CONSTRAINT message_actions_message_id_fkey FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE message_queue ADD CONSTRAINT message_queue_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES campaign_recipients(id) ON DELETE CASCADE;
ALTER TABLE message_queue ADD CONSTRAINT message_queue_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_parent_message_id_fkey FOREIGN KEY (parent_message_id) REFERENCES messages(id);
ALTER TABLE messages ADD CONSTRAINT messages_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE messages ADD CONSTRAINT messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads(id);
ALTER TABLE music_metadata ADD CONSTRAINT music_metadata_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE;
ALTER TABLE nav_catalog_i18n ADD CONSTRAINT nav_catalog_i18n_catalog_id_fkey FOREIGN KEY (catalog_id) REFERENCES nav_catalog(id) ON DELETE CASCADE;
ALTER TABLE oasis_spec_approvals ADD CONSTRAINT oasis_spec_approvals_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES oasis_specs(id) ON DELETE CASCADE;
ALTER TABLE oasis_spec_validations ADD CONSTRAINT oasis_spec_validations_spec_id_fkey FOREIGN KEY (spec_id) REFERENCES oasis_specs(id) ON DELETE CASCADE;
ALTER TABLE onboarding_invitations ADD CONSTRAINT onboarding_invitations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE onboarding_invitations ADD CONSTRAINT onboarding_invitations_signup_attempt_id_fkey FOREIGN KEY (signup_attempt_id) REFERENCES signup_attempts(id);
ALTER TABLE orb_session_state ADD CONSTRAINT orb_session_state_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_package_item_id_fkey FOREIGN KEY (package_item_id) REFERENCES package_items(id) ON DELETE CASCADE;
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_ticket_purchase_id_fkey FOREIGN KEY (ticket_purchase_id) REFERENCES event_ticket_purchases(id);
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE package_item_redemptions ADD CONSTRAINT package_item_redemptions_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES package_purchases(id) ON DELETE CASCADE;
ALTER TABLE package_items ADD CONSTRAINT package_items_package_id_fkey FOREIGN KEY (package_id) REFERENCES business_packages(id) ON DELETE CASCADE;
ALTER TABLE package_items ADD CONSTRAINT package_items_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id) ON DELETE SET NULL;
ALTER TABLE package_items ADD CONSTRAINT package_items_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE package_purchases ADD CONSTRAINT package_purchases_package_id_fkey FOREIGN KEY (package_id) REFERENCES business_packages(id);
ALTER TABLE package_purchases ADD CONSTRAINT package_purchases_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE patient_provider_assignments ADD CONSTRAINT patient_provider_assignments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE pattern_discoveries ADD CONSTRAINT pattern_discoveries_implemented_rule_id_fkey FOREIGN KEY (implemented_rule_id) REFERENCES automation_rules(id) ON DELETE SET NULL;
ALTER TABLE pattern_discoveries ADD CONSTRAINT pattern_discoveries_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE plan_adherence_logs ADD CONSTRAINT plan_adherence_logs_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES user_health_plans(id) ON DELETE CASCADE;
ALTER TABLE podcast_favorites ADD CONSTRAINT podcast_favorites_podcast_id_fkey FOREIGN KEY (podcast_id) REFERENCES media_uploads(id) ON DELETE CASCADE;
ALTER TABLE podcast_metadata ADD CONSTRAINT podcast_metadata_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE;
ALTER TABLE post_analytics ADD CONSTRAINT post_analytics_post_id_fkey FOREIGN KEY (post_id) REFERENCES distribution_posts(id) ON DELETE CASCADE;
ALTER TABLE product_clicks ADD CONSTRAINT product_clicks_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE product_clicks ADD CONSTRAINT product_clicks_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL;
ALTER TABLE product_orders ADD CONSTRAINT product_orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL;
ALTER TABLE product_orders ADD CONSTRAINT product_orders_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL;
ALTER TABLE product_outcomes ADD CONSTRAINT product_outcomes_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE product_outcomes ADD CONSTRAINT product_outcomes_order_id_fkey FOREIGN KEY (order_id) REFERENCES product_orders(id) ON DELETE SET NULL;
ALTER TABLE product_recommendations ADD CONSTRAINT product_recommendations_sharing_link_id_fkey FOREIGN KEY (sharing_link_id) REFERENCES sharing_links(id) ON DELETE SET NULL;
ALTER TABLE product_recommendations ADD CONSTRAINT product_recommendations_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE;
ALTER TABLE product_recommendations ADD CONSTRAINT product_recommendations_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE SET NULL;
ALTER TABLE products ADD CONSTRAINT products_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id) ON DELETE CASCADE;
ALTER TABLE profiles ADD CONSTRAINT profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE provider_account ADD CONSTRAINT provider_account_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES provider(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE provisioning_job ADD CONSTRAINT provisioning_job_provider_account_id_fkey FOREIGN KEY (provider_account_id) REFERENCES provider_account(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE recommendation_commissions ADD CONSTRAINT recommendation_commissions_product_recommendation_id_fkey FOREIGN KEY (product_recommendation_id) REFERENCES product_recommendations(id) ON DELETE CASCADE;
ALTER TABLE recommendation_commissions ADD CONSTRAINT recommendation_commissions_product_order_id_fkey FOREIGN KEY (product_order_id) REFERENCES product_orders(id) ON DELETE CASCADE;
ALTER TABLE recommendation_deployments ADD CONSTRAINT recommendation_deployments_recommendation_id_fkey FOREIGN KEY (recommendation_id) REFERENCES ai_recommendations(id) ON DELETE CASCADE;
ALTER TABLE recommendation_deployments ADD CONSTRAINT recommendation_deployments_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES automation_rules(id) ON DELETE CASCADE;
ALTER TABLE redemption_codes ADD CONSTRAINT redemption_codes_grants_plan_fkey FOREIGN KEY (grants_plan) REFERENCES subscription_plans(plan_key);
ALTER TABLE redemption_redemptions ADD CONSTRAINT redemption_redemptions_code_fkey FOREIGN KEY (code) REFERENCES redemption_codes(code);
ALTER TABLE relationship_dates ADD CONSTRAINT relationship_dates_relationship_node_id_fkey FOREIGN KEY (relationship_node_id) REFERENCES relationship_nodes(id) ON DELETE CASCADE;
ALTER TABLE relationship_health_context ADD CONSTRAINT relationship_health_context_relationship_node_id_fkey FOREIGN KEY (relationship_node_id) REFERENCES relationship_nodes(id) ON DELETE CASCADE;
ALTER TABLE relationship_health_context ADD CONSTRAINT relationship_health_context_superseded_by_fkey FOREIGN KEY (superseded_by) REFERENCES relationship_health_context(id);
ALTER TABLE relationship_health_context ADD CONSTRAINT relationship_health_context_source_episode_id_fkey FOREIGN KEY (source_episode_id) REFERENCES mem_episodes(id);
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_event_id_fkey FOREIGN KEY (event_id) REFERENCES global_community_events(id);
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_ticket_purchase_id_fkey FOREIGN KEY (ticket_purchase_id) REFERENCES event_ticket_purchases(id);
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_reseller_id_fkey FOREIGN KEY (reseller_id) REFERENCES reseller_profiles(id);
ALTER TABLE reseller_attributions ADD CONSTRAINT reseller_attributions_payout_id_fkey FOREIGN KEY (payout_id) REFERENCES reseller_payouts(id);
ALTER TABLE reseller_payouts ADD CONSTRAINT reseller_payouts_wallet_transaction_id_fkey FOREIGN KEY (wallet_transaction_id) REFERENCES wallet_transactions(id);
ALTER TABLE reseller_payouts ADD CONSTRAINT reseller_payouts_reseller_profile_id_fkey FOREIGN KEY (reseller_profile_id) REFERENCES reseller_profiles(id);
ALTER TABLE reseller_profiles ADD CONSTRAINT reseller_profiles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE retrieval_traces ADD CONSTRAINT retrieval_traces_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE rewards_ledger ADD CONSTRAINT rewards_ledger_commission_event_id_fkey FOREIGN KEY (commission_event_id) REFERENCES commission_event(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE role_preferences ADD CONSTRAINT role_preferences_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE role_sessions ADD CONSTRAINT role_sessions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE routine_runs ADD CONSTRAINT routine_runs_routine_name_fkey FOREIGN KEY (routine_name) REFERENCES routines(name) ON DELETE CASCADE;
ALTER TABLE scheduled_posts ADD CONSTRAINT scheduled_posts_post_id_fkey FOREIGN KEY (post_id) REFERENCES distribution_posts(id) ON DELETE CASCADE;
ALTER TABLE service_payments ADD CONSTRAINT service_payments_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE SET NULL;
ALTER TABLE signup_attempts ADD CONSTRAINT signup_attempts_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id);
ALTER TABLE stream_recordings ADD CONSTRAINT stream_recordings_stream_id_fkey FOREIGN KEY (stream_id) REFERENCES community_live_streams(id) ON DELETE CASCADE;
ALTER TABLE subscription_plan_prices ADD CONSTRAINT subscription_plan_prices_plan_key_fkey FOREIGN KEY (plan_key) REFERENCES subscription_plans(plan_key) ON DELETE CASCADE;
ALTER TABLE tenant_autopilot_bindings ADD CONSTRAINT tenant_autopilot_bindings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE tenant_autopilot_bindings ADD CONSTRAINT tenant_autopilot_bindings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES app_users(user_id);
ALTER TABLE tenant_autopilot_runs ADD CONSTRAINT tenant_autopilot_runs_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE tenant_autopilot_runs ADD CONSTRAINT tenant_autopilot_runs_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES app_users(user_id);
ALTER TABLE tenant_autopilot_runs ADD CONSTRAINT tenant_autopilot_runs_binding_id_fkey FOREIGN KEY (binding_id) REFERENCES tenant_autopilot_bindings(id) ON DELETE SET NULL;
ALTER TABLE tenant_autopilot_settings ADD CONSTRAINT tenant_autopilot_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE tenant_autopilot_settings ADD CONSTRAINT tenant_autopilot_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES app_users(user_id);
ALTER TABLE test_contract_runs ADD CONSTRAINT test_contract_runs_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES test_contracts(id) ON DELETE CASCADE;
ALTER TABLE test_cycles ADD CONSTRAINT fk_test_cycles_last_run FOREIGN KEY (last_run_id) REFERENCES test_runs(id);
ALTER TABLE test_results ADD CONSTRAINT test_results_run_id_fkey FOREIGN KEY (run_id) REFERENCES test_runs(id) ON DELETE CASCADE;
ALTER TABLE test_runs ADD CONSTRAINT test_runs_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES test_cycles(id);
ALTER TABLE thread_participants ADD CONSTRAINT thread_participants_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE;
ALTER TABLE thread_participants ADD CONSTRAINT fk_thread_participants_thread_id FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE;
ALTER TABLE training_cycle_days ADD CONSTRAINT training_cycle_days_cycle_id_fkey FOREIGN KEY (cycle_id) REFERENCES training_cycles(id) ON DELETE CASCADE;
ALTER TABLE typing_indicators ADD CONSTRAINT typing_indicators_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE typing_indicators ADD CONSTRAINT typing_indicators_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES message_threads(id) ON DELETE CASCADE;
ALTER TABLE universal_cart_events ADD CONSTRAINT universal_cart_events_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES universal_carts(id) ON DELETE CASCADE;
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES products(id);
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES merchants(id);
ALTER TABLE universal_cart_items ADD CONSTRAINT universal_cart_items_cart_id_fkey FOREIGN KEY (cart_id) REFERENCES universal_carts(id) ON DELETE CASCADE;
ALTER TABLE universal_carts ADD CONSTRAINT universal_carts_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE user_capability_awareness ADD CONSTRAINT user_capability_awareness_capability_key_fkey FOREIGN KEY (capability_key) REFERENCES system_capabilities(capability_key) ON DELETE CASCADE;
ALTER TABLE user_category_preferences ADD CONSTRAINT user_category_preferences_category_id_fkey FOREIGN KEY (category_id) REFERENCES notification_categories(id) ON DELETE CASCADE;
ALTER TABLE user_connections ADD CONSTRAINT user_connections_connector_id_fkey FOREIGN KEY (connector_id) REFERENCES connector_registry(id);
ALTER TABLE user_device_session_log ADD CONSTRAINT user_device_session_log_device_token_id_fkey FOREIGN KEY (device_token_id) REFERENCES user_device_tokens(id) ON DELETE CASCADE;
ALTER TABLE user_feedback_reports ADD CONSTRAINT user_feedback_reports_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE SET NULL;
ALTER TABLE user_intents ADD CONSTRAINT user_intents_intent_kind_fkey FOREIGN KEY (intent_kind) REFERENCES intent_kinds(kind_key);
ALTER TABLE user_limitations ADD CONSTRAINT user_limitations_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE user_location_history ADD CONSTRAINT user_location_history_named_place_id_fkey FOREIGN KEY (named_place_id) REFERENCES user_location_settings(id) ON DELETE SET NULL;
ALTER TABLE user_ratings ADD CONSTRAINT user_ratings_match_id_fkey FOREIGN KEY (match_id) REFERENCES intent_matches(match_id) ON DELETE SET NULL;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE RESTRICT;
ALTER TABLE user_subscriptions ADD CONSTRAINT user_subscriptions_plan_key_fkey FOREIGN KEY (plan_key) REFERENCES subscription_plans(plan_key);
ALTER TABLE user_subscriptions ADD CONSTRAINT user_subscriptions_price_key_fkey FOREIGN KEY (price_key) REFERENCES subscription_plan_prices(price_key);
ALTER TABLE user_tenants ADD CONSTRAINT user_tenants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE user_tenants ADD CONSTRAINT user_tenants_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE vaea_detected_questions ADD CONSTRAINT vaea_detected_questions_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES vaea_listener_channels(id) ON DELETE CASCADE;
ALTER TABLE vaea_reply_drafts ADD CONSTRAINT vaea_reply_drafts_detected_question_id_fkey FOREIGN KEY (detected_question_id) REFERENCES vaea_detected_questions(id) ON DELETE CASCADE;
ALTER TABLE vaea_reply_drafts ADD CONSTRAINT vaea_reply_drafts_catalog_item_id_fkey FOREIGN KEY (catalog_item_id) REFERENCES vaea_referral_catalog(id) ON DELETE SET NULL;
ALTER TABLE video_metadata ADD CONSTRAINT video_metadata_media_id_fkey FOREIGN KEY (media_id) REFERENCES media_uploads(id) ON DELETE CASCADE;
ALTER TABLE voucher_orders ADD CONSTRAINT voucher_orders_voucher_id_fkey FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE CASCADE;
ALTER TABLE voucher_orders ADD CONSTRAINT voucher_orders_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE voucher_redemptions ADD CONSTRAINT voucher_redemptions_voucher_id_fkey FOREIGN KEY (voucher_id) REFERENCES vouchers(id) ON DELETE CASCADE;
ALTER TABLE voucher_redemptions ADD CONSTRAINT voucher_redemptions_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE vouchers ADD CONSTRAINT vouchers_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE wallet_credits ADD CONSTRAINT wallet_credits_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES tenants(tenant_id) ON DELETE CASCADE;
ALTER TABLE wallet_deposits ADD CONSTRAINT wallet_deposits_account_id_fkey FOREIGN KEY (account_id) REFERENCES wallet_accounts(id);
ALTER TABLE wallet_ledger_entries ADD CONSTRAINT wallet_ledger_entries_account_id_fkey FOREIGN KEY (account_id) REFERENCES wallet_accounts(id);
ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES profiles(user_id) NOT VALID;
ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES profiles(user_id) NOT VALID;
ALTER TABLE wearable_daily_metrics ADD CONSTRAINT wearable_daily_metrics_user_connection_id_fkey FOREIGN KEY (user_connection_id) REFERENCES user_connections(id) ON DELETE CASCADE;
ALTER TABLE wearable_waitlist ADD CONSTRAINT wearable_waitlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES app_users(user_id) ON DELETE CASCADE;
ALTER TABLE wearable_workouts ADD CONSTRAINT wearable_workouts_user_connection_id_fkey FOREIGN KEY (user_connection_id) REFERENCES user_connections(id) ON DELETE CASCADE;
