#!/usr/bin/env bash
# Run this in AWS CloudShell (your own console session — never Claude's).
# Does two things Claude's IAM identity (claude-code-aws-agent) is explicitly
# denied from doing:
#   1. Drops the 245 FK constraints blocking the DMS full reload of Aurora
#      (Aurora is a DMS-fed replica with no direct write traffic yet -- these
#      are restorable any time from aurora-fk-restore-2026-08-12.sql).
#   2. Creates the `authenticator` Postgres role PostgREST needs, and stores
#      its connection string in Secrets Manager.
# The master secret's password is never printed or echoed anywhere -- RDS
# Data API authenticates using the secret ARN directly.
set -euo pipefail

REGION="eu-central-1"
CLUSTER_ARN="arn:aws:rds:eu-central-1:472838866351:cluster:vitana-aurora-prod"
DB="vitana"

echo "=== Resolving Aurora master secret ==="
# --no-paginate is load-bearing here: list-secrets auto-paginates, and
# --query is applied PER PAGE by the CLI, not to the combined result set.
# With ~80 secrets in this account spread across multiple pages, most pages
# have no match (prints "None") and exactly one page has the real ARN --
# without --no-paginate, $MASTER_SECRET_ARN ends up as a multi-line blob of
# "None"s with the real ARN buried in the middle, which silently poisons
# every use of the variable below.
MASTER_SECRET_ARN=$(aws secretsmanager list-secrets --region "$REGION" --no-paginate \
  --query "SecretList[?starts_with(Name, 'rds!cluster-')].ARN | [0]" --output text)

# Defensive check: this must be exactly one line and look like an ARN. If
# pagination bites again for any reason, fail loudly here instead of
# passing garbage to get-secret-value.
LINE_COUNT=$(printf '%s' "$MASTER_SECRET_ARN" | wc -l)
if [ -z "$MASTER_SECRET_ARN" ] || [ "$MASTER_SECRET_ARN" == "None" ] || [ "$LINE_COUNT" -gt 0 ] || [[ "$MASTER_SECRET_ARN" != arn:aws:secretsmanager:* ]]; then
  echo "ERROR: could not cleanly resolve the RDS-managed master secret (got: '$MASTER_SECRET_ARN'). Aborting." >&2
  exit 1
fi
echo "Using master secret: $MASTER_SECRET_ARN"

# Safety check (lesson from earlier today): confirm the secret actually has
# content before trusting it for anything, without ever printing the value.
SECRET_LEN=$(aws secretsmanager get-secret-value --region "$REGION" \
  --secret-id "$MASTER_SECRET_ARN" --query 'SecretString' --output text | wc -c)
if [ "$SECRET_LEN" -lt 20 ]; then
  echo "ERROR: master secret looks empty/too short ($SECRET_LEN chars). Aborting." >&2
  exit 1
fi
echo "Master secret looks populated ($SECRET_LEN chars). Proceeding."
echo

run_sql() {
  local sql="$1"
  aws rds-data execute-statement --region "$REGION" \
    --resource-arn "$CLUSTER_ARN" --secret-arn "$MASTER_SECRET_ARN" \
    --database "$DB" --sql "$sql"
}

echo "=== Step 1: Dropping 245 FK constraints on Aurora (unblocks DMS reload) ==="
ok=0
fail=0
if run_sql 'ALTER TABLE messages DROP CONSTRAINT messages_parent_message_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE messages DROP CONSTRAINT messages_parent_message_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE scheduled_posts DROP CONSTRAINT scheduled_posts_post_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE scheduled_posts DROP CONSTRAINT scheduled_posts_post_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE service_payments DROP CONSTRAINT service_payments_match_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE service_payments DROP CONSTRAINT service_payments_match_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE signup_attempts DROP CONSTRAINT signup_attempts_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE signup_attempts DROP CONSTRAINT signup_attempts_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE stream_recordings DROP CONSTRAINT stream_recordings_stream_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE stream_recordings DROP CONSTRAINT stream_recordings_stream_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE subscription_plan_prices DROP CONSTRAINT subscription_plan_prices_plan_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE subscription_plan_prices DROP CONSTRAINT subscription_plan_prices_plan_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE tenant_autopilot_bindings DROP CONSTRAINT tenant_autopilot_bindings_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE tenant_autopilot_bindings DROP CONSTRAINT tenant_autopilot_bindings_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE tenant_autopilot_bindings DROP CONSTRAINT tenant_autopilot_bindings_updated_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE tenant_autopilot_bindings DROP CONSTRAINT tenant_autopilot_bindings_updated_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE tenant_autopilot_runs DROP CONSTRAINT tenant_autopilot_runs_binding_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE tenant_autopilot_runs DROP CONSTRAINT tenant_autopilot_runs_binding_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE tenant_autopilot_runs DROP CONSTRAINT tenant_autopilot_runs_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE tenant_autopilot_runs DROP CONSTRAINT tenant_autopilot_runs_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE tenant_autopilot_runs DROP CONSTRAINT tenant_autopilot_runs_triggered_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE tenant_autopilot_runs DROP CONSTRAINT tenant_autopilot_runs_triggered_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE tenant_autopilot_settings DROP CONSTRAINT tenant_autopilot_settings_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE tenant_autopilot_settings DROP CONSTRAINT tenant_autopilot_settings_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE tenant_autopilot_settings DROP CONSTRAINT tenant_autopilot_settings_updated_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE tenant_autopilot_settings DROP CONSTRAINT tenant_autopilot_settings_updated_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE test_contract_runs DROP CONSTRAINT test_contract_runs_contract_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE test_contract_runs DROP CONSTRAINT test_contract_runs_contract_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE test_results DROP CONSTRAINT test_results_run_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE test_results DROP CONSTRAINT test_results_run_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE test_runs DROP CONSTRAINT test_runs_cycle_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE test_runs DROP CONSTRAINT test_runs_cycle_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE thread_participants DROP CONSTRAINT thread_participants_thread_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE thread_participants DROP CONSTRAINT thread_participants_thread_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE training_cycle_days DROP CONSTRAINT training_cycle_days_cycle_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE training_cycle_days DROP CONSTRAINT training_cycle_days_cycle_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE typing_indicators DROP CONSTRAINT typing_indicators_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE typing_indicators DROP CONSTRAINT typing_indicators_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE messages DROP CONSTRAINT messages_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE messages DROP CONSTRAINT messages_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE messages DROP CONSTRAINT messages_thread_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE messages DROP CONSTRAINT messages_thread_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE music_metadata DROP CONSTRAINT music_metadata_media_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE music_metadata DROP CONSTRAINT music_metadata_media_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE nav_catalog_i18n DROP CONSTRAINT nav_catalog_i18n_catalog_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE nav_catalog_i18n DROP CONSTRAINT nav_catalog_i18n_catalog_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE oasis_spec_approvals DROP CONSTRAINT oasis_spec_approvals_spec_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE oasis_spec_approvals DROP CONSTRAINT oasis_spec_approvals_spec_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE oasis_spec_validations DROP CONSTRAINT oasis_spec_validations_spec_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE oasis_spec_validations DROP CONSTRAINT oasis_spec_validations_spec_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE onboarding_invitations DROP CONSTRAINT onboarding_invitations_signup_attempt_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE onboarding_invitations DROP CONSTRAINT onboarding_invitations_signup_attempt_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE onboarding_invitations DROP CONSTRAINT onboarding_invitations_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE onboarding_invitations DROP CONSTRAINT onboarding_invitations_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_package_item_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_package_item_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_purchase_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_purchase_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_ticket_purchase_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_item_redemptions DROP CONSTRAINT package_item_redemptions_ticket_purchase_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_items DROP CONSTRAINT package_items_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_items DROP CONSTRAINT package_items_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_items DROP CONSTRAINT package_items_package_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_items DROP CONSTRAINT package_items_package_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_items DROP CONSTRAINT package_items_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_items DROP CONSTRAINT package_items_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_purchases DROP CONSTRAINT package_purchases_package_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_purchases DROP CONSTRAINT package_purchases_package_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE package_purchases DROP CONSTRAINT package_purchases_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE package_purchases DROP CONSTRAINT package_purchases_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE patient_provider_assignments DROP CONSTRAINT patient_provider_assignments_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE patient_provider_assignments DROP CONSTRAINT patient_provider_assignments_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE pattern_discoveries DROP CONSTRAINT pattern_discoveries_implemented_rule_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE pattern_discoveries DROP CONSTRAINT pattern_discoveries_implemented_rule_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE pattern_discoveries DROP CONSTRAINT pattern_discoveries_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE pattern_discoveries DROP CONSTRAINT pattern_discoveries_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE plan_adherence_logs DROP CONSTRAINT plan_adherence_logs_plan_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE plan_adherence_logs DROP CONSTRAINT plan_adherence_logs_plan_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE podcast_favorites DROP CONSTRAINT podcast_favorites_podcast_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE podcast_favorites DROP CONSTRAINT podcast_favorites_podcast_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE podcast_metadata DROP CONSTRAINT podcast_metadata_media_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE podcast_metadata DROP CONSTRAINT podcast_metadata_media_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE post_analytics DROP CONSTRAINT post_analytics_post_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE post_analytics DROP CONSTRAINT post_analytics_post_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_clicks DROP CONSTRAINT product_clicks_merchant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_clicks DROP CONSTRAINT product_clicks_merchant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_clicks DROP CONSTRAINT product_clicks_product_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_clicks DROP CONSTRAINT product_clicks_product_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_orders DROP CONSTRAINT product_orders_merchant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_orders DROP CONSTRAINT product_orders_merchant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_orders DROP CONSTRAINT product_orders_product_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_orders DROP CONSTRAINT product_orders_product_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_outcomes DROP CONSTRAINT product_outcomes_order_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_outcomes DROP CONSTRAINT product_outcomes_order_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_outcomes DROP CONSTRAINT product_outcomes_product_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_outcomes DROP CONSTRAINT product_outcomes_product_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_recommendations DROP CONSTRAINT product_recommendations_merchant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_recommendations DROP CONSTRAINT product_recommendations_merchant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_recommendations DROP CONSTRAINT product_recommendations_product_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_recommendations DROP CONSTRAINT product_recommendations_product_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE product_recommendations DROP CONSTRAINT product_recommendations_sharing_link_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE product_recommendations DROP CONSTRAINT product_recommendations_sharing_link_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE products DROP CONSTRAINT products_merchant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE products DROP CONSTRAINT products_merchant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE profiles DROP CONSTRAINT profiles_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE profiles DROP CONSTRAINT profiles_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE provider_account DROP CONSTRAINT provider_account_provider_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE provider_account DROP CONSTRAINT provider_account_provider_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE provisioning_job DROP CONSTRAINT provisioning_job_provider_account_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE provisioning_job DROP CONSTRAINT provisioning_job_provider_account_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE recommendation_commissions DROP CONSTRAINT recommendation_commissions_product_order_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE recommendation_commissions DROP CONSTRAINT recommendation_commissions_product_order_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE recommendation_commissions DROP CONSTRAINT recommendation_commissions_product_recommendation_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE recommendation_commissions DROP CONSTRAINT recommendation_commissions_product_recommendation_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE ai_conversations DROP CONSTRAINT ai_conversations_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE ai_conversations DROP CONSTRAINT ai_conversations_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE ai_memory DROP CONSTRAINT ai_memory_source_conversation_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE ai_memory DROP CONSTRAINT ai_memory_source_conversation_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE ai_recommendations DROP CONSTRAINT ai_recommendations_deployed_rule_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE ai_recommendations DROP CONSTRAINT ai_recommendations_deployed_rule_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE ai_recommendations DROP CONSTRAINT ai_recommendations_situation_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE ai_recommendations DROP CONSTRAINT ai_recommendations_situation_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE ai_recommendations DROP CONSTRAINT ai_recommendations_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE ai_recommendations DROP CONSTRAINT ai_recommendations_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE ai_situation_analyses DROP CONSTRAINT ai_situation_analyses_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE ai_situation_analyses DROP CONSTRAINT ai_situation_analyses_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE app_users DROP CONSTRAINT app_users_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE app_users DROP CONSTRAINT app_users_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE autopilot_actions DROP CONSTRAINT autopilot_actions_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE autopilot_actions DROP CONSTRAINT autopilot_actions_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE business_packages DROP CONSTRAINT business_packages_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE business_packages DROP CONSTRAINT business_packages_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_campaign_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE campaign_recipients DROP CONSTRAINT campaign_recipients_campaign_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE chat_group_members DROP CONSTRAINT chat_group_members_group_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE chat_group_members DROP CONSTRAINT chat_group_members_group_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE chat_messages DROP CONSTRAINT chat_messages_group_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE chat_messages DROP CONSTRAINT chat_messages_group_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE cj_orders DROP CONSTRAINT cj_orders_checkout_session_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE cj_orders DROP CONSTRAINT cj_orders_checkout_session_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE commission_event DROP CONSTRAINT commission_event_affiliate_program_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE commission_event DROP CONSTRAINT commission_event_affiliate_program_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listing_categories DROP CONSTRAINT community_listing_categories_parent_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listing_categories DROP CONSTRAINT community_listing_categories_parent_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listing_reports DROP CONSTRAINT community_listing_reports_listing_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listing_reports DROP CONSTRAINT community_listing_reports_listing_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listing_reports DROP CONSTRAINT community_listing_reports_reporter_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listing_reports DROP CONSTRAINT community_listing_reports_reporter_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listing_reports DROP CONSTRAINT community_listing_reports_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listing_reports DROP CONSTRAINT community_listing_reports_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listing_seller_blocks DROP CONSTRAINT community_listing_seller_blocks_blocked_seller_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listing_seller_blocks DROP CONSTRAINT community_listing_seller_blocks_blocked_seller_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listing_seller_blocks DROP CONSTRAINT community_listing_seller_blocks_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listing_seller_blocks DROP CONSTRAINT community_listing_seller_blocks_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listing_seller_blocks DROP CONSTRAINT community_listing_seller_blocks_viewer_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listing_seller_blocks DROP CONSTRAINT community_listing_seller_blocks_viewer_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listings DROP CONSTRAINT community_listings_merchant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listings DROP CONSTRAINT community_listings_merchant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listings DROP CONSTRAINT community_listings_seller_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listings DROP CONSTRAINT community_listings_seller_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_listings DROP CONSTRAINT community_listings_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_listings DROP CONSTRAINT community_listings_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE consents DROP CONSTRAINT consents_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE consents DROP CONSTRAINT consents_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE contradiction_flags DROP CONSTRAINT contradiction_flags_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE contradiction_flags DROP CONSTRAINT contradiction_flags_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE curated_memories DROP CONSTRAINT curated_memories_consent_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE curated_memories DROP CONSTRAINT curated_memories_consent_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE curated_memories DROP CONSTRAINT curated_memories_source_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE curated_memories DROP CONSTRAINT curated_memories_source_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE curated_memories DROP CONSTRAINT curated_memories_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE curated_memories DROP CONSTRAINT curated_memories_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE dev_autopilot_executions DROP CONSTRAINT dev_autopilot_executions_finding_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE dev_autopilot_executions DROP CONSTRAINT dev_autopilot_executions_finding_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE dev_autopilot_executions DROP CONSTRAINT dev_autopilot_executions_parent_execution_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE dev_autopilot_executions DROP CONSTRAINT dev_autopilot_executions_parent_execution_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE dev_autopilot_outcomes DROP CONSTRAINT dev_autopilot_outcomes_finding_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE dev_autopilot_outcomes DROP CONSTRAINT dev_autopilot_outcomes_finding_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE dev_autopilot_plan_versions DROP CONSTRAINT dev_autopilot_plan_versions_finding_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE dev_autopilot_plan_versions DROP CONSTRAINT dev_autopilot_plan_versions_finding_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE dev_autopilot_signals DROP CONSTRAINT dev_autopilot_signals_run_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE dev_autopilot_signals DROP CONSTRAINT dev_autopilot_signals_run_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE disclosure DROP CONSTRAINT disclosure_cart_order_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE disclosure DROP CONSTRAINT disclosure_cart_order_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE distribution_posts DROP CONSTRAINT distribution_posts_campaign_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE distribution_posts DROP CONSTRAINT distribution_posts_campaign_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE entity_relationships DROP CONSTRAINT entity_relationships_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE entity_relationships DROP CONSTRAINT entity_relationships_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE event_co_creators DROP CONSTRAINT event_co_creators_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE event_co_creators DROP CONSTRAINT event_co_creators_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE event_recommendations DROP CONSTRAINT event_recommendations_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE event_recommendations DROP CONSTRAINT event_recommendations_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE event_ticket_purchases DROP CONSTRAINT event_ticket_purchases_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE event_ticket_purchases DROP CONSTRAINT event_ticket_purchases_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE event_ticket_purchases DROP CONSTRAINT event_ticket_purchases_ticket_type_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE event_ticket_purchases DROP CONSTRAINT event_ticket_purchases_ticket_type_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE event_ticket_scans DROP CONSTRAINT event_ticket_scans_ticket_purchase_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE event_ticket_scans DROP CONSTRAINT event_ticket_scans_ticket_purchase_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE event_ticket_types DROP CONSTRAINT event_ticket_types_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE event_ticket_types DROP CONSTRAINT event_ticket_types_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE feature_entitlements DROP CONSTRAINT feature_entitlements_plan_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE feature_entitlements DROP CONSTRAINT feature_entitlements_plan_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE feedback_handoff_events DROP CONSTRAINT feedback_handoff_events_ticket_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE feedback_handoff_events DROP CONSTRAINT feedback_handoff_events_ticket_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE feedback_tickets DROP CONSTRAINT feedback_tickets_duplicate_of_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE feedback_tickets DROP CONSTRAINT feedback_tickets_duplicate_of_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE feedback_tickets DROP CONSTRAINT feedback_tickets_linked_finding_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE feedback_tickets DROP CONSTRAINT feedback_tickets_linked_finding_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE app_users DROP CONSTRAINT fk_app_users_live_room;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE app_users DROP CONSTRAINT fk_app_users_live_room;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_room_attendance DROP CONSTRAINT fk_attendance_session;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_room_attendance DROP CONSTRAINT fk_attendance_session;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE global_event_participants DROP CONSTRAINT fk_global_event_participants_event;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE global_event_participants DROP CONSTRAINT fk_global_event_participants_event;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE global_group_members DROP CONSTRAINT fk_global_group_members_group;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE global_group_members DROP CONSTRAINT fk_global_group_members_group;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE global_messages DROP CONSTRAINT fk_global_messages_thread;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE global_messages DROP CONSTRAINT fk_global_messages_thread;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE global_thread_participants DROP CONSTRAINT fk_global_thread_participants_thread;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE global_thread_participants DROP CONSTRAINT fk_global_thread_participants_thread;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_room_access_grants DROP CONSTRAINT fk_grants_session;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_room_access_grants DROP CONSTRAINT fk_grants_session;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_rooms DROP CONSTRAINT fk_live_rooms_current_session;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_rooms DROP CONSTRAINT fk_live_rooms_current_session;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE test_cycles DROP CONSTRAINT fk_test_cycles_last_run;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE test_cycles DROP CONSTRAINT fk_test_cycles_last_run;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE thread_participants DROP CONSTRAINT fk_thread_participants_thread_id;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE thread_participants DROP CONSTRAINT fk_thread_participants_thread_id;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE global_community_group_members DROP CONSTRAINT global_community_group_members_group_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE global_community_group_members DROP CONSTRAINT global_community_group_members_group_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE global_community_groups DROP CONSTRAINT global_community_groups_chat_thread_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE global_community_groups DROP CONSTRAINT global_community_groups_chat_thread_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE global_typing_indicators DROP CONSTRAINT global_typing_indicators_thread_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE global_typing_indicators DROP CONSTRAINT global_typing_indicators_thread_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE goal_plan_i18n DROP CONSTRAINT goal_plan_i18n_plan_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE goal_plan_i18n DROP CONSTRAINT goal_plan_i18n_plan_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE goal_plan_step_i18n DROP CONSTRAINT goal_plan_step_i18n_step_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE goal_plan_step_i18n DROP CONSTRAINT goal_plan_step_i18n_step_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE goal_plan_steps DROP CONSTRAINT goal_plan_steps_plan_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE goal_plan_steps DROP CONSTRAINT goal_plan_steps_plan_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE governance_enforcements DROP CONSTRAINT governance_enforcements_rule_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE governance_enforcements DROP CONSTRAINT governance_enforcements_rule_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE governance_evaluations DROP CONSTRAINT governance_evaluations_rule_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE governance_evaluations DROP CONSTRAINT governance_evaluations_rule_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE governance_rules DROP CONSTRAINT governance_rules_category_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE governance_rules DROP CONSTRAINT governance_rules_category_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE governance_violations DROP CONSTRAINT governance_violations_rule_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE governance_violations DROP CONSTRAINT governance_violations_rule_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE group_post_comments DROP CONSTRAINT group_post_comments_post_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE group_post_comments DROP CONSTRAINT group_post_comments_post_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE group_post_likes DROP CONSTRAINT group_post_likes_post_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE group_post_likes DROP CONSTRAINT group_post_likes_post_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE group_posts DROP CONSTRAINT group_posts_group_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE group_posts DROP CONSTRAINT group_posts_group_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE group_recommendations DROP CONSTRAINT group_recommendations_group_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE group_recommendations DROP CONSTRAINT group_recommendations_group_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE index_delta_observations DROP CONSTRAINT index_delta_observations_recommendation_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE index_delta_observations DROP CONSTRAINT index_delta_observations_recommendation_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_categories DROP CONSTRAINT intent_categories_kind_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_categories DROP CONSTRAINT intent_categories_kind_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_compass_boost DROP CONSTRAINT intent_compass_boost_intent_kind_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_compass_boost DROP CONSTRAINT intent_compass_boost_intent_kind_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_compatibility DROP CONSTRAINT intent_compatibility_kind_a_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_compatibility DROP CONSTRAINT intent_compatibility_kind_a_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_compatibility DROP CONSTRAINT intent_compatibility_kind_b_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_compatibility DROP CONSTRAINT intent_compatibility_kind_b_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_disputes DROP CONSTRAINT intent_disputes_match_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_disputes DROP CONSTRAINT intent_disputes_match_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_events DROP CONSTRAINT intent_events_intent_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_events DROP CONSTRAINT intent_events_intent_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_events DROP CONSTRAINT intent_events_match_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_events DROP CONSTRAINT intent_events_match_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_match_recommendations DROP CONSTRAINT intent_match_recommendations_intent_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_match_recommendations DROP CONSTRAINT intent_match_recommendations_intent_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_matches DROP CONSTRAINT intent_matches_intent_a_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_matches DROP CONSTRAINT intent_matches_intent_a_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_matches DROP CONSTRAINT intent_matches_intent_b_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_matches DROP CONSTRAINT intent_matches_intent_b_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE intent_supply_seeded DROP CONSTRAINT intent_supply_seeded_intent_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE intent_supply_seeded DROP CONSTRAINT intent_supply_seeded_intent_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE job_artifact DROP CONSTRAINT job_artifact_attempt_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE job_artifact DROP CONSTRAINT job_artifact_attempt_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE job_attempt DROP CONSTRAINT job_attempt_step_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE job_attempt DROP CONSTRAINT job_attempt_step_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE job_step DROP CONSTRAINT job_step_job_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE job_step DROP CONSTRAINT job_step_job_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE lab_test_orders DROP CONSTRAINT lab_test_orders_lab_test_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE lab_test_orders DROP CONSTRAINT lab_test_orders_lab_test_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE lab_test_results DROP CONSTRAINT lab_test_results_order_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE lab_test_results DROP CONSTRAINT lab_test_results_order_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE life_compass_subgoals DROP CONSTRAINT life_compass_subgoals_compass_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE life_compass_subgoals DROP CONSTRAINT life_compass_subgoals_compass_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE lifecycle_notification_state DROP CONSTRAINT lifecycle_notification_state_subscription_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE lifecycle_notification_state DROP CONSTRAINT lifecycle_notification_state_subscription_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE listing_status_history DROP CONSTRAINT listing_status_history_listing_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE listing_status_history DROP CONSTRAINT listing_status_history_listing_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_highlights DROP CONSTRAINT live_highlights_live_room_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_highlights DROP CONSTRAINT live_highlights_live_room_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_room_access_grants DROP CONSTRAINT live_room_access_grants_room_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_room_access_grants DROP CONSTRAINT live_room_access_grants_room_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_room_access_grants DROP CONSTRAINT live_room_access_grants_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_room_access_grants DROP CONSTRAINT live_room_access_grants_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_room_access_grants DROP CONSTRAINT live_room_access_grants_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_room_access_grants DROP CONSTRAINT live_room_access_grants_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_room_attendance DROP CONSTRAINT live_room_attendance_live_room_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_room_attendance DROP CONSTRAINT live_room_attendance_live_room_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_room_sessions DROP CONSTRAINT live_room_sessions_room_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_room_sessions DROP CONSTRAINT live_room_sessions_room_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE live_stream_subscribers DROP CONSTRAINT live_stream_subscribers_stream_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE live_stream_subscribers DROP CONSTRAINT live_stream_subscribers_stream_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE livekit_test_results DROP CONSTRAINT livekit_test_results_case_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE livekit_test_results DROP CONSTRAINT livekit_test_results_case_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE livekit_test_results DROP CONSTRAINT livekit_test_results_run_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE livekit_test_results DROP CONSTRAINT livekit_test_results_run_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE llm_allowed_models DROP CONSTRAINT llm_allowed_models_provider_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE llm_allowed_models DROP CONSTRAINT llm_allowed_models_provider_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE llm_routing_policy_audit DROP CONSTRAINT llm_routing_policy_audit_policy_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE llm_routing_policy_audit DROP CONSTRAINT llm_routing_policy_audit_policy_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE location_visits DROP CONSTRAINT location_visits_location_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE location_visits DROP CONSTRAINT location_visits_location_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE match_notifications DROP CONSTRAINT match_notifications_match_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE match_notifications DROP CONSTRAINT match_notifications_match_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE mcp_tool_executions DROP CONSTRAINT mcp_tool_executions_integration_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE mcp_tool_executions DROP CONSTRAINT mcp_tool_executions_integration_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE media_analytics DROP CONSTRAINT media_analytics_media_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE media_analytics DROP CONSTRAINT media_analytics_media_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE media_upload_comments DROP CONSTRAINT media_upload_comments_upload_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE media_upload_comments DROP CONSTRAINT media_upload_comments_upload_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE media_upload_likes DROP CONSTRAINT media_upload_likes_upload_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE media_upload_likes DROP CONSTRAINT media_upload_likes_upload_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE media_video_comment_likes DROP CONSTRAINT media_video_comment_likes_comment_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE media_video_comment_likes DROP CONSTRAINT media_video_comment_likes_comment_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE media_video_comments DROP CONSTRAINT media_video_comments_parent_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE media_video_comments DROP CONSTRAINT media_video_comments_parent_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE media_video_comments DROP CONSTRAINT media_video_comments_video_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE media_video_comments DROP CONSTRAINT media_video_comments_video_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE mem_episodes DROP CONSTRAINT mem_episodes_superseded_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE mem_episodes DROP CONSTRAINT mem_episodes_superseded_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE mem_facts DROP CONSTRAINT mem_facts_source_episode_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE mem_facts DROP CONSTRAINT mem_facts_source_episode_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE mem_facts DROP CONSTRAINT mem_facts_superseded_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE mem_facts DROP CONSTRAINT mem_facts_superseded_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE mem_graph_edges DROP CONSTRAINT mem_graph_edges_superseded_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE mem_graph_edges DROP CONSTRAINT mem_graph_edges_superseded_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memberships DROP CONSTRAINT memberships_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memberships DROP CONSTRAINT memberships_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memory_category_mapping DROP CONSTRAINT memory_category_mapping_garden_category_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memory_category_mapping DROP CONSTRAINT memory_category_mapping_garden_category_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memory_embeddings DROP CONSTRAINT memory_embeddings_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memory_embeddings DROP CONSTRAINT memory_embeddings_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memory_events DROP CONSTRAINT memory_events_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memory_events DROP CONSTRAINT memory_events_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memory_facts DROP CONSTRAINT memory_facts_superseded_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memory_facts DROP CONSTRAINT memory_facts_superseded_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memory_items DROP CONSTRAINT memory_items_category_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memory_items DROP CONSTRAINT memory_items_category_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memory_node_sources DROP CONSTRAINT memory_node_sources_diary_entry_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memory_node_sources DROP CONSTRAINT memory_node_sources_diary_entry_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE memory_node_sources DROP CONSTRAINT memory_node_sources_node_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE memory_node_sources DROP CONSTRAINT memory_node_sources_node_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE merchant_route DROP CONSTRAINT merchant_route_cart_order_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE merchant_route DROP CONSTRAINT merchant_route_cart_order_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE message_actions DROP CONSTRAINT message_actions_message_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE message_actions DROP CONSTRAINT message_actions_message_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE message_queue DROP CONSTRAINT message_queue_campaign_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE message_queue DROP CONSTRAINT message_queue_campaign_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE message_queue DROP CONSTRAINT message_queue_recipient_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE message_queue DROP CONSTRAINT message_queue_recipient_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE recommendation_deployments DROP CONSTRAINT recommendation_deployments_recommendation_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE recommendation_deployments DROP CONSTRAINT recommendation_deployments_recommendation_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE recommendation_deployments DROP CONSTRAINT recommendation_deployments_rule_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE recommendation_deployments DROP CONSTRAINT recommendation_deployments_rule_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE redemption_codes DROP CONSTRAINT redemption_codes_grants_plan_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE redemption_codes DROP CONSTRAINT redemption_codes_grants_plan_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE redemption_redemptions DROP CONSTRAINT redemption_redemptions_code_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE redemption_redemptions DROP CONSTRAINT redemption_redemptions_code_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE relationship_dates DROP CONSTRAINT relationship_dates_relationship_node_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE relationship_dates DROP CONSTRAINT relationship_dates_relationship_node_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE relationship_health_context DROP CONSTRAINT relationship_health_context_relationship_node_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE relationship_health_context DROP CONSTRAINT relationship_health_context_relationship_node_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE relationship_health_context DROP CONSTRAINT relationship_health_context_source_episode_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE relationship_health_context DROP CONSTRAINT relationship_health_context_source_episode_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE relationship_health_context DROP CONSTRAINT relationship_health_context_superseded_by_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE relationship_health_context DROP CONSTRAINT relationship_health_context_superseded_by_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_payout_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_payout_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_reseller_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_reseller_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_ticket_purchase_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE reseller_attributions DROP CONSTRAINT reseller_attributions_ticket_purchase_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE reseller_payouts DROP CONSTRAINT reseller_payouts_reseller_profile_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE reseller_payouts DROP CONSTRAINT reseller_payouts_reseller_profile_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE reseller_payouts DROP CONSTRAINT reseller_payouts_wallet_transaction_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE reseller_payouts DROP CONSTRAINT reseller_payouts_wallet_transaction_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE reseller_profiles DROP CONSTRAINT reseller_profiles_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE reseller_profiles DROP CONSTRAINT reseller_profiles_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE retrieval_traces DROP CONSTRAINT retrieval_traces_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE retrieval_traces DROP CONSTRAINT retrieval_traces_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE rewards_ledger DROP CONSTRAINT rewards_ledger_commission_event_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE rewards_ledger DROP CONSTRAINT rewards_ledger_commission_event_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE role_preferences DROP CONSTRAINT role_preferences_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE role_preferences DROP CONSTRAINT role_preferences_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE role_sessions DROP CONSTRAINT role_sessions_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE role_sessions DROP CONSTRAINT role_sessions_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE routine_runs DROP CONSTRAINT routine_runs_routine_name_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE routine_runs DROP CONSTRAINT routine_runs_routine_name_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE typing_indicators DROP CONSTRAINT typing_indicators_thread_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE typing_indicators DROP CONSTRAINT typing_indicators_thread_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE universal_cart_events DROP CONSTRAINT universal_cart_events_cart_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE universal_cart_events DROP CONSTRAINT universal_cart_events_cart_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE universal_cart_items DROP CONSTRAINT universal_cart_items_cart_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE universal_cart_items DROP CONSTRAINT universal_cart_items_cart_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE universal_cart_items DROP CONSTRAINT universal_cart_items_merchant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE universal_cart_items DROP CONSTRAINT universal_cart_items_merchant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE universal_cart_items DROP CONSTRAINT universal_cart_items_product_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE universal_cart_items DROP CONSTRAINT universal_cart_items_product_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE universal_carts DROP CONSTRAINT universal_carts_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE universal_carts DROP CONSTRAINT universal_carts_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_capability_awareness DROP CONSTRAINT user_capability_awareness_capability_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_capability_awareness DROP CONSTRAINT user_capability_awareness_capability_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_category_preferences DROP CONSTRAINT user_category_preferences_category_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_category_preferences DROP CONSTRAINT user_category_preferences_category_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_connections DROP CONSTRAINT user_connections_connector_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_connections DROP CONSTRAINT user_connections_connector_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_device_session_log DROP CONSTRAINT user_device_session_log_device_token_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_device_session_log DROP CONSTRAINT user_device_session_log_device_token_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_feedback_reports DROP CONSTRAINT user_feedback_reports_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_feedback_reports DROP CONSTRAINT user_feedback_reports_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_intents DROP CONSTRAINT user_intents_intent_kind_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_intents DROP CONSTRAINT user_intents_intent_kind_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_limitations DROP CONSTRAINT user_limitations_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_limitations DROP CONSTRAINT user_limitations_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_location_history DROP CONSTRAINT user_location_history_named_place_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_location_history DROP CONSTRAINT user_location_history_named_place_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_ratings DROP CONSTRAINT user_ratings_match_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_ratings DROP CONSTRAINT user_ratings_match_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_roles DROP CONSTRAINT user_roles_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_roles DROP CONSTRAINT user_roles_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_subscriptions DROP CONSTRAINT user_subscriptions_plan_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_subscriptions DROP CONSTRAINT user_subscriptions_plan_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_subscriptions DROP CONSTRAINT user_subscriptions_price_key_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_subscriptions DROP CONSTRAINT user_subscriptions_price_key_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_tenants DROP CONSTRAINT user_tenants_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_tenants DROP CONSTRAINT user_tenants_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE user_tenants DROP CONSTRAINT user_tenants_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE user_tenants DROP CONSTRAINT user_tenants_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE vaea_detected_questions DROP CONSTRAINT vaea_detected_questions_channel_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE vaea_detected_questions DROP CONSTRAINT vaea_detected_questions_channel_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE vaea_reply_drafts DROP CONSTRAINT vaea_reply_drafts_catalog_item_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE vaea_reply_drafts DROP CONSTRAINT vaea_reply_drafts_catalog_item_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE vaea_reply_drafts DROP CONSTRAINT vaea_reply_drafts_detected_question_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE vaea_reply_drafts DROP CONSTRAINT vaea_reply_drafts_detected_question_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE video_metadata DROP CONSTRAINT video_metadata_media_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE video_metadata DROP CONSTRAINT video_metadata_media_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE voucher_orders DROP CONSTRAINT voucher_orders_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE voucher_orders DROP CONSTRAINT voucher_orders_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE voucher_orders DROP CONSTRAINT voucher_orders_voucher_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE voucher_orders DROP CONSTRAINT voucher_orders_voucher_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE voucher_redemptions DROP CONSTRAINT voucher_redemptions_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE voucher_redemptions DROP CONSTRAINT voucher_redemptions_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE voucher_redemptions DROP CONSTRAINT voucher_redemptions_voucher_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE voucher_redemptions DROP CONSTRAINT voucher_redemptions_voucher_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE vouchers DROP CONSTRAINT vouchers_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE vouchers DROP CONSTRAINT vouchers_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wallet_credits DROP CONSTRAINT wallet_credits_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wallet_credits DROP CONSTRAINT wallet_credits_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wallet_deposits DROP CONSTRAINT wallet_deposits_account_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wallet_deposits DROP CONSTRAINT wallet_deposits_account_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wallet_ledger_entries DROP CONSTRAINT wallet_ledger_entries_account_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wallet_ledger_entries DROP CONSTRAINT wallet_ledger_entries_account_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wallet_transactions DROP CONSTRAINT wallet_transactions_from_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wallet_transactions DROP CONSTRAINT wallet_transactions_from_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wallet_transactions DROP CONSTRAINT wallet_transactions_to_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wallet_transactions DROP CONSTRAINT wallet_transactions_to_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wearable_daily_metrics DROP CONSTRAINT wearable_daily_metrics_user_connection_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wearable_daily_metrics DROP CONSTRAINT wearable_daily_metrics_user_connection_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wearable_waitlist DROP CONSTRAINT wearable_waitlist_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wearable_waitlist DROP CONSTRAINT wearable_waitlist_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE wearable_workouts DROP CONSTRAINT wearable_workouts_user_connection_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE wearable_workouts DROP CONSTRAINT wearable_workouts_user_connection_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_marketplace_seller_suspensions DROP CONSTRAINT community_marketplace_seller_suspensions_seller_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_marketplace_seller_suspensions DROP CONSTRAINT community_marketplace_seller_suspensions_seller_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE community_marketplace_seller_suspensions DROP CONSTRAINT community_marketplace_seller_suspensions_tenant_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE community_marketplace_seller_suspensions DROP CONSTRAINT community_marketplace_seller_suspensions_tenant_id_fkey;" >> /tmp/fk_drop_errors.log; fi
if run_sql 'ALTER TABLE orb_session_state DROP CONSTRAINT orb_session_state_user_id_fkey;' > /dev/null 2>>/tmp/fk_drop_errors.log; then ok=$((ok+1)); else fail=$((fail+1)); echo "FAILED: ALTER TABLE orb_session_state DROP CONSTRAINT orb_session_state_user_id_fkey;" >> /tmp/fk_drop_errors.log; fi

echo "FK drops: $ok ok, $fail failed"
if [ "$fail" -gt 0 ]; then
  echo "See /tmp/fk_drop_errors.log for details. Continuing anyway -- some may already be gone from a partial earlier attempt."
fi
echo

echo "=== Step 2: Creating the 'authenticator' role for PostgREST ==="
AUTH_PW=$(openssl rand -base64 32 | tr -d '=+/' | head -c 40)
if [ -z "$AUTH_PW" ] || [ "${#AUTH_PW}" -lt 20 ]; then
  echo "ERROR: generated password looks empty/too short. Aborting before touching any role." >&2
  exit 1
fi

run_sql "CREATE ROLE authenticator WITH LOGIN NOINHERIT PASSWORD '$AUTH_PW';" || \
  echo "(role may already exist -- continuing to GRANT)"
run_sql "GRANT anon, authenticated, service_role TO authenticator;"
echo "authenticator role created and granted anon/authenticated/service_role."
echo

echo "=== Step 3: Storing the authenticator connection string in Secrets Manager ==="
DB_URI="postgres://authenticator:${AUTH_PW}@vitana-aurora-prod.cluster-cfk228aiedf3.eu-central-1.rds.amazonaws.com:5432/vitana"
aws secretsmanager create-secret --region "$REGION" \
  --name "vitana/aurora/prod/postgrest-authenticator-uri" \
  --description "PostgREST's DB connection role for the Aurora-staging build (VTID-03619). Login role authenticator, member of anon/authenticated/service_role." \
  --secret-string "$DB_URI" \
  --query 'ARN' --output text
unset AUTH_PW DB_URI

echo
echo "=== Step 4: Restarting the DMS reload ==="
TASK_ARN="arn:aws:dms:eu-central-1:472838866351:task:6HXJWOLRF5FA3DND3TLMGXHY4I"
aws dms start-replication-task --region "$REGION" \
  --replication-task-arn "$TASK_ARN" \
  --start-replication-task-type reload-target \
  --query 'ReplicationTask.Status' --output text

echo
echo "=== Done ==="
echo "FK constraints dropped (restorable via aurora-fk-restore-2026-08-12.sql)."
echo "authenticator role created; its secret ARN is vitana/aurora/prod/postgrest-authenticator-uri."
echo "DMS reload restarted -- Claude's session will pick up progress from here."
