-- BOOTSTRAP-NAV-DESKTOP-TABS: per-page tab/section deep-links for Desktop MAXINA.
-- Generated by services/gateway/scripts/gen-desktop-nav-seed.ts from the desktop
-- web app inventory (vitana-v1/src/App.tsx + page components). Each entry reuses
-- the screen’s category/access/i18n and overrides the route with the real desktop
-- path, scoped to platform='desktop'. Tabs included here are ONLY the ones that are
-- actually URL-addressable on desktop (state-only <SplitBar> tabs are excluded).
--
-- impact-allow-solo-migration: pure data seed into the existing nav_catalog /
-- nav_catalog_i18n tables (the runtime already reads them). Additive + idempotent.
-- 22 desktop tab deep-links.
BEGIN;

-- COMM.EVENTS_HOT
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.EVENTS_HOT', NULL, 'desktop', '/comm/events-meetups?tab=hot', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Hot Events', 'Featured and trending Maxina community events and meetups.', 'When the user asks for the Hot tab of Events & Meetups, hot events, trending events, featured events, or the highlighted community events.'),
    ('de', 'Angesagte Events', 'Hervorgehobene und angesagte Maxina-Community-Events und Meetups.', 'Wenn der Nutzer nach dem Tab „Hot“ von Events & Meetups, angesagten Events, Trend-Events, hervorgehobenen Events oder den Top-Community-Events fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.EVENTS_UPCOMING
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.EVENTS_UPCOMING', NULL, 'desktop', '/comm/events-meetups?tab=upcoming', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Upcoming Events', 'Upcoming community events and meetups you can attend.', 'When the user asks for upcoming events, the upcoming tab, what events are coming up, or future events and meetups in Events & Meetups.'),
    ('de', 'Kommende Veranstaltungen', 'Kommende Community-Events und Meetups, an denen du teilnehmen kannst.', 'Wenn der Nutzer nach kommenden Veranstaltungen, anstehenden Events, dem Tab "Kommend" oder zukünftigen Events und Meetups fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.EVENTS_TODAY
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.EVENTS_TODAY', NULL, 'desktop', '/comm/events-meetups?tab=today', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Today''s Events', 'Community events and meetups happening today.', 'When the user asks what events are happening today, today''s events, or the today tab in Events & Meetups.'),
    ('de', 'Heutige Veranstaltungen', 'Community-Events und Meetups, die heute stattfinden.', 'Wenn der Nutzer fragt, welche Events heute stattfinden, nach heutigen Veranstaltungen oder dem Tab "Heute".')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.FEED
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.FEED', NULL, 'desktop', '/comm/events-meetups?tab=following', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Following Community Feed', 'The Following tab of Events & Meetups — your community feed of events, posts, and updates from the members and groups you follow (Following).', 'When the user asks for the Following tab of Events & Meetups, following, following events, events from people they follow, the people or groups they follow, or to open the community feed and see community posts and updates.'),
    ('de', 'Following Community-Feed', 'Der „Folge ich"-Tab von Events & Meetups — dein Community-Feed mit Events, Posts und Updates von Mitgliedern und Gruppen, denen du folgst (Following).', 'Wenn der Nutzer nach dem „Folge ich"-Tab von Events & Meetups, nach Following, nach Events von Personen, denen er folgt, nach den Personen oder Gruppen, denen er folgt, oder nach dem Community-Feed mit Community-Posts und Updates fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.LIVE_ROOMS_ALL
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.LIVE_ROOMS_ALL', NULL, 'desktop', '/comm/live-rooms?tab=all', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'All Rooms', 'All Live Rooms — live now and scheduled — in one list.', 'When the user asks for the All Rooms tab of Live Rooms, or to see all live rooms (both live and scheduled) together.'),
    ('de', 'Alle Räume', 'Alle Live-Räume — jetzt live und geplant — in einer Liste.', 'Wenn der Nutzer nach dem Tab „Alle Räume“ der Live-Räume fragt oder alle Live-Räume (live und geplant) zusammen sehen möchte.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.LIVE_ROOMS_LIVE
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.LIVE_ROOMS_LIVE', NULL, 'desktop', '/comm/live-rooms?tab=live', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Live Now', 'Live Rooms that are streaming right now.', 'When the user asks for the Live Now tab of Live Rooms — rooms that are live right now, currently streaming, or happening this moment.'),
    ('de', 'Jetzt live', 'Live-Räume, die gerade jetzt streamen.', 'Wenn der Nutzer nach dem Tab „Jetzt live“ der Live-Räume fragt — Räume, die gerade live sind, aktuell streamen oder genau jetzt stattfinden.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.LIVE_ROOMS_SCHEDULED
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.LIVE_ROOMS_SCHEDULED', NULL, 'desktop', '/comm/live-rooms?tab=scheduled', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Scheduled Rooms', 'Upcoming Live Rooms scheduled for later.', 'When the user asks for the Scheduled tab of Live Rooms — upcoming rooms, scheduled sessions, or live rooms planned for later.'),
    ('de', 'Geplante Räume', 'Kommende Live-Räume, die für später geplant sind.', 'Wenn der Nutzer nach dem Tab „Geplant“ der Live-Räume fragt — kommende Räume, geplante Sitzungen oder für später geplante Live-Räume.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.LIVE_ROOMS_PAST
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.LIVE_ROOMS_PAST', NULL, 'desktop', '/comm/live-rooms?tab=past', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Past Sessions', 'Recordings and summaries from completed Live Rooms.', 'When the user asks for the Past tab of Live Rooms — past sessions, previous rooms, recordings, or summaries of completed live rooms.'),
    ('de', 'Vergangene Sitzungen', 'Aufzeichnungen und Zusammenfassungen abgeschlossener Live-Räume.', 'Wenn der Nutzer nach dem Tab „Vergangen“ der Live-Räume fragt — vergangene Sitzungen, frühere Räume, Aufzeichnungen oder Zusammenfassungen abgeschlossener Live-Räume.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.MEDIA_SHORTS
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.MEDIA_SHORTS', NULL, 'desktop', '/comm/media-hub?tab=shorts', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Shorts', 'Short community videos — the Shorts feed.', 'When the user asks for shorts, short videos, the shorts feed, or reels in the Media Hub.'),
    ('de', 'Shorts', 'Kurze Community-Videos — der Shorts-Feed.', 'Wenn der Nutzer nach Shorts, kurzen Videos, dem Shorts-Feed oder Reels im Media Hub fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.MEDIA_MUSIC
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.MEDIA_MUSIC', NULL, 'desktop', '/comm/media-hub?tab=music', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Music', 'Music shared by the community.', 'When the user asks for music, songs, or tracks in the Media Hub.'),
    ('de', 'Musik', 'Musik der Community.', 'Wenn der Nutzer nach Musik, Liedern oder Tracks im Media Hub fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- COMM.MEDIA_PODCASTS
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('COMM.MEDIA_PODCASTS', NULL, 'desktop', '/comm/media-hub?tab=podcasts', 'community', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Podcasts', 'Podcasts and audio episodes shared by the community.', 'When the user asks for podcasts, the podcasts tab, or audio episodes in the Media Hub.'),
    ('de', 'Podcasts', 'Podcasts und Audiofolgen der Community.', 'Wenn der Nutzer nach Podcasts, dem Podcast-Tab oder Audiofolgen im Media Hub fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- DISCOVER.CATEGORIES
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('DISCOVER.CATEGORIES', NULL, 'desktop', '/discover?tab=categories', 'discover', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Categories', 'Browse Discover by category.', 'When the user asks for the Categories tab of Discover, to browse Discover by category, or to see all the marketplace categories.'),
    ('de', 'Kategorien', 'Durchstöbere Discover nach Kategorie.', 'Wenn der Nutzer nach dem Kategorien-Tab von Discover fragt, Discover nach Kategorie durchstöbern oder alle Marktplatz-Kategorien sehen möchte.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- DISCOVER.SHARE_EARN
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('DISCOVER.SHARE_EARN', NULL, 'desktop', '/discover?tab=share', 'discover', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Share & Earn', 'Share Discover products and earn rewards.', 'When the user asks for the Share and Earn tab of Discover, the Discover Share and Earn section, or sharing Discover marketplace products to earn rewards.'),
    ('de', 'Teilen & Verdienen', 'Teile Discover-Produkte und verdiene Belohnungen.', 'Wenn der Nutzer nach dem Tab "Teilen & Verdienen" von Discover, dem Discover Share and Earn Bereich oder dem Teilen von Discover-Marktplatzprodukten fragt, um Belohnungen zu verdienen.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- DISCOVER.MARKETPLACE_OPEN
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('DISCOVER.MARKETPLACE_OPEN', NULL, 'desktop', '/discover/marketplace?view=open', 'discover', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Open Requests', 'The Open view of the marketplace — requests and offers open to everyone.', 'When the user asks for the Open tab of the marketplace, open marketplace requests, or offers open to all.'),
    ('de', 'Offene Anfragen', 'Die Ansicht „Offen“ des Marktplatzes — Anfragen und Angebote, die allen offenstehen.', 'Wenn der Nutzer nach dem Tab „Offen“ des Marktplatzes, offenen Marktplatz-Anfragen oder allgemein offenen Angeboten fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- DISCOVER.MARKETPLACE_MINE
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('DISCOVER.MARKETPLACE_MINE', NULL, 'desktop', '/discover/marketplace?view=mine', 'discover', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'My Marketplace', 'The Mine view of the marketplace — your own requests, offers and listings.', 'When the user asks for the Mine tab of the marketplace, their own marketplace requests, offers, or listings.'),
    ('de', 'Mein Marktplatz', 'Die Ansicht „Meine“ des Marktplatzes — deine eigenen Anfragen, Angebote und Inserate.', 'Wenn der Nutzer nach dem Tab „Meine“ des Marktplatzes, seinen eigenen Marktplatz-Anfragen, Angeboten oder Inseraten fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- HOME.NEWS_ALL
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('HOME.NEWS_ALL', NULL, 'desktop', '/home?tab=all', 'home', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'All News', 'The News feed with all sources — longevity and community news combined.', 'When the user asks for the All News tab, all news, every news source, or both longevity and community news together in one feed.'),
    ('de', 'Alle News', 'Der News-Feed mit allen Quellen — Longevity- und Community-News zusammen.', 'Wenn der Nutzer den Tab „Alle News“, alle Nachrichten, jede Nachrichtenquelle oder Longevity- und Community-News zusammen in einem Feed möchte.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- HOME.NEWS_COMMUNITY
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('HOME.NEWS_COMMUNITY', NULL, 'desktop', '/home?tab=community', 'home', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Community News', 'The Community tab of the News feed — updates and posts from the Maxina community.', 'When the user asks for the Community tab of the news feed, community news, community updates, or what is happening in the community feed.'),
    ('de', 'Community-News', 'Der Community-Tab des News-Feeds — Updates und Beiträge aus der Maxina-Community.', 'Wenn der Nutzer den Community-Tab des News-Feeds, Community-Nachrichten, Community-Updates oder Neuigkeiten aus dem Community-Feed möchte.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- ASSISTANT.VOICE
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('ASSISTANT.VOICE', NULL, 'desktop', '/assistant?tab=voice', 'ai', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Voice', 'The Voice tab of the AI Assistant — voice settings and your voice-first ORB experience.', 'When the user asks for the Voice tab of the Assistant, voice settings, voice AI, or to configure the voice assistant.'),
    ('de', 'Stimme', 'Der Voice-Tab des KI-Assistenten — Spracheinstellungen und dein Voice-First-ORB-Erlebnis.', 'Wenn der Nutzer nach dem Voice-Tab des Assistenten, Spracheinstellungen, Voice-KI fragt oder den Sprachassistenten konfigurieren möchte.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- ASSISTANT.AI
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('ASSISTANT.AI', NULL, 'desktop', '/assistant?tab=ai', 'ai', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'AI', 'The AI tab of the Assistant — your text AI assistant and its settings.', 'When the user asks for the AI tab of the Assistant, the text assistant, or AI assistant settings.'),
    ('de', 'KI', 'Der KI-Tab des Assistenten — dein Text-KI-Assistent und seine Einstellungen.', 'Wenn der Nutzer nach dem KI-Tab des Assistenten, dem Text-Assistenten oder den KI-Assistenten-Einstellungen fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- ASSISTANT.AUTOPILOT
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('ASSISTANT.AUTOPILOT', NULL, 'desktop', '/assistant?tab=autopilot', 'ai', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Autopilot & Automation', 'The Autopilot tab of the Assistant — automations Vitana runs on your behalf.', 'When the user asks for the Autopilot tab of the Assistant, automation settings, or what Vitana automates for them.'),
    ('de', 'Autopilot & Automatisierung', 'Der Autopilot-Tab des Assistenten — Automatisierungen, die Vitana für dich ausführt.', 'Wenn der Nutzer nach dem Autopilot-Tab des Assistenten, Automatisierungseinstellungen oder dem fragt, was Vitana für ihn automatisiert.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- ASSISTANT.PROACTIVE
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('ASSISTANT.PROACTIVE', NULL, 'desktop', '/assistant?tab=proactive', 'ai', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Proactive Talking', 'The Proactive tab of the Assistant — control when Vitana speaks up unprompted.', 'When the user asks for the Proactive tab of the Assistant, proactive talking, or when Vitana should reach out unprompted.'),
    ('de', 'Proaktives Sprechen', 'Der Proaktiv-Tab des Assistenten — steuere, wann Vitana von sich aus spricht.', 'Wenn der Nutzer nach dem Proaktiv-Tab des Assistenten, proaktivem Sprechen oder dem fragt, wann Vitana sich von selbst melden soll.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

-- ASSISTANT.REFERRALS
WITH up AS (
  INSERT INTO nav_catalog (screen_id, tenant_id, platform, route, category, access, anonymous_safe, priority, related_kb_topics, is_active)
  VALUES ('ASSISTANT.REFERRALS', NULL, 'desktop', '/assistant?tab=referrals', 'ai', 'authenticated', FALSE, 0, '[]'::jsonb, TRUE)
  ON CONFLICT (screen_id, platform) WHERE tenant_id IS NULL
  DO UPDATE SET updated_at = now()
  RETURNING id
)
INSERT INTO nav_catalog_i18n (catalog_id, lang, title, description, when_to_visit)
SELECT up.id, v.lang, v.title, v.description, v.wtv
FROM up CROSS JOIN (VALUES
    ('en', 'Referrals', 'The Referrals tab of the Assistant — referrals and rewards from the assistant.', 'When the user asks for the Referrals tab of the Assistant, assistant referrals, or referral rewards in the Assistant.'),
    ('de', 'Empfehlungen', 'Der Empfehlungen-Tab des Assistenten — Empfehlungen und Belohnungen aus dem Assistenten.', 'Wenn der Nutzer nach dem Empfehlungen-Tab des Assistenten, Assistenten-Empfehlungen oder Empfehlungsbelohnungen im Assistenten fragt.')
) AS v(lang, title, description, wtv)
ON CONFLICT (catalog_id, lang) DO UPDATE SET title = EXCLUDED.title, description = EXCLUDED.description, when_to_visit = EXCLUDED.when_to_visit;

COMMIT;
