-- VTID-04333: auto-triage moves bug AND ux_issue tickets of EVERY priority to
-- spec_ready (with the placeholder spec the gateway drafter replaces).
--
-- Before: auto_triage_pending_feedback_tickets() (last defined in
-- 20260604123000_support_surface_human_only_queue.sql) moved only p3 bugs to
-- spec_ready. Every p1/p2 bug and every ux_issue waited in `triaged` for a
-- human who never came (brief docs/CUSTOMER-SUPPORT-REBUILD-BRIEF.md §2.4:
-- 43 tickets stuck since May).
--
-- After: the bug branch covers kind IN ('bug','ux_issue') with no priority
-- filter. The spec it writes is still a PLACEHOLDER — the first line keeps
-- "(placeholder)" so isPlaceholderSpec() (services/gateway/src/services/
-- feedback-spec-drafter.ts) matches it, the bridge refuses to dispatch it, and
-- the gateway's spec drafter (VTID-04311) replaces it with a real Devon draft
-- through the `triage` routing stage. Only a real spec can then be
-- dispatched (by a supervisor, or by FEEDBACK_AUTO_DISPATCH_ENABLED,
-- VTID-04333).
--
-- Everything else in the function is unchanged: the support_question and
-- account_issue branches, the 5-minute triaged_at delay, the duplicate and
-- classifier_meta guards, and the human-only surface='support' exclusion
-- (20260604123000).

CREATE OR REPLACE FUNCTION public.auto_triage_pending_feedback_tickets()
RETURNS TABLE (
  auto_drafted_answers INT,
  auto_drafted_specs INT,
  auto_drafted_resolutions INT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_answers INT := 0;
  v_specs INT := 0;
  v_resolutions INT := 0;
  r RECORD;
BEGIN
  FOR r IN
    SELECT id, kind, priority, classifier_meta, raw_transcript, structured_fields
      FROM public.feedback_tickets
     WHERE status = 'triaged'
       AND triaged_at < NOW() - INTERVAL '5 minutes'
       AND duplicate_of IS NULL
       AND classifier_meta IS NOT NULL
       -- Human-only queue: never auto-draft/auto-assign support tickets.
       AND COALESCE(surface, '') <> 'support'
     ORDER BY triaged_at
     LIMIT 100
  LOOP
    -- support_question → Sage drafts answer if confidence high enough
    IF r.kind = 'support_question'
       AND COALESCE((r.classifier_meta->>'pick_confidence')::REAL, 0) >= 0.5 THEN
      UPDATE public.feedback_tickets
         SET status = 'answer_ready',
             resolver_agent = 'sage',
             draft_answer_md = '**Sage auto-draft (placeholder)**' || chr(10) || chr(10) ||
                              '_Generated by auto_triage routine. LLM-backed retrieval lands in resolver-agents follow-up._' || chr(10) || chr(10) ||
                              'User asked: ' || COALESCE(r.raw_transcript, '(no transcript)')
       WHERE id = r.id;
      v_answers := v_answers + 1;

    -- VTID-04333: bug / ux_issue of every priority → Devon placeholder spec.
    -- The gateway spec drafter replaces it with a real draft; the placeholder
    -- itself is never dispatched.
    ELSIF r.kind IN ('bug', 'ux_issue') THEN
      UPDATE public.feedback_tickets
         SET status = 'spec_ready',
             resolver_agent = 'devon',
             spec_md = '# Devon auto-draft spec (placeholder)' || chr(10) ||
                      '## User report' || chr(10) || COALESCE(r.raw_transcript, '(no transcript)') || chr(10) || chr(10) ||
                      '## Root cause hypothesis' || chr(10) || 'TBD' || chr(10) || chr(10) ||
                      '## Risk + rollback' || chr(10) || 'Priority ' || COALESCE(r.priority, 'unset') || ' ' || r.kind || ' ticket; the real spec is drafted by the gateway spec drafter.' || chr(10) || chr(10) ||
                      '_Generated by auto_triage routine._'
       WHERE id = r.id;
      v_specs := v_specs + 1;

    -- account_issue with low-risk keywords → Mira drafts resolution
    ELSIF r.kind = 'account_issue'
       AND COALESCE(r.raw_transcript, '') ~* '(password|email|verification|verify)' THEN
      UPDATE public.feedback_tickets
         SET status = 'spec_ready',
             resolver_agent = 'mira',
             resolution_md = '# Mira auto-draft resolution (placeholder)' || chr(10) ||
                            '## User report' || chr(10) || COALESCE(r.raw_transcript, '(no transcript)') || chr(10) || chr(10) ||
                            '## Proposed action' || chr(10) || 'Trigger password reset or resend verification email.' || chr(10) || chr(10) ||
                            '## Risk' || chr(10) || 'Low — runbook covered.' || chr(10) || chr(10) ||
                            '_Generated by auto_triage routine. Supervisor approves before action._'
       WHERE id = r.id;
      v_resolutions := v_resolutions + 1;
    END IF;
  END LOOP;

  RETURN QUERY SELECT v_answers, v_specs, v_resolutions;
END;
$$;

GRANT EXECUTE ON FUNCTION public.auto_triage_pending_feedback_tickets() TO service_role;
