-- VTID-02000 (Discover marketplace) — DoctorBox home-test catalog seed.
--
-- DoctorBox (home health tests — nutrients/vitamins, hormones, cardio,
-- longevity & fitness, women's health, sexual health, prevention, general
-- health, DNA analyses) is onboarded as a Shopify Collabs personal-referral
-- merchant, not an automated-sync network: no bulk product feed or network
-- API exists (confirmed: shop.doctorbox.de and www.doctorbox.de both block
-- automated fetching with 403, same bot-protection Bodylab24 hit). Same
-- pattern as Bodylab24 (see 20260629120000_..._discover_admitad_real_catalog.sql,
-- 20260709120000_..._bodylab24_real_deeplinks_admitad_cleanup.sql): hand-seeded
-- via a one-time SQL migration, product data gathered by manually browsing the
-- live storefront by category.
--
-- Affiliate link: single storefront-level referral link for all 53 products,
-- https://shop.doctorbox.de/VITANALAND (15% commission, confirmed active in
-- Shopify Collabs). Per-product deep-linking IS supported by Shopify Collabs
-- (tested: https://collabs.shop/qezwvt), but individually copying 53 tracked
-- links isn't practical for the initial seed — same one-link-for-the-whole-
-- catalog tradeoff Bodylab24 launched with. A handful of flagship products
-- can be upgraded to individual tracked links in a follow-up migration later.
--
-- No gateway/frontend code change required: /r/:product_id (click-redirect)
-- already 302s any non-'demo_seed' product to its stamped affiliate_url;
-- discover-feed.ts + feed-ranker already read products. Images are Unsplash
-- placeholders (DoctorBox's own product photography wasn't captured — cards
-- reuse generic category-tinted box renders) — same placeholder-then-real-
-- photos pattern as Bodylab24/Amazon.ae's initial seeds.
--
-- Not fabricated: rating/review_count are left NULL (no real DoctorBox
-- ratings were available to transcribe — no fabricated stars/review counts).
--
-- impact-allow-solo-migration: intentional data-only migration. Seeds catalog
-- rows fully consumed by EXISTING code — no gateway/worker code touch needed.

BEGIN;

-- 1) DoctorBox merchant (fixed UUID for idempotency + clean rollback)
INSERT INTO merchants (
  id, name, source_network, currencies, is_active, requires_admin_review,
  storefront_url, commission_rate, merchant_country, ships_to_countries, ships_to_regions
) VALUES (
  'd0c706b0-0000-4000-8000-000000000001', 'DoctorBox', 'doctorbox', ARRAY['EUR']::text[], true, false,
  'https://shop.doctorbox.de', 0.15, 'DE',
  ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[],
  ARRAY['EU','UK']::text[]
)
ON CONFLICT (id) DO UPDATE
  SET name = EXCLUDED.name, source_network = EXCLUDED.source_network,
      currencies = EXCLUDED.currencies, is_active = true,
      storefront_url = EXCLUDED.storefront_url, commission_rate = EXCLUDED.commission_rate,
      merchant_country = EXCLUDED.merchant_country, ships_to_countries = EXCLUDED.ships_to_countries,
      ships_to_regions = EXCLUDED.ships_to_regions, updated_at = now();

-- 2) Full DoctorBox catalog: 53 products across 9 categories, gathered by
--    manually browsing shop.doctorbox.de (automated fetch blocked, 403).
INSERT INTO products (
  id, merchant_id, source_network, source_product_id, title, description, description_long,
  brand, category, subcategory, price_cents, compare_at_price_cents, currency, images,
  affiliate_url, availability, rating, review_count, origin_country, origin_region,
  ships_to_countries, ships_to_regions, health_goals, dietary_tags, ingredients_primary,
  topic_keys, reward_preview, is_active, requires_admin_review
) VALUES
  ('d0c70000-0000-4000-8000-000000000001', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-nutrient-check-premium', 'Nutrient Check Premium',
   'Analysiert wichtige Vitamine, Mineralstoffe und Eisenwerte für einen klaren Überblick über deine Nährstoffversorgung und Vitalstoffbalance.',
   'Der Nährstoff Check Premium analysiert wichtige Vitamine, Mineralstoffe und Eisenwerte und gibt dir einen klaren Überblick über deine Nährstoffversorgung und Vitalstoffbalance. 7 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'nutrients-vitamins', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615485500834-bc10199bc727?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['nutrient-supply','energy']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','nutrients','vitamins','minerals','iron']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000002', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-fitness-check-pro', 'Fitness Check Pro',
   'Ganzheitlicher Überblick über Leistungsfähigkeit, Regeneration und Muskelgesundheit. Ideal bei sportlicher Belastung, Trainingszielen oder Erschöpfung.',
   'Mit dem Fitness Check Pro erhältst du einen ganzheitlichen Überblick über Leistungsfähigkeit, Regeneration und Muskelgesundheit. Ideal bei sportlicher Belastung, Trainingszielen oder Erschöpfung. 11 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'longevity-fitness', 13900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['fitness-performance','muscle-recovery']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','fitness','performance','recovery','muscle']::text[],
   '{"points_estimate": 695, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000003', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-vitamin-all-round-check', 'Vitamin All-round Check',
   'Überprüft deine Versorgung mit wichtigen Vitaminen und zeigt, wie gut Energie, Nervenfunktion und Immunsystem unterstützt werden.',
   'Der Vitamin Rundum Check überprüft deine Versorgung mit wichtigen Vitaminen und zeigt, wie gut Energie, Nervenfunktion und Immunsystem unterstützt werden. 4 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'nutrients-vitamins', 13900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['vitamins','immunity','energy']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','vitamins','immunity','energy']::text[],
   '{"points_estimate": 695, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000004', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-vitamin-d-test', 'Vitamin D Test',
   'Überprüft den Vitamin D2 und D3 Gehalt. Wichtig für Immunsystem, Knochen und Stimmung.',
   'Der Vitamin D Test überprüft den Vitamin D2 und D3 Gehalt in deinem Blut. Wichtig für Immunsystem, Knochen und Stimmung. 1 analysierter Wert, Probenart: Trockenblut.',
   'DoctorBox', 'health-tests', 'nutrients-vitamins', 2999, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['vitamin-d','immunity','bone-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','vitamin-d','immunity','bone-health']::text[],
   '{"points_estimate": 150, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000005', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-vitamin-b12-holo-tc', 'Vitamin B12 Test - Holo TC',
   'Wichtig für Energie, Nervenfunktion und Blutbildung. Ideal für Veganer und Vegetarier.',
   'Der Vitamin B12 Test (Holo TC) zeigt, ob dein Körper optimal mit Vitamin B12 versorgt ist – wichtig für Energie, Nervenfunktion und Blutbildung. Ideal für Veganer und Vegetarier. 1 analysierter Wert, Probenart: Trockenblut.',
   'DoctorBox', 'health-tests', 'nutrients-vitamins', 3500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1550572017-edd951b55104?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['vitamin-b12','energy']::text[], ARRAY['vegan','vegetarian']::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','vitamin-b12','energy','nerve-function']::text[],
   '{"points_estimate": 175, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000006', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-nutrient-all-round-check', 'Nutrient All-round Check',
   'Umfassender Überblick über Vitamine, Mineralstoffe, Spurenelemente und Stoffwechselwerte – für eine ganzheitliche Beurteilung deiner Nährstoffversorgung.',
   'Der Nutrient All-Around Check bietet dir eine umfassende Übersicht über Vitamine, Mineralstoffe, Spurenelemente und Stoffwechselwerte – für eine ganzheitliche Beurteilung deiner Nährstoffversorgung und Gesundheit. 15 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'nutrients-vitamins', 18900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['nutrient-supply','metabolism']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','nutrients','vitamins','minerals','trace-elements']::text[],
   '{"points_estimate": 945, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000007', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-vitamin-b1-check', 'Vitamin B1 Check',
   'Zeigt, ob dein Körper ausreichend mit Thiamin versorgt ist – wichtig für Energie, Nervenfunktion und Konzentration.',
   'Der Vitamin B1 Check zeigt, ob dein Körper ausreichend mit Thiamin versorgt ist – wichtig für Energie, Nervenfunktion und Konzentration. 1 analysierter Wert, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'nutrients-vitamins', 5500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['energy','focus']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','vitamin-b1','energy','focus']::text[],
   '{"points_estimate": 275, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000008', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-vitamin-b6-check', 'Vitamin B6 Check',
   'Zeigt, ob dein Körper ausreichend mit Vitamin B6 versorgt ist. Vitamin B6 spielt eine zentrale Rolle bei Nervenfunktion, Hormonstoffwechsel, Immunsystem und Energieproduktion.',
   'Der Vitamin B6 Check zeigt, ob dein Körper ausreichend mit Vitamin B6 (Pyridoxin) versorgt ist. Vitamin B6 spielt eine zentrale Rolle bei Nervenfunktion, Hormonstoffwechsel, Immunsystem und Energieproduktion. 1 analysierter Wert, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'nutrients-vitamins', 5500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['hormone-balance','immunity']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','vitamin-b6','hormones','immunity']::text[],
   '{"points_estimate": 275, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000009', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-hormon-check-fuer-maenner', 'Hormon Check für Männer',
   'Untersucht zentrale Hormon- und Schilddrüsenwerte, die Einfluss auf Energie, Leistungsfähigkeit, Fruchtbarkeit und Wohlbefinden haben.',
   'Der Hormon Check für Männer untersucht zentrale Hormon- und Schilddrüsenwerte, die Einfluss auf Energie, Leistungsfähigkeit, Fruchtbarkeit und Wohlbefinden haben – für einen klaren Überblick über deine hormonelle Balance. 5 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'hormones', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['hormone-balance','mens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','hormones','thyroid','mens-health']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000000a', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-fruchtbarkeits-check-fuer-frauen', 'Fruchtbarkeits Check für Frauen',
   'Für Frauen mit Kinderwunsch oder Zyklusunregelmäßigkeiten. Auch sinnvoll zur hormonellen Standortbestimmung und Vorsorge.',
   'Der Fruchtbarkeits Check für Frauen untersucht 9 wichtige Hormone und ist geeignet für Frauen mit Kinderwunsch oder Zyklusunregelmäßigkeiten. Auch sinnvoll zur hormonellen Standortbestimmung und Vorsorge. 9 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'hormones', 14000, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['fertility','hormone-balance']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','fertility','hormones','womens-health']::text[],
   '{"points_estimate": 700, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000000b', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-testosteron-test', 'Testosteron Test',
   'Misst deinen Testosteronspiegel und zeigt, ob dein Hormonhaushalt Energie, Leistungsfähigkeit oder Wohlbefinden beeinflusst.',
   'Mit dem Testosteron Test misst du deinen Testosteronspiegel und erfährst, ob dein Hormonhaushalt Energie, Leistungsfähigkeit oder Wohlbefinden beeinflusst. 1 analysierter Wert, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'hormones', 4500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['hormone-balance','mens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','testosterone','hormones','mens-health']::text[],
   '{"points_estimate": 225, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000000c', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-schilddruesen-check-plus', 'Schilddrüsen Check Plus',
   'Umfassender Überblick über deine Schilddrüsenfunktion. Misst wichtige Schilddrüsenhormone und prüft zusätzlich auf Autoimmunreaktionen wie Hashimoto.',
   'Der Schilddrüsen Check Plus liefert dir einen umfassenden Überblick über deine Schilddrüsenfunktion. Er misst wichtige Schilddrüsenhormone und prüft zusätzlich auf Autoimmunreaktionen wie Hashimoto. Ideal bei Müdigkeit, Gewichtsschwankungen, Haarausfall oder hormonellen Beschwerden. 4 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'hormones', 8900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['thyroid-health','hormone-balance']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','thyroid','hormones','autoimmune']::text[],
   '{"points_estimate": 445, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000000d', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-hormon-check-fuer-frauen', 'Hormon Check für Frauen',
   'Für Frauen, die ihre Hormonbalance und Schilddrüsenfunktion überprüfen möchten. Ideal bei Kinderwunsch, Zyklusproblemen oder hormonellen Beschwerden.',
   'Der Hormon Check für Frauen gibt dir einen klaren Überblick über deine Hormonbalance und Schilddrüsenfunktion. Ideal bei Kinderwunsch, Zyklusproblemen oder hormonellen Beschwerden. 5 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'hormones', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['hormone-balance','womens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','hormones','thyroid','womens-health']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000000e', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-rundum-check-fuer-maenner', 'Rundum Check für Männer',
   'Für Männer, die ihre Herz-, Stoffwechsel-, Hormon- und Nierenwerte überprüfen möchten. Ideal zur Vorsorge oder bei Müdigkeit, Stress und Leistungsschwäche.',
   'Der Rundum Check für Männer analysiert 9 wichtige Blutwerte für Männer, die ihre Herz-, Stoffwechsel-, Hormon- und Nierenwerte überprüfen möchten. Ideal zur Vorsorge oder bei Müdigkeit, Stress und Leistungsschwäche. 9 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'longevity-fitness', 15900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['mens-health','cardio-health','metabolism']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','mens-health','cardio-health','metabolism']::text[],
   '{"points_estimate": 795, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000000f', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-abnehmen-set', 'Abnehmen-Set',
   'Überprüft 12 zentrale Blutwerte zu Schilddrüse, Blutzucker und weiteren Faktoren.',
   'Das Abnehmen-Set überprüft 12 zentrale Blutwerte zu Schilddrüse, Blutzucker und weiteren Faktoren. Für alle, die trotz Ernährung und Bewegung nur schwer abnehmen und mögliche hormonelle oder stoffwechselbedingte Ursachen verstehen möchten. 12 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'longevity-fitness', 12900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['weight-management','metabolism']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','weight-loss','metabolism','thyroid']::text[],
   '{"points_estimate": 645, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000010', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-stoffwechsel-check-plus', 'Stoffwechsel Check Plus',
   'Umfassender Überblick über Stoffwechsel-, Hormon- und Nierenwerte. Ideal zur Vorsorge oder bei Müdigkeit, Stress und unklaren Beschwerden.',
   'Der Stoffwechsel Check Plus gibt dir einen umfassenden Überblick über deine Stoffwechsel-, Hormon- und Nierenwerte. Ideal zur Vorsorge oder bei Müdigkeit, Stress und unklaren Beschwerden. 9 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'longevity-fitness', 8900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['metabolism','hormone-balance']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','metabolism','hormones','kidney']::text[],
   '{"points_estimate": 445, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000011', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-herz-kreislauf-check', 'Herz-Kreislauf Check',
   'Für alle, die ihre Herz- und Gefäßgesundheit überprüfen möchten. Ideal bei Risikofaktoren wie Bluthochdruck, erhöhten Blutfetten oder familiärer Vorbelastung.',
   'Der Herz-Kreislauf Check liefert dir einen umfassenden Überblick über Herz- und Gefäßgesundheit. Ideal bei Risikofaktoren wie Bluthochdruck, erhöhten Blutfetten oder familiärer Vorbelastung. 8 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'cardio', 8900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cardio-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cardio-health','blood-pressure','cholesterol']::text[],
   '{"points_estimate": 445, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000012', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-entzuendungs-check', 'Entzündungs-Check',
   'Für alle, die ihren Entzündungsstatus überprüfen möchten. Ideal bei Müdigkeit, Infektanfälligkeit oder unklaren Beschwerden.',
   'Mit dem Entzündungs-Check erkennst du sowohl akute als auch stille Entzündungsprozesse. Ideal bei Müdigkeit, Infektanfälligkeit oder unklaren Beschwerden. 4 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'cardio', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['immunity']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','inflammation','immunity']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000013', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-rundum-check-fuer-frauen', 'Rundum Check für Frauen',
   'Für Frauen, die ihre Herz-, Stoffwechsel-, Hormon- und Nährstoffwerte überprüfen möchten. Ideal zur Vorsorge oder bei Müdigkeit, hormonellen Schwankungen und Stress.',
   'Der Rundum Check für Frauen untersucht 9 zentrale Blutwerte zu Herz-, Stoffwechsel-, Hormon- und Nährstoffversorgung. Ideal zur Vorsorge oder bei Müdigkeit, hormonellen Schwankungen und Stress. 9 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'womens-health', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['womens-health','cardio-health','hormone-balance']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','womens-health','cardio-health','hormones']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000014', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-nieren-profil', 'Nieren Profil',
   'Überblick über zentrale Nieren- und Stoffwechselwerte. Für alle, die ihre Nierenfunktion vorsorglich überprüfen möchten.',
   'Das Nieren Profil gibt dir einen Überblick über zentrale Nieren- und Stoffwechselwerte. Für alle, die ihre Nierenfunktion vorsorglich überprüfen oder bei Risikofaktoren wie Bluthochdruck, Diabetes oder anhaltender Müdigkeit Klarheit erhalten möchten. 5 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'cardio', 6900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['prevention']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','kidney','prevention']::text[],
   '{"points_estimate": 345, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000015', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-lipid-check', 'Lipid Check',
   'Liefert dir einen schnellen Überblick über deine wichtigsten Blutfettwerte wie Cholesterin und Triglyceride.',
   'Der Lipid Check gibt dir einen schnellen Überblick über deine wichtigsten Blutfettwerte wie Cholesterin und Triglyceride. Er hilft dabei, Risiken für Herz-Kreislauf-Erkrankungen frühzeitig zu erkennen – bequem von zu Hause mit professioneller Laborauswertung. 4 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'cardio', 6900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cardio-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cholesterol','cardio-health']::text[],
   '{"points_estimate": 345, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000016', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-cortisol-check', 'Cortisol Check',
   'Für alle, die ihr Stresslevel und ihre hormonelle Balance überprüfen möchten. Ideal bei Stress, Erschöpfung oder Schlafproblemen.',
   'Der Cortisol Check liefert dir präzise Einblicke in deinen Cortisolspiegel. Für alle, die ihr Stresslevel und ihre hormonelle Balance überprüfen möchten. Ideal bei Stress, Erschöpfung oder Schlafproblemen. 1 analysierter Wert, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'longevity-fitness', 3500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['stress-reduction']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','stress','cortisol','sleep']::text[],
   '{"points_estimate": 175, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000017', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-bio-age', 'Bio Age - Dein biologisches Alter',
   'Analysiert neun Schlüsselparameter im Blut. Richtet sich an alle, die ihr biologisches Alter verstehen und aktiv beeinflussen möchten.',
   'Der Bio Age Test analysiert neun Schlüsselparameter im Blut. Das Bio Age Kit richtet sich an alle, die ihr biologisches Alter verstehen und aktiv beeinflussen möchten. Besonders angesprochen sind Menschen mit häufiger Müdigkeit, häufigen Infekten, Verdacht auf stille Entzündungen oder dem Wunsch nach gezielter Gesundheitsvorsorge – bequem von zu Hause aus. 9 analysierte Werte, Probenart: Kapillarblut (Serum).',
   'DoctorBox', 'health-tests', 'longevity-fitness', 19900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['longevity']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','biological-age','longevity','inflammation']::text[],
   '{"points_estimate": 995, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000018', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-neuro-vital-check', 'Neuro Vital Check',
   'Für alle, die ihre Nerven- und Energieversorgung überprüfen möchten. Ideal bei Müdigkeit, Stress und Konzentrationsproblemen.',
   'Der Neuro Vital Check untersucht 5 zentrale Blutwerte für Nerven- und Energieversorgung. Für alle, die ihre Nerven- und Energieversorgung überprüfen möchten. Ideal bei Müdigkeit, Stress und Konzentrationsproblemen. 5 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'longevity-fitness', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['focus','energy']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','nerve-function','energy','focus']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000019', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-hpv-high-risk', 'HPV (High Risk)',
   'Überprüft 12 verschiedene HPV Risiko-Typen. Für die Vorsorge von Gebärmutterhalskrebs.',
   'Der HPV (High Risk) Test überprüft 12 verschiedene HPV Risiko-Typen. Für die Vorsorge von Gebärmutterhalskrebs. 12 analysierte Werte, Probenart: Vaginalabstrich.',
   'DoctorBox', 'health-tests', 'womens-health', 8500, 10000, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening','womens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','hpv','cancer-screening','womens-health']::text[],
   '{"points_estimate": 425, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000001a', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-vaginalpilz', 'Vaginalpilz',
   'Überprüft auf 7 verschiedene Typen. Bei intensivem Juckreiz im Intimbereich.',
   'Der Vaginalpilz-Test überprüft auf 7 verschiedene Pilz-Typen. Geeignet bei intensivem Juckreiz im Intimbereich. 7 analysierte Werte, Probenart: Vaginalabstrich.',
   'DoctorBox', 'health-tests', 'womens-health', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['womens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','vaginal-health','womens-health']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000001b', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-antecrc', 'Personalisierte Darmkrebsprävention',
   'Der AnteCRC-Test bietet eine wissenschaftlich validierte Analyse. Ideal für gesundheitsbewusste Menschen – mit oder ohne familiäre Krebsbelastung. Ab 40 Jahren.',
   'Der AnteCRC-Test bietet eine wissenschaftlich validierte, personalisierte Analyse zur Darmkrebsprävention. Ideal für gesundheitsbewusste Menschen – mit oder ohne familiäre Krebsbelastung. Ab 40 Jahren. 1 analysierter Wert, Probenart: Wangenabstrich.',
   'DoctorBox', 'health-tests', 'dna-analysis', 25200, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','dna-analysis','colon-cancer']::text[],
   '{"points_estimate": 1260, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000001c', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-amh-test', 'Anti-Müller Hormontest',
   'Mit dem AMH-Test erhältst du eine einfache Einschätzung deiner ovariellen Reserve. Bei Kinderwunsch oder Familienplanung.',
   'Mit dem Anti-Müller Hormontest (AMH) erhältst du eine einfache Einschätzung deiner ovariellen Reserve. Geeignet bei Kinderwunsch oder Familienplanung. 1 analysierter Wert, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'hormones', 5000, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['fertility']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','fertility','amh','womens-health']::text[],
   '{"points_estimate": 250, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000001d', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-antemel', 'Personalisierte Melanomprävention',
   'Der AnteMEL-Test liefert eine wissenschaftlich fundierte Analyse. Ideal für gesundheitsbewusste Menschen – mit oder ohne familiäre Krebsbelastung. Ab 18 Jahren.',
   'Der AnteMEL-Test liefert eine wissenschaftlich fundierte, personalisierte Analyse zur Melanomprävention. Ideal für gesundheitsbewusste Menschen – mit oder ohne familiäre Krebsbelastung. Ab 18 Jahren. 1 analysierter Wert, Probenart: Wangenabstrich.',
   'DoctorBox', 'health-tests', 'dna-analysis', 25200, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','dna-analysis','skin-cancer']::text[],
   '{"points_estimate": 1260, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000001e', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-sti-trio-complete-frauen', 'STI Trio Complete für Frauen',
   'Überprüft 10 verschiedene Geschlechtskrankheiten. Für alle, die ein besonders umfassendes STI-Screening wünschen.',
   'Der STI Trio Complete für Frauen überprüft 10 verschiedene Geschlechtskrankheiten. Für alle, die ein besonders umfassendes STI-Screening wünschen. 10 analysierte Werte, Probenart: Vaginal-, Rektalabstrich und Trockenblut.',
   'DoctorBox', 'health-tests', 'sexual-health', 16990, 18400, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['sexual-health','womens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','sti-screening','sexual-health','womens-health']::text[],
   '{"points_estimate": 850, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000001f', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-antebc', 'Personalisierte Brustkrebsprävention',
   'Der AnteBC-Test bietet eine wissenschaftlich validierte Analyse. Besonders hilfreich für Frauen unter 50, um ein erhöhtes Risiko frühzeitig zu erkennen.',
   'Der AnteBC-Test bietet eine wissenschaftlich validierte, personalisierte Analyse zur Brustkrebsprävention. Besonders hilfreich für Frauen unter 50, um ein erhöhtes Risiko frühzeitig zu erkennen. 1 analysierter Wert, Probenart: Wangenabstrich.',
   'DoctorBox', 'health-tests', 'dna-analysis', 25200, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening','womens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','dna-analysis','breast-cancer']::text[],
   '{"points_estimate": 1260, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000020', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-sti-pro', 'STI Pro',
   'Überprüft 10 verschiedene Geschlechtskrankheiten. Für sexuell aktive Erwachsene mit mehreren Partnern.',
   'Der STI Pro Test überprüft 10 verschiedene Geschlechtskrankheiten. Für sexuell aktive Erwachsene mit mehreren Partnern. 10 analysierte Werte, Probenart: Urin & Trockenblut | Vaginalabstrich & Trockenblut.',
   'DoctorBox', 'health-tests', 'sexual-health', 12900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['sexual-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','sti-screening','sexual-health']::text[],
   '{"points_estimate": 645, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000021', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-sti-trio-complete-maenner', 'STI Trio Complete für Männer',
   'Überprüft 10 verschiedene Geschlechtskrankheiten. Für alle, die ein besonders umfassendes STI-Screening wünschen.',
   'Der STI Trio Complete für Männer überprüft 10 verschiedene Geschlechtskrankheiten. Für alle, die ein besonders umfassendes STI-Screening wünschen. 10 analysierte Werte, Probenart: Rektalabstrich + Urin + Trockenblut.',
   'DoctorBox', 'health-tests', 'sexual-health', 16990, 18400, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['sexual-health','mens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','sti-screening','sexual-health','mens-health']::text[],
   '{"points_estimate": 850, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000022', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-sti-standard', 'STI Standard',
   'Überprüft 5 verschiedene Geschlechtskrankheiten. Für neue Beziehungen oder wiederkehrende Kontrolle.',
   'Der STI Standard Test überprüft 5 verschiedene Geschlechtskrankheiten. Geeignet bei neuer Beziehung oder für wiederkehrende Kontrolle. 5 analysierte Werte, Probenart: Urin & Trockenblut | Vaginalabstrich & Trockenblut.',
   'DoctorBox', 'health-tests', 'sexual-health', 8000, 13500, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['sexual-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','sti-screening','sexual-health']::text[],
   '{"points_estimate": 400, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000023', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-sti-basic', 'STI Basic',
   'Testet dich auf 4 verschiedene Geschlechtskrankheiten. Allgemeine Vorsorge.',
   'Der STI Basic Test testet dich auf 4 verschiedene Geschlechtskrankheiten. Für die allgemeine Vorsorge. 4 analysierte Werte, Probenart: Urin, Vaginal- oder Rektalabstrich.',
   'DoctorBox', 'health-tests', 'sexual-health', 5500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['sexual-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','sti-screening','sexual-health']::text[],
   '{"points_estimate": 275, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000024', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-sti-select', 'STI Select',
   'Überprüft 3 verschiedene Geschlechtskrankheiten. Für gezielte Abklärung.',
   'Der STI Select Test überprüft 3 verschiedene Geschlechtskrankheiten. Für eine gezielte Abklärung. 3 analysierte Werte, Probenart: Trockenblut.',
   'DoctorBox', 'health-tests', 'sexual-health', 5000, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['sexual-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','sti-screening','sexual-health']::text[],
   '{"points_estimate": 250, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000025', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-sti-essential', 'STI Essential',
   'Überprüft 7 verschiedene Geschlechtskrankheiten. Allgemeine Vorsorge.',
   'Der STI Essential Test überprüft 7 verschiedene Geschlechtskrankheiten. Für die allgemeine Vorsorge. 7 analysierte Werte, Probenart: Urin oder Vaginalabstrich.',
   'DoctorBox', 'health-tests', 'sexual-health', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['sexual-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','sti-screening','sexual-health']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000026', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-darmkrebsvorsorge', 'Darmkrebsvorsorge',
   'Erkennt verstecktes Blut im Stuhl, ein mögliches Anzeichen für Darmkrebs. Für die Vorsorge von Darmkrebs.',
   'Die Darmkrebsvorsorge erkennt verstecktes Blut im Stuhl, ein mögliches Anzeichen für Darmkrebs. Für die Vorsorge von Darmkrebs. 1 analysierter Wert, Probenart: Stuhlprobe.',
   'DoctorBox', 'health-tests', 'prevention', 3500, 4000, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','colon-cancer','prevention']::text[],
   '{"points_estimate": 175, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000027', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-psa', 'PSA (Prostataspezifisches Antigen)',
   'Der Test misst den prostataspezifischen Antigenwert. Für die Vorsorge von Prostatakrebs.',
   'Der PSA-Test (Prostataspezifisches Antigen) misst den prostataspezifischen Antigenwert. Für die Vorsorge von Prostatakrebs. 1 analysierter Wert, Probenart: Trockenblut.',
   'DoctorBox', 'health-tests', 'prevention', 4490, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening','mens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','prostate','mens-health']::text[],
   '{"points_estimate": 225, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000028', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-hba1c', 'HbA1c (Langzeitblutzuckerwert)',
   'Behalte deinen Blutzucker im Blick. Für die Vorsorge von Diabetes.',
   'Der HbA1c-Test (Langzeitblutzuckerwert) hilft dir, deinen Blutzucker im Blick zu behalten – für die Vorsorge von Diabetes. 1 analysierter Wert, Probenart: Trockenblut.',
   'DoctorBox', 'health-tests', 'prevention', 4500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['prevention']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','diabetes','blood-sugar','prevention']::text[],
   '{"points_estimate": 225, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000029', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-leber-check', 'Leber Check',
   'Der Leber Check zeigt dir, ob deine Leberwerte im gesunden Bereich sind.',
   'Der Leber Check gibt dir einen Überblick über deine wichtigsten Leberwerte und zeigt, ob deine Leber gesund arbeitet. Ideal bei Müdigkeit, Verdauungsproblemen, erhöhter Alkohol- oder Medikamentenbelastung sowie zur Vorsorge. 4 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'prevention', 3500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['prevention']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','liver-health','prevention']::text[],
   '{"points_estimate": 175, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000002a', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-coloalert', 'ColoAlert',
   'Der innovative DNA-Stuhltest zur Darmkrebsvorsorge.',
   'ColoAlert® ist der innovative DNA-Stuhltest zur Darmkrebsvorsorge. Für Erwachsene ab 40 Jahren, die ihr Darmkrebsrisiko frühzeitig erkennen wollen. Probenart: Stuhlprobe.',
   'DoctorBox', 'health-tests', 'dna-analysis', 25798, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','dna-analysis','colon-cancer']::text[],
   '{"points_estimate": 1290, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000002b', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-leaky-gut-test', 'Leaky Gut Test',
   'Eine gestörte Darmbarriere kann Erschöpfung, Entzündungen und weitere Beschwerden verursachen.',
   'Der Leaky Gut Test beurteilt deine Darmgesundheit — eine gestörte Darmbarriere kann Erschöpfung, Entzündungen und weitere Beschwerden verursachen. 2 analysierte Werte, Probenart: Stuhlprobe.',
   'DoctorBox', 'health-tests', 'prevention', 9900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['digestive-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','gut-health','digestive-health']::text[],
   '{"points_estimate": 495, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000002c', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-allergietest-295', 'Allergietest (295 Allergene)',
   'Testet über 295 Allergene von Pollen, Tierhaaren bis zu Insektengifte. Ideal für ein umfassendes Allergieprofil.',
   'Der Allergietest testet über 295 Allergene von Pollen, Tierhaaren bis zu Insektengifte. Ideal für ein umfassendes Allergieprofil. 295 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'general-health', 17900, 22900, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['immunity']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','allergy','immunity']::text[],
   '{"points_estimate": 895, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000002d', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-aminosaeuren-profil', 'Aminosäuren Profil',
   'Finde heraus, wie gut dein Körper mit wichtigen Eiweißbausteinen versorgt ist. Für Sportler.',
   'Das Aminosäuren Profil zeigt dir, wie gut dein Körper mit wichtigen Eiweißbausteinen versorgt ist. Für Sportler. 16 analysierte Werte, Probenart: Trockenblut.',
   'DoctorBox', 'health-tests', 'general-health', 5990, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['fitness-performance']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','amino-acids','fitness','sports']::text[],
   '{"points_estimate": 300, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000002e', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-haemoglobin', 'Hämoglobin',
   'Ermittelt deinen Hämoglobinwert.',
   'Der Hämoglobin-Test ermittelt deinen Hämoglobinwert. Prüfe, ob deine Müdigkeit oder Erschöpfung durch Eisenmangel oder Blutarmut verursacht wird. 1 analysierter Wert, Probenart: Trockenblut.',
   'DoctorBox', 'health-tests', 'general-health', 3190, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['energy']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','iron','anemia','energy']::text[],
   '{"points_estimate": 160, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-00000000002f', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-fettstoffwechsel-analyse', 'Fettstoffwechsel Analyse',
   'Sorge aktiv für dein Herz. Überprüft Cholesterin- und Triglyceridwerte.',
   'Die Fettstoffwechsel Analyse gibt dir einen umfassenden Überblick über deinen Fettstoffwechsel — sorge aktiv für dein Herz. Überprüft Cholesterin- und Triglyceridwerte. Wichtig für Herz, Zellen und Entzündungsbalance. 9 analysierte Werte, Probenart: Kapillarblut.',
   'DoctorBox', 'health-tests', 'general-health', 8900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cardio-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cholesterol','cardio-health']::text[],
   '{"points_estimate": 445, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000030', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-voc-imo-test', 'VOC IMO Test',
   'Misst bestimmte Gase in deiner Atemluft, die auf ein intestinales Ungleichgewicht hinweisen können.',
   'Der VOC IMO Test misst bestimmte Gase in deiner Atemluft, die auf ein intestinales Ungleichgewicht hinweisen können. Zur Abklärung von Verdauungsproblemen und Blähungen. Probenart: Atemluft.',
   'DoctorBox', 'health-tests', 'general-health', 4500, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1615461066841-6116e61058f4?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['digestive-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','digestive-health','gut-health']::text[],
   '{"points_estimate": 225, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000031', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-antecancerw', 'Personalisierte Krebsprävention für Frauen',
   'Der AnteCancerW-Test liefert eine wissenschaftlich fundierte Analyse. Ideal für gesundheitsbewusste Frauen – mit oder ohne familiäre Krebsbelastung. Ab 35 Jahren.',
   'Der AnteCancerW-Test liefert eine wissenschaftlich fundierte, personalisierte Krebspräventions-Analyse für Frauen. Ideal für gesundheitsbewusste Frauen – mit oder ohne familiäre Krebsbelastung. Ab 35 Jahren. 3 analysierte Werte, Probenart: Wangenabstrich.',
   'DoctorBox', 'health-tests', 'dna-analysis', 30900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening','womens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','dna-analysis','womens-health']::text[],
   '{"points_estimate": 1545, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000032', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-antecancerm', 'Personalisierte Krebsprävention für Männer',
   'Der AnteCancerM-Test liefert eine wissenschaftlich fundierte Analyse. Ideal für gesundheitsbewusste Männer – mit oder ohne familiäre Krebsbelastung.',
   'Der AnteCancerM-Test liefert eine wissenschaftlich fundierte, personalisierte Krebspräventions-Analyse für Männer. Ideal für gesundheitsbewusste Männer – mit oder ohne familiäre Krebsbelastung. 3 analysierte Werte, Probenart: Wangenabstrich.',
   'DoctorBox', 'health-tests', 'dna-analysis', 30900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening','mens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','dna-analysis','mens-health']::text[],
   '{"points_estimate": 1545, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000033', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-antepc', 'Personalisierte Prostatakrebsprävention',
   'Der AntePC-Test liefert eine wissenschaftlich validierte Analyse. Ideal für gesundheitsbewusste Männer – mit oder ohne familiäre Krebsbelastung. Ab 40.',
   'Der AntePC-Test liefert eine wissenschaftlich validierte, personalisierte Analyse zur Prostatakrebsprävention. Ideal für gesundheitsbewusste Männer – mit oder ohne familiäre Krebsbelastung. Ab 40 Jahren. 1 analysierter Wert, Probenart: Wangenabstrich.',
   'DoctorBox', 'health-tests', 'dna-analysis', 25200, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1499125562588-29fb8a56b5d5?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['cancer-screening','mens-health']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','cancer-screening','dna-analysis','prostate']::text[],
   '{"points_estimate": 1260, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000034', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-coffeegen', 'COFFEEGEN',
   'Hilft dir herauszufinden, wie dein Körper auf Koffein reagiert.',
   'COFFEEGEN hilft dir herauszufinden, wie dein Körper auf Koffein reagiert. Für gesundheits- und genussbewusste Kaffeetrinker:innen. Probenart: Speichel.',
   'DoctorBox', 'health-tests', 'dna-analysis', 6995, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1596363505729-4190a9506133?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['genetics']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','genetics','caffeine','dna-analysis']::text[],
   '{"points_estimate": 350, "currency": "EUR"}'::jsonb, true, false),

  ('d0c70000-0000-4000-8000-000000000035', 'd0c706b0-0000-4000-8000-000000000001', 'doctorbox',
   'doctorbox-neotes-bioage', 'neotes bioAge Test',
   'Bestimmt dein biologisches Alter anhand von DNA-Methylierung.',
   'Der neotes bioAge Test bestimmt dein biologisches Alter anhand von DNA-Methylierung. Um zu verstehen, wie sich Umwelt und Lebensstil auf deinen Alterungsprozess ausgewirkt haben. Probenart: Blut.',
   'DoctorBox', 'health-tests', 'dna-analysis', 29900, NULL, 'EUR',
   ARRAY['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=800&fit=crop','https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=800&fit=crop']::text[],
   'https://shop.doctorbox.de/VITANALAND', 'in_stock', NULL, NULL, 'DE', 'EU',
   ARRAY['DE','AT','CH','FR','IT','ES','NL','BE','PL','SE','DK','FI','GB','IE']::text[], ARRAY['EU','UK']::text[],
   ARRAY['longevity']::text[], ARRAY[]::text[], ARRAY[]::text[],
   ARRAY['diagnostics','self-testing','biological-age','dna-analysis','longevity']::text[],
   '{"points_estimate": 1495, "currency": "EUR"}'::jsonb, true, false)
ON CONFLICT (source_network, source_product_id) DO UPDATE SET
  merchant_id = EXCLUDED.merchant_id, title = EXCLUDED.title, description = EXCLUDED.description,
  description_long = EXCLUDED.description_long, brand = EXCLUDED.brand, category = EXCLUDED.category,
  subcategory = EXCLUDED.subcategory, price_cents = EXCLUDED.price_cents,
  compare_at_price_cents = EXCLUDED.compare_at_price_cents, currency = EXCLUDED.currency,
  images = EXCLUDED.images, affiliate_url = EXCLUDED.affiliate_url, availability = EXCLUDED.availability,
  origin_country = EXCLUDED.origin_country, origin_region = EXCLUDED.origin_region,
  ships_to_countries = EXCLUDED.ships_to_countries, ships_to_regions = EXCLUDED.ships_to_regions,
  health_goals = EXCLUDED.health_goals, dietary_tags = EXCLUDED.dietary_tags,
  ingredients_primary = EXCLUDED.ingredients_primary, topic_keys = EXCLUDED.topic_keys,
  reward_preview = EXCLUDED.reward_preview, is_active = true, updated_at = now();

COMMIT;

-- =====================================================================================
-- DOWN (rollback) — run manually or as a reverting migration if needed:
--
-- BEGIN;
-- DELETE FROM products WHERE source_network = 'doctorbox';
-- DELETE FROM merchants WHERE id = 'd0c706b0-0000-4000-8000-000000000001';
-- COMMIT;
-- =====================================================================================
