-- VTID-02047: Auto-triage routine (parent plan PR 12)
--
-- Extends the classifier (PR 6) with auto-actions for high-confidence
-- tickets. Per the routines autonomy contract: each tick either acts
-- (auto-resolve / auto-spec) OR leaves the ticket in *_ready state for
-- the supervisor — never produces a brief.
--
-- v1 conservative thresholds:
--   support_question + classifier confidence ≥ 0.5 + age > 5 min
--     → auto-draft answer (status='answer_ready', resolver=sage). Supervisor
--       still clicks Send Answer; full auto-send is a follow-up flag.
--   bug + p3 + dedupe-clean + age > 5 min
--     → auto-draft spec (status='spec_ready', resolver=devon). Supervisor
--       still clicks Approve & Fix; auto-approve is a follow-up flag.
--   account_issue + low-risk runbook (password reset / email resend)
--     → auto-draft resolution (status='spec_ready', resolver=mira).
--
-- Tickets that don't match auto-action criteria stay in 'triaged' for the
-- supervisor inbox.

CREATE OR REPLACE FUNCTION public.auto_triage_pending_feedback_tickets()
RETURNS TABLE (
  auto_drafted_answers INT,
  auto_drafted_specs INT,
  auto_drafted_resolutions INT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_answers INT := 0;
  v_specs INT := 0;
  v_resolutions INT := 0;
  r RECORD;
BEGIN
  FOR r IN
    SELECT id, kind, priority, classifier_meta, raw_transcript, structured_fields
      FROM public.feedback_tickets
     WHERE status = 'triaged'
       AND triaged_at < NOW() - INTERVAL '5 minutes'
       AND duplicate_of IS NULL
       AND classifier_meta IS NOT NULL
     ORDER BY triaged_at
     LIMIT 100
  LOOP
    -- support_question → Sage drafts answer if confidence high enough
    IF r.kind = 'support_question'
       AND COALESCE((r.classifier_meta->>'pick_confidence')::REAL, 0) >= 0.5 THEN
      UPDATE public.feedback_tickets
         SET status = 'answer_ready',
             resolver_agent = 'sage',
             draft_answer_md = '**Sage auto-draft (placeholder)**' || chr(10) || chr(10) ||
                              '_Generated by auto_triage routine. LLM-backed retrieval lands in resolver-agents follow-up._' || chr(10) || chr(10) ||
                              'User asked: ' || COALESCE(r.raw_transcript, '(no transcript)')
       WHERE id = r.id;
      v_answers := v_answers + 1;

    -- p3 bug → Devon drafts spec (low-priority, low-risk to auto-process)
    ELSIF r.kind = 'bug' AND r.priority = 'p3' THEN
      UPDATE public.feedback_tickets
         SET status = 'spec_ready',
             resolver_agent = 'devon',
             spec_md = '# Devon auto-draft spec (placeholder)' || chr(10) ||
                      '## User report' || chr(10) || COALESCE(r.raw_transcript, '(no transcript)') || chr(10) || chr(10) ||
                      '## Root cause hypothesis' || chr(10) || 'TBD' || chr(10) || chr(10) ||
                      '## Risk + rollback' || chr(10) || 'Low (p3 ticket).' || chr(10) || chr(10) ||
                      '_Generated by auto_triage routine._'
       WHERE id = r.id;
      v_specs := v_specs + 1;

    -- account_issue with low-risk keywords → Mira drafts resolution
    ELSIF r.kind = 'account_issue'
       AND COALESCE(r.raw_transcript, '') ~* '(password|email|verification|verify)' THEN
      UPDATE public.feedback_tickets
         SET status = 'spec_ready',
             resolver_agent = 'mira',
             resolution_md = '# Mira auto-draft resolution (placeholder)' || chr(10) ||
                            '## User report' || chr(10) || COALESCE(r.raw_transcript, '(no transcript)') || chr(10) || chr(10) ||
                            '## Proposed action' || chr(10) || 'Trigger password reset or resend verification email.' || chr(10) || chr(10) ||
                            '## Risk' || chr(10) || 'Low — runbook covered.' || chr(10) || chr(10) ||
                            '_Generated by auto_triage routine. Supervisor approves before action._'
       WHERE id = r.id;
      v_resolutions := v_resolutions + 1;
    END IF;
  END LOOP;

  RETURN QUERY SELECT v_answers, v_specs, v_resolutions;
END;
$$;

GRANT EXECUTE ON FUNCTION public.auto_triage_pending_feedback_tickets() TO service_role;

-- Schedule alongside the classifier — same 5-minute pg_cron tick.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    PERFORM cron.unschedule('feedback-auto-triage')
      WHERE EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'feedback-auto-triage');
    PERFORM cron.schedule(
      'feedback-auto-triage',
      '*/5 * * * *',
      $cron$SELECT public.auto_triage_pending_feedback_tickets()$cron$
    );
  END IF;
END
$$;
