name: CICDL-CORE-LINT-SERVICES

on:
  pull_request:
    branches: [main, trunk, develop, release/**]
    paths:
      - 'services/**'
  push:
    branches: [main, trunk]
    paths:
      - 'services/**'

run-name: 'Services Lint [VTID: DEV-CICDL-0033] (${{ github.ref_name }})'

jobs:
  lint-services:
    name: Validate Services Structure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check services directory structure
        run: |
          echo "🔍 Validating services directory structure..."
          
          violations=0
          
          if [ ! -d "services" ]; then
            echo "❌ ERROR: /services directory not found"
            exit 1
          fi
          
          echo "✅ /services directory exists"
          echo ""
          
          echo "📋 Found services:"
          find services -mindepth 1 -maxdepth 3 -type d | sort
          echo ""
      
      - name: Validate manifest.json presence
        run: |
          echo "🔍 Checking for manifest.json in each service..."
          echo ""
          
          violations=0
          services_checked=0
          
          # Check agents - look for manifest.json at the direct agent level
          for agent_dir in services/agents/*/; do
            if [ -d "$agent_dir" ]; then
              services_checked=$((services_checked + 1))
              agent_name=$(basename "$agent_dir")
              
              if [ -f "${agent_dir}manifest.json" ]; then
                echo "✅ ${agent_dir}"
              else
                echo "❌ Missing: ${agent_dir}manifest.json"
                violations=$((violations + 1))
              fi
            fi
          done
          
          # Check MCP services
          for mcp_dir in services/mcp/*/; do
            if [ -d "$mcp_dir" ]; then
              services_checked=$((services_checked + 1))
              
              if [ -f "${mcp_dir}manifest.json" ]; then
                echo "✅ $mcp_dir"
              else
                echo "❌ Missing: ${mcp_dir}manifest.json"
                violations=$((violations + 1))
              fi
            fi
          done
          
          # Check gateway
          if [ -d "services/gateway" ]; then
            services_checked=$((services_checked + 1))
            
            if [ -f "services/gateway/manifest.json" ]; then
              echo "✅ services/gateway/"
            else
              echo "❌ Missing: services/gateway/manifest.json"
              violations=$((violations + 1))
            fi
          fi
          
          # Check deploy-watcher
          if [ -d "services/deploy-watcher" ]; then
            services_checked=$((services_checked + 1))
            
            if [ -f "services/deploy-watcher/manifest.json" ]; then
              echo "✅ services/deploy-watcher/"
            else
              echo "❌ Missing: services/deploy-watcher/manifest.json"
              violations=$((violations + 1))
            fi
          fi
          
          echo ""
          echo "Services checked: $services_checked"
          echo "Violations: $violations"
          
          if [ $violations -gt 0 ]; then
            echo ""
            echo "❌ FAILURE: $violations service(s) missing manifest.json"
            exit 1
          fi
          
          echo "✅ All services have manifest.json files"
      
      - name: Validate manifest.json schema
        run: |
          echo "🔍 Validating manifest.json schema..."
          echo ""
          
          violations=0
          manifests=$(find services -maxdepth 3 -name "manifest.json" -type f)
          
          if [ -z "$manifests" ]; then
            echo "⚠️  No manifest.json files found"
            exit 0
          fi
          
          for manifest in $manifests; do
            echo "Checking: $manifest"
            
            if ! jq empty "$manifest" 2>/dev/null; then
              echo "  ❌ Invalid JSON syntax"
              violations=$((violations + 1))
              continue
            fi
            
            # Check for required fields - support both old and new schema
            name=$(jq -r '.name // empty' "$manifest")
            vtid=$(jq -r '.vtid // empty' "$manifest")
            vt_layer=$(jq -r '.vt_layer // .layer // empty' "$manifest")
            vt_module=$(jq -r '.vt_module // .module // empty' "$manifest")
            
            if [ -z "$name" ]; then
              echo "  ❌ Missing required field: name"
              violations=$((violations + 1))
            fi
            
            # Either vtid or both vt_layer/vt_module required
            if [ -z "$vtid" ] && ([ -z "$vt_layer" ] || [ -z "$vt_module" ]); then
              echo "  ⚠️  Warning: Missing vtid or vt_layer/vt_module"
            fi
            
            if [ $violations -eq 0 ]; then
              echo "  ✅ Valid: $name"
            fi
          done
          
          echo ""
          
          if [ $violations -gt 0 ]; then
            echo "❌ FAILURE: $violations manifest validation error(s)"
            exit 1
          fi
          
          echo "✅ All manifests are valid"
      
      - name: Check naming conventions
        run: |
          echo "🔍 Checking top-level service naming conventions..."
          echo ""
          
          violations=0
          
          # Only check top-level service directories (maxdepth 2)
          # Internal subdirectories can follow language conventions (e.g., Python snake_case)
          while IFS= read -r dir; do
            dirname=$(basename "$dir")
            
            # Skip hidden directories and node_modules
            if [[ "$dirname" == .* ]] || [[ "$dirname" == "node_modules" ]]; then
              continue
            fi
            
            # Check for uppercase or underscore
            if echo "$dirname" | grep -qE '[A-Z]|_'; then
              echo "❌ Non-kebab-case directory: $dir"
              echo "   Top-level service directories must use kebab-case"
              violations=$((violations + 1))
            fi
          done < <(find services -mindepth 1 -maxdepth 2 -type d -not -path "*/node_modules/*")
          
          if [ $violations -gt 0 ]; then
            echo ""
            echo "❌ FAILURE: $violations naming convention violation(s)"
            echo ""
            echo "📘 Phase 2B Standard: Top-level service directories must use kebab-case"
            echo "   Internal subdirectories may follow language conventions"
            exit 1
          fi
          
          echo "✅ All top-level service directories follow kebab-case convention"
      
      - name: Summary
        if: success()
        run: |
          echo "✅ Services Lint Checks Complete"
          echo ""
          echo "Checks passed:"
          echo "  ✅ Services directory structure valid"
          echo "  ✅ All services have manifest.json"
          echo "  ✅ All manifests have valid schema"
          echo "  ✅ Naming conventions followed"
