name: Daily Status Update
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:
jobs:
  update-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests pyyaml
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          WEBHOOK_URL: ${{ secrets.VITANA_CHAT_WEBHOOK }}
        run: python3 scripts/ci/collect-status.py
      - run: |
          git config user.name "Vitana Automation"
          git config user.email "automation@vitana.dev"
          git add docs/STATUS.md README.md 2>/dev/null || true
          if git diff --quiet --cached; then echo "No changes"; else git commit -m "chore: daily status update - $(date -u +'%Y-%m-%d %H:%M:%S UTC')" && git push; fi
