name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 492.0.0"

      - name: Deploy to Cloud Run
        run: |
          set -euo pipefail
          gcloud run deploy crewai-gcp \
            --image=europe-west1-docker.pkg.dev/lovable-vitana-vers1/app/crewai-gcp:alive \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated \
            --port=8080 \
            --no-use-http2 \
            --service-account=lovable-vitana-vers1@appspot.gserviceaccount.com

      - name: Smoke test (dynamic URL, 3-path probe)
        run: |
          set -euo pipefail
          URL="$(gcloud run services describe crewai-gcp \
            --project=lovable-vitana-vers1 \
            --region=europe-west1 \
            --format='value(status.url)')"
          echo "Resolved URL: $URL"
          curl -fsS "$URL/" || curl -fsS "$URL/alive" || curl -fsS "$URL/healthz"
